set_property PACKAGE_PIN H5 [get_ports {LED[0]}]
set_property PACKAGE_PIN J5 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN A8 [get_ports {SW[0]}]
set_property PACKAGE_PIN C11 [get_ports {SW[1]}]
set_property PACKAGE_PIN C10 [get_ports {SW[2]}]
set_property PACKAGE_PIN A10 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]

set_property PACKAGE_PIN E3 [get_ports CLK_100Mhz]
set_property PACKAGE_PIN D9 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100Mhz]
set_property PACKAGE_PIN T9 [get_ports {LED[2]}]
set_property PACKAGE_PIN T10 [get_ports {LED[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DONE[0]}]
set_property PACKAGE_PIN F6 [get_ports {DONE[0]}]

set_property PACKAGE_PIN G4 [get_ports {START[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {START[0]}]

set_property PACKAGE_PIN K1 [get_ports {ERROR[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ERROR[0]}]

set_property PACKAGE_PIN H5 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
