// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processor_processor,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.061600,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1735,HLS_SYN_LUT=2966,HLS_VERSION=2023_1_1}" *)

module processor (
        ap_clk,
        ap_rst,
        memory_address0,
        memory_ce0,
        memory_we0,
        memory_d0,
        memory_q0,
        o_error
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
output  [16:0] memory_address0;
output   memory_ce0;
output   memory_we0;
output  [31:0] memory_d0;
input  [31:0] memory_q0;
output  [0:0] o_error;

reg[16:0] memory_address0;
reg memory_ce0;
reg memory_we0;
reg[31:0] memory_d0;

reg   [31:0] g_pc;
reg   [0:0] g_error;
reg   [31:0] p_ZL6g_xreg_1;
reg   [31:0] p_ZL6g_xreg_2;
reg   [31:0] p_ZL6g_xreg_3;
reg   [31:0] p_ZL6g_xreg_4;
reg   [31:0] p_ZL6g_xreg_5;
reg   [31:0] p_ZL6g_xreg_6;
reg   [31:0] p_ZL6g_xreg_7;
reg   [31:0] p_ZL6g_xreg_8;
reg   [31:0] p_ZL6g_xreg_9;
reg   [31:0] p_ZL6g_xreg_10;
reg   [31:0] p_ZL6g_xreg_11;
reg   [31:0] p_ZL6g_xreg_12;
reg   [31:0] p_ZL6g_xreg_13;
reg   [31:0] p_ZL6g_xreg_14;
reg   [31:0] p_ZL6g_xreg_15;
reg   [31:0] p_ZL6g_xreg_16;
reg   [31:0] p_ZL6g_xreg_17;
reg   [31:0] p_ZL6g_xreg_18;
reg   [31:0] p_ZL6g_xreg_19;
reg   [31:0] p_ZL6g_xreg_20;
reg   [31:0] p_ZL6g_xreg_21;
reg   [31:0] p_ZL6g_xreg_22;
reg   [31:0] p_ZL6g_xreg_23;
reg   [31:0] p_ZL6g_xreg_24;
reg   [31:0] p_ZL6g_xreg_25;
reg   [31:0] p_ZL6g_xreg_26;
reg   [31:0] p_ZL6g_xreg_27;
reg   [31:0] p_ZL6g_xreg_28;
reg   [31:0] p_ZL6g_xreg_29;
reg   [31:0] p_ZL6g_xreg_30;
reg   [31:0] p_ZL6g_xreg_31;
reg   [31:0] old_pc_reg_2007;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] result_1_fu_777_p2;
reg   [31:0] result_1_reg_2023;
wire    ap_CS_fsm_state2;
wire   [6:0] op_code_fu_782_p1;
reg   [6:0] op_code_reg_2063;
wire   [2:0] funct3_fu_786_p4;
reg   [2:0] funct3_reg_2068;
reg   [6:0] funct7_reg_2073;
reg   [4:0] rd_reg_2078;
wire  signed [31:0] sext_ln40_fu_866_p1;
reg  signed [31:0] sext_ln40_reg_2082;
wire  signed [11:0] imm_I_fu_870_p4;
reg   [11:0] imm_I_reg_2087;
wire  signed [31:0] sext_ln41_fu_880_p1;
reg  signed [31:0] sext_ln41_reg_2093;
wire  signed [31:0] sext_ln42_fu_926_p1;
reg  signed [31:0] sext_ln42_reg_2098;
wire   [11:0] tmp_4_fu_950_p3;
reg   [11:0] tmp_4_reg_2103;
wire   [31:0] imm_U_fu_968_p3;
reg   [31:0] imm_U_reg_2108;
wire   [31:0] source1_fu_1120_p34;
reg   [31:0] source1_reg_2113;
wire   [31:0] source2_fu_1190_p34;
reg   [31:0] source2_reg_2124;
wire   [0:0] grp_fu_674_p2;
reg   [0:0] icmp_ln96_reg_2139;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln91_reg_2144;
wire   [0:0] grp_fu_678_p2;
reg   [0:0] icmp_ln86_reg_2149;
reg   [0:0] icmp_ln81_reg_2154;
wire   [0:0] grp_fu_682_p2;
reg   [0:0] icmp_ln76_reg_2159;
reg   [0:0] icmp_ln71_reg_2164;
wire   [31:0] select_ln96_fu_1266_p3;
wire    ap_CS_fsm_state4;
wire   [31:0] select_ln91_fu_1272_p3;
wire   [31:0] select_ln86_fu_1278_p3;
wire   [31:0] select_ln81_fu_1284_p3;
wire   [31:0] select_ln76_fu_1290_p3;
wire   [31:0] select_ln71_fu_1296_p3;
wire   [31:0] add_ln64_fu_1302_p2;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln59_fu_1306_p2;
reg   [0:0] tmp_11_reg_2209;
wire    ap_CS_fsm_state6;
reg   [31:0] trunc_ln112_1_reg_2215;
reg   [31:0] trunc_ln112_2_reg_2220;
wire   [1:0] trunc_ln113_fu_1356_p1;
reg   [1:0] trunc_ln113_reg_2225;
wire   [1:0] trunc_ln113_1_fu_1360_p1;
reg   [1:0] trunc_ln113_1_reg_2230;
reg   [0:0] tmp_9_reg_2235;
reg   [31:0] trunc_ln165_1_reg_2241;
reg   [31:0] trunc_ln165_2_reg_2246;
wire   [1:0] trunc_ln166_fu_1410_p1;
reg   [1:0] trunc_ln166_reg_2251;
wire   [1:0] trunc_ln166_1_fu_1414_p1;
reg   [1:0] trunc_ln166_1_reg_2256;
reg   [31:0] result_reg_2261;
reg   [0:0] write_back_reg_2266;
wire   [2:0] select_ln113_fu_1457_p3;
reg   [2:0] select_ln113_reg_2271;
wire    ap_CS_fsm_state7;
wire   [2:0] select_ln166_fu_1578_p3;
reg   [2:0] select_ln166_reg_2343;
reg   [16:0] memory_addr_8_reg_2350;
reg   [16:0] memory_addr_7_reg_2355;
reg   [16:0] memory_addr_6_reg_2360;
reg   [16:0] memory_addr_5_reg_2365;
reg   [16:0] memory_addr_4_reg_2370;
reg   [16:0] memory_addr_3_reg_2375;
wire    call_ret_execute_arithm_fu_660_ap_ready;
wire   [0:0] call_ret_execute_arithm_fu_660_g_error;
wire    call_ret_execute_arithm_fu_660_g_error_ap_vld;
wire   [31:0] call_ret_execute_arithm_fu_660_ap_return_0;
wire   [0:0] call_ret_execute_arithm_fu_660_ap_return_1;
reg   [31:0] g_pc_new_7_reg_466;
wire   [0:0] ap_phi_mux_write_back_1_phi_fu_496_p20;
reg   [0:0] write_back_1_reg_491;
reg   [31:0] result_15_reg_527;
reg   [31:0] ap_phi_mux_g_pc_new_8_phi_fu_555_p38;
reg   [31:0] g_pc_new_8_reg_552;
wire    ap_CS_fsm_state8;
reg   [31:0] ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
reg   [31:0] p_0_0_0470_reg_596;
wire   [31:0] zext_ln154_1_fu_1638_p1;
wire   [31:0] zext_ln152_1_fu_1647_p1;
wire   [31:0] zext_ln147_1_fu_1652_p1;
wire   [31:0] zext_ln145_1_fu_1657_p1;
wire   [31:0] zext_ln143_1_fu_1662_p1;
wire   [31:0] zext_ln141_1_fu_1671_p1;
wire  signed [31:0] sext_ln133_fu_1676_p1;
wire  signed [31:0] sext_ln131_fu_1685_p1;
wire  signed [31:0] sext_ln126_fu_1690_p1;
wire  signed [31:0] sext_ln124_fu_1695_p1;
wire  signed [31:0] sext_ln122_fu_1700_p1;
wire  signed [31:0] sext_ln120_fu_1709_p1;
reg   [31:0] ap_phi_mux_g_pc_new_9_phi_fu_650_p6;
wire   [63:0] zext_ln28_fu_772_p1;
wire   [63:0] zext_ln154_fu_1476_p1;
wire   [63:0] zext_ln152_fu_1481_p1;
wire   [63:0] zext_ln147_fu_1486_p1;
wire   [63:0] zext_ln145_fu_1491_p1;
wire   [63:0] zext_ln143_fu_1496_p1;
wire   [63:0] zext_ln141_fu_1501_p1;
wire   [63:0] zext_ln137_fu_1506_p1;
wire   [63:0] zext_ln133_fu_1511_p1;
wire   [63:0] zext_ln131_fu_1516_p1;
wire   [63:0] zext_ln126_fu_1521_p1;
wire   [63:0] zext_ln124_fu_1526_p1;
wire   [63:0] zext_ln122_fu_1531_p1;
wire   [63:0] zext_ln120_fu_1536_p1;
wire   [63:0] zext_ln190_fu_1597_p1;
wire   [63:0] zext_ln186_fu_1602_p1;
wire   [63:0] zext_ln184_fu_1607_p1;
wire   [63:0] zext_ln179_fu_1612_p1;
wire   [63:0] zext_ln177_fu_1617_p1;
wire   [63:0] zext_ln175_fu_1622_p1;
wire   [63:0] zext_ln173_fu_1627_p1;
wire   [0:0] icmp_ln114_fu_1464_p2;
wire   [0:0] icmp_ln167_fu_1585_p2;
wire   [0:0] or_ln26_fu_760_p2;
wire   [31:0] tmp_18_fu_1717_p5;
wire   [31:0] tmp_17_fu_1733_p5;
wire   [31:0] tmp_16_fu_1749_p5;
wire   [31:0] tmp_15_fu_1765_p5;
wire   [31:0] tmp_14_fu_1781_p5;
wire   [31:0] tmp_13_fu_1797_p5;
wire   [1:0] trunc_ln26_fu_734_p1;
wire   [0:0] icmp_ln26_fu_738_p2;
wire   [0:0] icmp_ln26_1_fu_754_p2;
wire   [16:0] lshr_ln_fu_744_p4;
wire   [0:0] tmp_1_fu_844_p3;
wire   [0:0] tmp_fu_836_p3;
wire   [5:0] tmp_s_fu_826_p4;
wire   [3:0] tmp7_fu_816_p4;
wire   [12:0] imm_B_fu_852_p6;
wire   [7:0] tmp_5_fu_902_p4;
wire   [0:0] tmp_3_fu_894_p3;
wire   [9:0] tmp_2_fu_884_p4;
wire   [20:0] imm_J_fu_912_p6;
wire   [6:0] tmp_7_fu_940_p4;
wire   [4:0] tmp_6_fu_930_p4;
wire   [19:0] tmp_8_fu_958_p4;
wire   [4:0] source1_fu_1120_p33;
wire   [4:0] source2_fu_1190_p33;
wire   [31:0] grp_fu_686_p2;
wire   [33:0] zext_ln112_fu_1310_p1;
wire  signed [33:0] sext_ln112_fu_1313_p1;
wire   [33:0] add_ln112_fu_1316_p2;
wire   [33:0] sub_ln112_fu_1330_p2;
wire   [33:0] zext_ln165_fu_1364_p1;
wire  signed [33:0] sext_ln165_fu_1367_p1;
wire   [33:0] add_ln165_fu_1370_p2;
wire   [33:0] sub_ln165_fu_1384_p2;
wire   [31:0] sub_ln112_1_fu_1426_p2;
wire   [2:0] p_and_t_fu_1437_p3;
wire   [2:0] sub_ln113_fu_1444_p2;
wire   [2:0] tmp_12_fu_1450_p3;
wire   [31:0] pos_1_fu_1431_p3;
wire   [31:0] sub_ln165_1_fu_1547_p2;
wire   [2:0] p_and_t3_fu_1558_p3;
wire   [2:0] sub_ln166_fu_1565_p2;
wire   [2:0] tmp_10_fu_1571_p3;
wire   [31:0] pos_fu_1552_p3;
wire   [15:0] grp_fu_690_p4;
wire   [15:0] result_13_fu_1643_p1;
wire   [7:0] grp_fu_700_p4;
wire   [7:0] grp_fu_710_p4;
wire   [7:0] grp_fu_720_p4;
wire   [7:0] result_9_fu_1667_p1;
wire   [15:0] result_7_fu_1681_p1;
wire   [7:0] result_3_fu_1705_p1;
wire   [15:0] trunc_ln186_fu_1714_p1;
wire   [15:0] trunc_ln184_fu_1730_p1;
wire   [7:0] trunc_ln179_fu_1746_p1;
wire   [7:0] trunc_ln177_fu_1762_p1;
wire   [7:0] trunc_ln175_fu_1778_p1;
wire   [7:0] trunc_ln173_fu_1794_p1;
reg   [7:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_condition_481;
reg    ap_condition_484;
reg    ap_condition_409;
reg    ap_condition_414;
reg    ap_condition_419;
reg    ap_condition_423;
reg    ap_condition_428;
reg    ap_condition_432;
reg    ap_condition_436;
reg    ap_condition_440;
reg    ap_condition_444;
reg    ap_condition_448;
reg    ap_condition_452;
reg    ap_condition_456;
reg    ap_condition_461;
reg    ap_condition_1517;
reg    ap_condition_1521;
reg    ap_condition_1525;
reg    ap_condition_1529;
reg    ap_condition_1533;
reg    ap_condition_1537;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 g_pc = 32'd0;
#0 g_error = 1'd0;
#0 p_ZL6g_xreg_1 = 32'd0;
#0 p_ZL6g_xreg_2 = 32'd0;
#0 p_ZL6g_xreg_3 = 32'd0;
#0 p_ZL6g_xreg_4 = 32'd0;
#0 p_ZL6g_xreg_5 = 32'd0;
#0 p_ZL6g_xreg_6 = 32'd0;
#0 p_ZL6g_xreg_7 = 32'd0;
#0 p_ZL6g_xreg_8 = 32'd0;
#0 p_ZL6g_xreg_9 = 32'd0;
#0 p_ZL6g_xreg_10 = 32'd0;
#0 p_ZL6g_xreg_11 = 32'd0;
#0 p_ZL6g_xreg_12 = 32'd0;
#0 p_ZL6g_xreg_13 = 32'd0;
#0 p_ZL6g_xreg_14 = 32'd0;
#0 p_ZL6g_xreg_15 = 32'd0;
#0 p_ZL6g_xreg_16 = 32'd0;
#0 p_ZL6g_xreg_17 = 32'd0;
#0 p_ZL6g_xreg_18 = 32'd0;
#0 p_ZL6g_xreg_19 = 32'd0;
#0 p_ZL6g_xreg_20 = 32'd0;
#0 p_ZL6g_xreg_21 = 32'd0;
#0 p_ZL6g_xreg_22 = 32'd0;
#0 p_ZL6g_xreg_23 = 32'd0;
#0 p_ZL6g_xreg_24 = 32'd0;
#0 p_ZL6g_xreg_25 = 32'd0;
#0 p_ZL6g_xreg_26 = 32'd0;
#0 p_ZL6g_xreg_27 = 32'd0;
#0 p_ZL6g_xreg_28 = 32'd0;
#0 p_ZL6g_xreg_29 = 32'd0;
#0 p_ZL6g_xreg_30 = 32'd0;
#0 p_ZL6g_xreg_31 = 32'd0;
#0 ap_CS_fsm = 8'd1;
end

processor_execute_arithm call_ret_execute_arithm_fu_660(
    .ap_ready(call_ret_execute_arithm_fu_660_ap_ready),
    .op_code_val(op_code_reg_2063),
    .funct3_val(funct3_reg_2068),
    .funct7_val(funct7_reg_2073),
    .source1_val(source1_reg_2113),
    .source2_val(source2_reg_2124),
    .imm_I_val(imm_I_reg_2087),
    .imm_U_val(imm_U_reg_2108),
    .old_pc_val(old_pc_reg_2007),
    .g_error(call_ret_execute_arithm_fu_660_g_error),
    .g_error_ap_vld(call_ret_execute_arithm_fu_660_g_error_ap_vld),
    .ap_return_0(call_ret_execute_arithm_fu_660_ap_return_0),
    .ap_return_1(call_ret_execute_arithm_fu_660_ap_return_1)
);

processor_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U10(
    .din0(32'd0),
    .din1(p_ZL6g_xreg_1),
    .din2(p_ZL6g_xreg_2),
    .din3(p_ZL6g_xreg_3),
    .din4(p_ZL6g_xreg_4),
    .din5(p_ZL6g_xreg_5),
    .din6(p_ZL6g_xreg_6),
    .din7(p_ZL6g_xreg_7),
    .din8(p_ZL6g_xreg_8),
    .din9(p_ZL6g_xreg_9),
    .din10(p_ZL6g_xreg_10),
    .din11(p_ZL6g_xreg_11),
    .din12(p_ZL6g_xreg_12),
    .din13(p_ZL6g_xreg_13),
    .din14(p_ZL6g_xreg_14),
    .din15(p_ZL6g_xreg_15),
    .din16(p_ZL6g_xreg_16),
    .din17(p_ZL6g_xreg_17),
    .din18(p_ZL6g_xreg_18),
    .din19(p_ZL6g_xreg_19),
    .din20(p_ZL6g_xreg_20),
    .din21(p_ZL6g_xreg_21),
    .din22(p_ZL6g_xreg_22),
    .din23(p_ZL6g_xreg_23),
    .din24(p_ZL6g_xreg_24),
    .din25(p_ZL6g_xreg_25),
    .din26(p_ZL6g_xreg_26),
    .din27(p_ZL6g_xreg_27),
    .din28(p_ZL6g_xreg_28),
    .din29(p_ZL6g_xreg_29),
    .din30(p_ZL6g_xreg_30),
    .din31(p_ZL6g_xreg_31),
    .din32(source1_fu_1120_p33),
    .dout(source1_fu_1120_p34)
);

processor_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U11(
    .din0(32'd0),
    .din1(p_ZL6g_xreg_1),
    .din2(p_ZL6g_xreg_2),
    .din3(p_ZL6g_xreg_3),
    .din4(p_ZL6g_xreg_4),
    .din5(p_ZL6g_xreg_5),
    .din6(p_ZL6g_xreg_6),
    .din7(p_ZL6g_xreg_7),
    .din8(p_ZL6g_xreg_8),
    .din9(p_ZL6g_xreg_9),
    .din10(p_ZL6g_xreg_10),
    .din11(p_ZL6g_xreg_11),
    .din12(p_ZL6g_xreg_12),
    .din13(p_ZL6g_xreg_13),
    .din14(p_ZL6g_xreg_14),
    .din15(p_ZL6g_xreg_15),
    .din16(p_ZL6g_xreg_16),
    .din17(p_ZL6g_xreg_17),
    .din18(p_ZL6g_xreg_18),
    .din19(p_ZL6g_xreg_19),
    .din20(p_ZL6g_xreg_20),
    .din21(p_ZL6g_xreg_21),
    .din22(p_ZL6g_xreg_22),
    .din23(p_ZL6g_xreg_23),
    .din24(p_ZL6g_xreg_24),
    .din25(p_ZL6g_xreg_25),
    .din26(p_ZL6g_xreg_26),
    .din27(p_ZL6g_xreg_27),
    .din28(p_ZL6g_xreg_28),
    .din29(p_ZL6g_xreg_29),
    .din30(p_ZL6g_xreg_30),
    .din31(p_ZL6g_xreg_31),
    .din32(source2_fu_1190_p33),
    .dout(source2_fu_1190_p34)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        g_pc <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            g_pc <= ap_phi_mux_g_pc_new_9_phi_fu_650_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_786_p4 == 3'd2) & (op_code_fu_782_p1 == 7'd99)) | ((funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99)))) | ((or_ln26_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~(funct3_reg_2068 == 3'd2) & ~(funct3_reg_2068 == 3'd0) & ~(funct3_reg_2068 == 3'd1) & ~(funct3_reg_2068 == 3'd4) & ~(funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | (~(funct3_reg_2068 == 3'd2) & ~(funct3_reg_2068 == 3'd0) & ~(funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state7)) | ((op_code_reg_2063 == 7'd35) & (icmp_ln167_fu_1585_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((op_code_reg_2063 == 7'd3) & (icmp_ln114_fu_1464_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)))) begin
        g_error <= 1'd1;
    end else if ((~(op_code_reg_2063 == 7'd99) & ~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & ~(op_code_reg_2063 == 7'd111) & ~(op_code_reg_2063 == 7'd103) & (call_ret_execute_arithm_fu_660_g_error_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        g_error <= call_ret_execute_arithm_fu_660_g_error;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln71_fu_1296_p3;
    end else if (((funct3_reg_2068 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln76_fu_1290_p3;
    end else if (((funct3_reg_2068 == 3'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln81_fu_1284_p3;
    end else if (((funct3_reg_2068 == 3'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln86_fu_1278_p3;
    end else if (((funct3_reg_2068 == 3'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln91_fu_1272_p3;
    end else if (((funct3_reg_2068 == 3'd7) & (1'b1 == ap_CS_fsm_state4))) begin
        g_pc_new_7_reg_466 <= select_ln96_fu_1266_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_786_p4 == 3'd2) & (op_code_fu_782_p1 == 7'd99)) | ((funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99))))) begin
        g_pc_new_7_reg_466 <= result_1_fu_777_p2;
    end else if (((op_code_reg_2063 == 7'd111) & (1'b1 == ap_CS_fsm_state5))) begin
        g_pc_new_7_reg_466 <= add_ln59_fu_1306_p2;
    end else if (((op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state5))) begin
        g_pc_new_7_reg_466 <= add_ln64_fu_1302_p2;
    end else if ((~(op_code_reg_2063 == 7'd99) & ~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & ~(op_code_reg_2063 == 7'd111) & ~(op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state7))) begin
        g_pc_new_7_reg_466 <= result_1_reg_2023;
    end
end

always @ (posedge ap_clk) begin
    if ((~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        g_pc_new_8_reg_552 <= g_pc_new_7_reg_466;
    end else if (((~(select_ln113_fu_1457_p3 == 3'd1) & ~(select_ln113_fu_1457_p3 == 3'd3) & ~(select_ln113_fu_1457_p3 == 3'd0) & ~(select_ln113_fu_1457_p3 == 3'd2) & (funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | (~(select_ln113_fu_1457_p3 == 3'd1) & ~(select_ln113_fu_1457_p3 == 3'd3) & ~(select_ln113_fu_1457_p3 == 3'd0) & ~(select_ln113_fu_1457_p3 == 3'd2) & (funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | (~(select_ln113_fu_1457_p3 == 3'd0) & ~(select_ln113_fu_1457_p3 == 3'd2) & (funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | (~(select_ln113_fu_1457_p3 == 3'd0) & ~(select_ln113_fu_1457_p3 == 3'd2) & (funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | (~(funct3_reg_2068 == 3'd2) & ~(funct3_reg_2068 == 3'd0) & ~(funct3_reg_2068 == 3'd1) & ~(funct3_reg_2068 == 3'd4) & ~(funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd2) 
    & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) 
    | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)))) begin
        g_pc_new_8_reg_552 <= result_1_reg_2023;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((1'b1 == ap_condition_461)) begin
            p_0_0_0470_reg_596 <= result_15_reg_527;
        end else if ((1'b1 == ap_condition_456)) begin
            p_0_0_0470_reg_596 <= sext_ln120_fu_1709_p1;
        end else if ((1'b1 == ap_condition_452)) begin
            p_0_0_0470_reg_596 <= sext_ln122_fu_1700_p1;
        end else if ((1'b1 == ap_condition_448)) begin
            p_0_0_0470_reg_596 <= sext_ln124_fu_1695_p1;
        end else if ((1'b1 == ap_condition_444)) begin
            p_0_0_0470_reg_596 <= sext_ln126_fu_1690_p1;
        end else if ((1'b1 == ap_condition_440)) begin
            p_0_0_0470_reg_596 <= sext_ln131_fu_1685_p1;
        end else if ((1'b1 == ap_condition_436)) begin
            p_0_0_0470_reg_596 <= sext_ln133_fu_1676_p1;
        end else if ((1'b1 == ap_condition_432)) begin
            p_0_0_0470_reg_596 <= zext_ln141_1_fu_1671_p1;
        end else if ((1'b1 == ap_condition_428)) begin
            p_0_0_0470_reg_596 <= zext_ln143_1_fu_1662_p1;
        end else if ((1'b1 == ap_condition_423)) begin
            p_0_0_0470_reg_596 <= zext_ln145_1_fu_1657_p1;
        end else if ((1'b1 == ap_condition_419)) begin
            p_0_0_0470_reg_596 <= zext_ln147_1_fu_1652_p1;
        end else if ((1'b1 == ap_condition_414)) begin
            p_0_0_0470_reg_596 <= zext_ln152_1_fu_1647_p1;
        end else if ((1'b1 == ap_condition_409)) begin
            p_0_0_0470_reg_596 <= zext_ln154_1_fu_1638_p1;
        end else if (((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd3))) begin
            p_0_0_0470_reg_596 <= memory_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_786_p4 == 3'd2) & (op_code_fu_782_p1 == 7'd99)) | ((funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99))))) begin
        result_15_reg_527 <= result_1_fu_777_p2;
    end else if ((((op_code_reg_2063 == 7'd111) & (1'b1 == ap_CS_fsm_state5)) | ((op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state5)) | ((funct3_reg_2068 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd4) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd5) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd6) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd7) & (1'b1 == ap_CS_fsm_state4)))) begin
        result_15_reg_527 <= result_1_reg_2023;
    end else if ((~(op_code_reg_2063 == 7'd99) & ~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & ~(op_code_reg_2063 == 7'd111) & ~(op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state7))) begin
        result_15_reg_527 <= result_reg_2261;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_786_p4 == 3'd2) & (op_code_fu_782_p1 == 7'd99)) | ((funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99)))) | ((funct3_reg_2068 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd4) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd5) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd6) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2068 == 3'd7) & (1'b1 == ap_CS_fsm_state4)))) begin
        write_back_1_reg_491 <= 1'd0;
    end else if ((((op_code_reg_2063 == 7'd111) & (1'b1 == ap_CS_fsm_state5)) | ((op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state5)))) begin
        write_back_1_reg_491 <= 1'd1;
    end else if ((~(op_code_reg_2063 == 7'd99) & ~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & ~(op_code_reg_2063 == 7'd111) & ~(op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state7))) begin
        write_back_1_reg_491 <= write_back_reg_2266;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        funct3_reg_2068 <= {{memory_q0[14:12]}};
        funct7_reg_2073 <= {{memory_q0[31:25]}};
        imm_I_reg_2087 <= {{memory_q0[31:20]}};
        imm_U_reg_2108[31 : 12] <= imm_U_fu_968_p3[31 : 12];
        op_code_reg_2063 <= op_code_fu_782_p1;
        rd_reg_2078 <= {{memory_q0[11:7]}};
        result_1_reg_2023 <= result_1_fu_777_p2;
        sext_ln40_reg_2082[31 : 1] <= sext_ln40_fu_866_p1[31 : 1];
        sext_ln41_reg_2093 <= sext_ln41_fu_880_p1;
        sext_ln42_reg_2098[31 : 1] <= sext_ln42_fu_926_p1[31 : 1];
        source1_reg_2113 <= source1_fu_1120_p34;
        source2_reg_2124 <= source2_fu_1190_p34;
        tmp_4_reg_2103 <= tmp_4_fu_950_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln71_reg_2164 <= grp_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln76_reg_2159 <= grp_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd4) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln81_reg_2154 <= grp_fu_678_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd5) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln86_reg_2149 <= grp_fu_678_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd6) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln91_reg_2144 <= grp_fu_674_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd7) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln96_reg_2139 <= grp_fu_674_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_3_reg_2375 <= zext_ln173_fu_1627_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_4_reg_2370 <= zext_ln175_fu_1622_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_5_reg_2365 <= zext_ln177_fu_1617_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_6_reg_2360 <= zext_ln179_fu_1612_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_7_reg_2355 <= zext_ln184_fu_1607_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_addr_8_reg_2350 <= zext_ln186_fu_1602_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        old_pc_reg_2007 <= g_pc;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd1) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd1) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_1 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd10) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd10) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_10 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd11) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd11) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_11 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd12) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd12) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_12 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd13) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd13) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_13 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd14) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd14) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_14 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd15) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd15) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_15 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd16) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd16) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_16 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd17) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd17) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_17 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd18) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd18) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_18 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd19) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd19) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_19 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd2) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd2) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_2 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd20) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd20) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_20 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd21) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd21) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_21 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd22) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd22) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_22 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd23) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd23) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_23 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd24) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd24) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_24 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd25) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd25) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_25 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd26) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd26) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_26 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd27) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd27) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_27 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd28) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd28) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_28 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd29) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd29) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_29 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd3) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd3) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_3 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd30) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd30) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_30 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd31) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd31) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_31 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd4) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd4) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_4 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd5) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd5) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_5 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd6) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd6) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_6 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd7) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd7) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_7 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd8) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd8) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_8 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd9) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (rd_reg_2078 == 5'd9) & (op_code_reg_2063 == 7'd3))))) begin
        p_ZL6g_xreg_9 <= ap_phi_mux_p_0_0_0470_phi_fu_600_p38;
    end
end

always @ (posedge ap_clk) begin
    if ((~(op_code_reg_2063 == 7'd99) & ~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & ~(op_code_reg_2063 == 7'd111) & ~(op_code_reg_2063 == 7'd103) & (1'b1 == ap_CS_fsm_state6))) begin
        result_reg_2261 <= call_ret_execute_arithm_fu_660_ap_return_0;
        write_back_reg_2266 <= call_ret_execute_arithm_fu_660_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        select_ln113_reg_2271 <= select_ln113_fu_1457_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state7))) begin
        select_ln166_reg_2343 <= select_ln166_fu_1578_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_11_reg_2209 <= add_ln112_fu_1316_p2[32'd33];
        trunc_ln112_1_reg_2215 <= {{sub_ln112_fu_1330_p2[33:2]}};
        trunc_ln112_2_reg_2220 <= {{add_ln112_fu_1316_p2[33:2]}};
        trunc_ln113_1_reg_2230 <= trunc_ln113_1_fu_1360_p1;
        trunc_ln113_reg_2225 <= trunc_ln113_fu_1356_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_9_reg_2235 <= add_ln165_fu_1370_p2[32'd33];
        trunc_ln165_1_reg_2241 <= {{sub_ln165_fu_1384_p2[33:2]}};
        trunc_ln165_2_reg_2246 <= {{add_ln165_fu_1370_p2[33:2]}};
        trunc_ln166_1_reg_2256 <= trunc_ln166_1_fu_1414_p1;
        trunc_ln166_reg_2251 <= trunc_ln166_fu_1410_p1;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_g_pc_new_8_phi_fu_555_p38 = g_pc_new_7_reg_466;
    end else if ((((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 
    3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_g_pc_new_8_phi_fu_555_p38 = result_1_reg_2023;
    end else begin
        ap_phi_mux_g_pc_new_8_phi_fu_555_p38 = g_pc_new_8_reg_552;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((op_code_reg_2063 == 7'd35)) begin
            ap_phi_mux_g_pc_new_9_phi_fu_650_p6 = result_1_reg_2023;
        end else if ((1'b1 == ap_condition_484)) begin
            ap_phi_mux_g_pc_new_9_phi_fu_650_p6 = g_pc_new_7_reg_466;
        end else if ((1'b1 == ap_condition_481)) begin
            ap_phi_mux_g_pc_new_9_phi_fu_650_p6 = ap_phi_mux_g_pc_new_8_phi_fu_555_p38;
        end else begin
            ap_phi_mux_g_pc_new_9_phi_fu_650_p6 = 'bx;
        end
    end else begin
        ap_phi_mux_g_pc_new_9_phi_fu_650_p6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((1'b1 == ap_condition_461)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = result_15_reg_527;
        end else if ((1'b1 == ap_condition_456)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln120_fu_1709_p1;
        end else if ((1'b1 == ap_condition_452)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln122_fu_1700_p1;
        end else if ((1'b1 == ap_condition_448)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln124_fu_1695_p1;
        end else if ((1'b1 == ap_condition_444)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln126_fu_1690_p1;
        end else if ((1'b1 == ap_condition_440)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln131_fu_1685_p1;
        end else if ((1'b1 == ap_condition_436)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = sext_ln133_fu_1676_p1;
        end else if ((1'b1 == ap_condition_432)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln141_1_fu_1671_p1;
        end else if ((1'b1 == ap_condition_428)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln143_1_fu_1662_p1;
        end else if ((1'b1 == ap_condition_423)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln145_1_fu_1657_p1;
        end else if ((1'b1 == ap_condition_419)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln147_1_fu_1652_p1;
        end else if ((1'b1 == ap_condition_414)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln152_1_fu_1647_p1;
        end else if ((1'b1 == ap_condition_409)) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = zext_ln154_1_fu_1638_p1;
        end else if (((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd3))) begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = memory_q0;
        end else begin
            ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = p_0_0_0470_reg_596;
        end
    end else begin
        ap_phi_mux_p_0_0_0470_phi_fu_600_p38 = p_0_0_0470_reg_596;
    end
end

always @ (*) begin
    if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_3_reg_2375;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_4_reg_2370;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_5_reg_2365;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd3) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_6_reg_2360;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_7_reg_2355;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8))) begin
        memory_address0 = memory_addr_8_reg_2350;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln173_fu_1627_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln175_fu_1622_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln177_fu_1617_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln179_fu_1612_p1;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln184_fu_1607_p1;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln186_fu_1602_p1;
    end else if (((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln190_fu_1597_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln120_fu_1536_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln122_fu_1531_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln124_fu_1526_p1;
    end else if (((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln126_fu_1521_p1;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln131_fu_1516_p1;
    end else if (((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln133_fu_1511_p1;
    end else if (((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln137_fu_1506_p1;
    end else if (((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln141_fu_1501_p1;
    end else if (((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln143_fu_1496_p1;
    end else if (((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln145_fu_1491_p1;
    end else if (((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln147_fu_1486_p1;
    end else if (((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln152_fu_1481_p1;
    end else if (((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        memory_address0 = zext_ln154_fu_1476_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        memory_address0 = zext_ln28_fu_772_p1;
    end else begin
        memory_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | ((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd3) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 
    == 3'd0) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7)) 
    | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_fu_1578_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd1) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd3) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_fu_1457_p3 == 3'd0) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 
    == 7'd3) & (select_ln113_fu_1457_p3 == 3'd2) & (1'b1 == ap_CS_fsm_state7)))) begin
        memory_ce0 = 1'b1;
    end else begin
        memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((op_code_reg_2063 == 7'd35)) begin
        if ((1'b1 == ap_condition_1537)) begin
            memory_d0 = tmp_13_fu_1797_p5;
        end else if ((1'b1 == ap_condition_1533)) begin
            memory_d0 = tmp_14_fu_1781_p5;
        end else if ((1'b1 == ap_condition_1529)) begin
            memory_d0 = tmp_15_fu_1765_p5;
        end else if ((1'b1 == ap_condition_1525)) begin
            memory_d0 = tmp_16_fu_1749_p5;
        end else if ((1'b1 == ap_condition_1521)) begin
            memory_d0 = tmp_17_fu_1733_p5;
        end else if ((1'b1 == ap_condition_1517)) begin
            memory_d0 = tmp_18_fu_1717_p5;
        end else if (((funct3_reg_2068 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
            memory_d0 = source2_reg_2124;
        end else begin
            memory_d0 = 'bx;
        end
    end else begin
        memory_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((funct3_reg_2068 == 3'd2) & (op_code_reg_2063 == 7'd35) & (1'b1 == ap_CS_fsm_state7)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd35) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8)))) begin
        memory_we0 = 1'b1;
    end else begin
        memory_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_786_p4 == 3'd2) & (op_code_fu_782_p1 == 7'd99)) | ((funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~(funct3_fu_786_p4 == 3'd2) & ~(funct3_fu_786_p4 == 3'd3) & (op_code_fu_782_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~(op_code_fu_782_p1 == 7'd99) & ~(op_code_fu_782_p1 == 7'd111) & ~(op_code_fu_782_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln112_fu_1316_p2 = ($signed(zext_ln112_fu_1310_p1) + $signed(sext_ln112_fu_1313_p1));

assign add_ln165_fu_1370_p2 = ($signed(zext_ln165_fu_1364_p1) + $signed(sext_ln165_fu_1367_p1));

assign add_ln59_fu_1306_p2 = ($signed(old_pc_reg_2007) + $signed(sext_ln42_reg_2098));

assign add_ln64_fu_1302_p2 = ($signed(source1_reg_2113) + $signed(sext_ln41_reg_2093));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_condition_1517 = ((funct3_reg_2068 == 3'd1) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_1521 = ((funct3_reg_2068 == 3'd1) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_1525 = ((funct3_reg_2068 == 3'd0) & (select_ln166_reg_2343 == 3'd3) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_1529 = ((funct3_reg_2068 == 3'd0) & (select_ln166_reg_2343 == 3'd2) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_1533 = ((funct3_reg_2068 == 3'd0) & (select_ln166_reg_2343 == 3'd1) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_1537 = ((funct3_reg_2068 == 3'd0) & (select_ln166_reg_2343 == 3'd0) & (1'b1 == ap_CS_fsm_state8));
end

always @ (*) begin
    ap_condition_409 = ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2));
end

always @ (*) begin
    ap_condition_414 = ((funct3_reg_2068 == 3'd5) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0));
end

always @ (*) begin
    ap_condition_419 = ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd3));
end

always @ (*) begin
    ap_condition_423 = ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2));
end

always @ (*) begin
    ap_condition_428 = ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1));
end

always @ (*) begin
    ap_condition_432 = ((funct3_reg_2068 == 3'd4) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0));
end

always @ (*) begin
    ap_condition_436 = ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2));
end

always @ (*) begin
    ap_condition_440 = ((funct3_reg_2068 == 3'd1) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0));
end

always @ (*) begin
    ap_condition_444 = ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd3));
end

always @ (*) begin
    ap_condition_448 = ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd2));
end

always @ (*) begin
    ap_condition_452 = ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd1));
end

always @ (*) begin
    ap_condition_456 = ((funct3_reg_2068 == 3'd0) & (op_code_reg_2063 == 7'd3) & (select_ln113_reg_2271 == 3'd0));
end

always @ (*) begin
    ap_condition_461 = (~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1));
end

always @ (*) begin
    ap_condition_481 = ((~(op_code_reg_2063 == 7'd35) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd1)) | (~(op_code_reg_2063 == 7'd35) & (op_code_reg_2063 == 7'd3)));
end

always @ (*) begin
    ap_condition_484 = (~(op_code_reg_2063 == 7'd35) & ~(op_code_reg_2063 == 7'd3) & (ap_phi_mux_write_back_1_phi_fu_496_p20 == 1'd0));
end

assign ap_phi_mux_write_back_1_phi_fu_496_p20 = write_back_1_reg_491;

assign funct3_fu_786_p4 = {{memory_q0[14:12]}};

assign grp_fu_674_p2 = ((source1_reg_2113 < source2_reg_2124) ? 1'b1 : 1'b0);

assign grp_fu_678_p2 = (($signed(source1_reg_2113) < $signed(source2_reg_2124)) ? 1'b1 : 1'b0);

assign grp_fu_682_p2 = ((source1_reg_2113 == source2_reg_2124) ? 1'b1 : 1'b0);

assign grp_fu_686_p2 = ($signed(old_pc_reg_2007) + $signed(sext_ln40_reg_2082));

assign grp_fu_690_p4 = {{memory_q0[31:16]}};

assign grp_fu_700_p4 = {{memory_q0[31:24]}};

assign grp_fu_710_p4 = {{memory_q0[23:16]}};

assign grp_fu_720_p4 = {{memory_q0[15:8]}};

assign icmp_ln114_fu_1464_p2 = ((pos_1_fu_1431_p3 > 32'd102399) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_1585_p2 = ((pos_fu_1552_p3 > 32'd102399) ? 1'b1 : 1'b0);

assign icmp_ln26_1_fu_754_p2 = ((g_pc > 32'd409599) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_738_p2 = ((trunc_ln26_fu_734_p1 != 2'd0) ? 1'b1 : 1'b0);

assign imm_B_fu_852_p6 = {{{{{tmp_1_fu_844_p3}, {tmp_fu_836_p3}}, {tmp_s_fu_826_p4}}, {tmp7_fu_816_p4}}, {1'd0}};

assign imm_I_fu_870_p4 = {{memory_q0[31:20]}};

assign imm_J_fu_912_p6 = {{{{{tmp_1_fu_844_p3}, {tmp_5_fu_902_p4}}, {tmp_3_fu_894_p3}}, {tmp_2_fu_884_p4}}, {1'd0}};

assign imm_U_fu_968_p3 = {{tmp_8_fu_958_p4}, {12'd0}};

assign lshr_ln_fu_744_p4 = {{g_pc[18:2]}};

assign o_error = g_error;

assign op_code_fu_782_p1 = memory_q0[6:0];

assign or_ln26_fu_760_p2 = (icmp_ln26_fu_738_p2 | icmp_ln26_1_fu_754_p2);

assign p_and_t3_fu_1558_p3 = {{1'd0}, {trunc_ln166_1_reg_2256}};

assign p_and_t_fu_1437_p3 = {{1'd0}, {trunc_ln113_1_reg_2230}};

assign pos_1_fu_1431_p3 = ((tmp_11_reg_2209[0:0] == 1'b1) ? sub_ln112_1_fu_1426_p2 : trunc_ln112_2_reg_2220);

assign pos_fu_1552_p3 = ((tmp_9_reg_2235[0:0] == 1'b1) ? sub_ln165_1_fu_1547_p2 : trunc_ln165_2_reg_2246);

assign result_13_fu_1643_p1 = memory_q0[15:0];

assign result_1_fu_777_p2 = (old_pc_reg_2007 + 32'd4);

assign result_3_fu_1705_p1 = memory_q0[7:0];

assign result_7_fu_1681_p1 = memory_q0[15:0];

assign result_9_fu_1667_p1 = memory_q0[7:0];

assign select_ln113_fu_1457_p3 = ((tmp_11_reg_2209[0:0] == 1'b1) ? sub_ln113_fu_1444_p2 : tmp_12_fu_1450_p3);

assign select_ln166_fu_1578_p3 = ((tmp_9_reg_2235[0:0] == 1'b1) ? sub_ln166_fu_1565_p2 : tmp_10_fu_1571_p3);

assign select_ln71_fu_1296_p3 = ((icmp_ln71_reg_2164[0:0] == 1'b1) ? grp_fu_686_p2 : result_1_reg_2023);

assign select_ln76_fu_1290_p3 = ((icmp_ln76_reg_2159[0:0] == 1'b1) ? result_1_reg_2023 : grp_fu_686_p2);

assign select_ln81_fu_1284_p3 = ((icmp_ln81_reg_2154[0:0] == 1'b1) ? grp_fu_686_p2 : result_1_reg_2023);

assign select_ln86_fu_1278_p3 = ((icmp_ln86_reg_2149[0:0] == 1'b1) ? result_1_reg_2023 : grp_fu_686_p2);

assign select_ln91_fu_1272_p3 = ((icmp_ln91_reg_2144[0:0] == 1'b1) ? grp_fu_686_p2 : result_1_reg_2023);

assign select_ln96_fu_1266_p3 = ((icmp_ln96_reg_2139[0:0] == 1'b1) ? result_1_reg_2023 : grp_fu_686_p2);

assign sext_ln112_fu_1313_p1 = $signed(imm_I_reg_2087);

assign sext_ln120_fu_1709_p1 = $signed(result_3_fu_1705_p1);

assign sext_ln122_fu_1700_p1 = $signed(grp_fu_720_p4);

assign sext_ln124_fu_1695_p1 = $signed(grp_fu_710_p4);

assign sext_ln126_fu_1690_p1 = $signed(grp_fu_700_p4);

assign sext_ln131_fu_1685_p1 = $signed(result_7_fu_1681_p1);

assign sext_ln133_fu_1676_p1 = $signed(grp_fu_690_p4);

assign sext_ln165_fu_1367_p1 = $signed(tmp_4_reg_2103);

assign sext_ln40_fu_866_p1 = $signed(imm_B_fu_852_p6);

assign sext_ln41_fu_880_p1 = imm_I_fu_870_p4;

assign sext_ln42_fu_926_p1 = $signed(imm_J_fu_912_p6);

assign source1_fu_1120_p33 = {{memory_q0[19:15]}};

assign source2_fu_1190_p33 = {{memory_q0[24:20]}};

assign sub_ln112_1_fu_1426_p2 = (32'd0 - trunc_ln112_1_reg_2215);

assign sub_ln112_fu_1330_p2 = (34'd0 - add_ln112_fu_1316_p2);

assign sub_ln113_fu_1444_p2 = (3'd0 - p_and_t_fu_1437_p3);

assign sub_ln165_1_fu_1547_p2 = (32'd0 - trunc_ln165_1_reg_2241);

assign sub_ln165_fu_1384_p2 = (34'd0 - add_ln165_fu_1370_p2);

assign sub_ln166_fu_1565_p2 = (3'd0 - p_and_t3_fu_1558_p3);

assign tmp7_fu_816_p4 = {{memory_q0[11:8]}};

assign tmp_10_fu_1571_p3 = {{1'd0}, {trunc_ln166_reg_2251}};

assign tmp_12_fu_1450_p3 = {{1'd0}, {trunc_ln113_reg_2225}};

assign tmp_13_fu_1797_p5 = {{memory_q0[31:8]}, {trunc_ln173_fu_1794_p1}};

assign tmp_14_fu_1781_p5 = {{memory_q0[31:16]}, {trunc_ln175_fu_1778_p1}, {memory_q0[7:0]}};

assign tmp_15_fu_1765_p5 = {{memory_q0[31:24]}, {trunc_ln177_fu_1762_p1}, {memory_q0[15:0]}};

assign tmp_16_fu_1749_p5 = {{trunc_ln179_fu_1746_p1}, {memory_q0[23:0]}};

assign tmp_17_fu_1733_p5 = {{memory_q0[31:16]}, {trunc_ln184_fu_1730_p1}};

assign tmp_18_fu_1717_p5 = {{trunc_ln186_fu_1714_p1}, {memory_q0[15:0]}};

assign tmp_1_fu_844_p3 = memory_q0[32'd31];

assign tmp_2_fu_884_p4 = {{memory_q0[30:21]}};

assign tmp_3_fu_894_p3 = memory_q0[32'd20];

assign tmp_4_fu_950_p3 = {{tmp_7_fu_940_p4}, {tmp_6_fu_930_p4}};

assign tmp_5_fu_902_p4 = {{memory_q0[19:12]}};

assign tmp_6_fu_930_p4 = {{memory_q0[11:7]}};

assign tmp_7_fu_940_p4 = {{memory_q0[31:25]}};

assign tmp_8_fu_958_p4 = {{memory_q0[31:12]}};

assign tmp_fu_836_p3 = memory_q0[32'd7];

assign tmp_s_fu_826_p4 = {{memory_q0[30:25]}};

assign trunc_ln113_1_fu_1360_p1 = sub_ln112_fu_1330_p2[1:0];

assign trunc_ln113_fu_1356_p1 = add_ln112_fu_1316_p2[1:0];

assign trunc_ln166_1_fu_1414_p1 = sub_ln165_fu_1384_p2[1:0];

assign trunc_ln166_fu_1410_p1 = add_ln165_fu_1370_p2[1:0];

assign trunc_ln173_fu_1794_p1 = source2_reg_2124[7:0];

assign trunc_ln175_fu_1778_p1 = source2_reg_2124[7:0];

assign trunc_ln177_fu_1762_p1 = source2_reg_2124[7:0];

assign trunc_ln179_fu_1746_p1 = source2_reg_2124[7:0];

assign trunc_ln184_fu_1730_p1 = source2_reg_2124[15:0];

assign trunc_ln186_fu_1714_p1 = source2_reg_2124[15:0];

assign trunc_ln26_fu_734_p1 = g_pc[1:0];

assign zext_ln112_fu_1310_p1 = source1_reg_2113;

assign zext_ln120_fu_1536_p1 = pos_1_fu_1431_p3;

assign zext_ln122_fu_1531_p1 = pos_1_fu_1431_p3;

assign zext_ln124_fu_1526_p1 = pos_1_fu_1431_p3;

assign zext_ln126_fu_1521_p1 = pos_1_fu_1431_p3;

assign zext_ln131_fu_1516_p1 = pos_1_fu_1431_p3;

assign zext_ln133_fu_1511_p1 = pos_1_fu_1431_p3;

assign zext_ln137_fu_1506_p1 = pos_1_fu_1431_p3;

assign zext_ln141_1_fu_1671_p1 = result_9_fu_1667_p1;

assign zext_ln141_fu_1501_p1 = pos_1_fu_1431_p3;

assign zext_ln143_1_fu_1662_p1 = grp_fu_720_p4;

assign zext_ln143_fu_1496_p1 = pos_1_fu_1431_p3;

assign zext_ln145_1_fu_1657_p1 = grp_fu_710_p4;

assign zext_ln145_fu_1491_p1 = pos_1_fu_1431_p3;

assign zext_ln147_1_fu_1652_p1 = grp_fu_700_p4;

assign zext_ln147_fu_1486_p1 = pos_1_fu_1431_p3;

assign zext_ln152_1_fu_1647_p1 = result_13_fu_1643_p1;

assign zext_ln152_fu_1481_p1 = pos_1_fu_1431_p3;

assign zext_ln154_1_fu_1638_p1 = grp_fu_690_p4;

assign zext_ln154_fu_1476_p1 = pos_1_fu_1431_p3;

assign zext_ln165_fu_1364_p1 = source1_reg_2113;

assign zext_ln173_fu_1627_p1 = pos_fu_1552_p3;

assign zext_ln175_fu_1622_p1 = pos_fu_1552_p3;

assign zext_ln177_fu_1617_p1 = pos_fu_1552_p3;

assign zext_ln179_fu_1612_p1 = pos_fu_1552_p3;

assign zext_ln184_fu_1607_p1 = pos_fu_1552_p3;

assign zext_ln186_fu_1602_p1 = pos_fu_1552_p3;

assign zext_ln190_fu_1597_p1 = pos_fu_1552_p3;

assign zext_ln28_fu_772_p1 = lshr_ln_fu_744_p4;

always @ (posedge ap_clk) begin
    sext_ln40_reg_2082[0] <= 1'b0;
    sext_ln42_reg_2098[0] <= 1'b0;
    imm_U_reg_2108[11:0] <= 12'b000000000000;
end

endmodule //processor
