// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processor_processor,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.384000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=325,HLS_SYN_LUT=3335,HLS_VERSION=2023_1_1}" *)

module processor (
        ap_clk,
        ap_rst,
        instr_memory_address0,
        instr_memory_ce0,
        instr_memory_q0,
        data_memory_address0,
        data_memory_ce0,
        data_memory_we0,
        data_memory_d0,
        data_memory_q0,
        error
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
output  [15:0] instr_memory_address0;
output   instr_memory_ce0;
input  [31:0] instr_memory_q0;
output  [15:0] data_memory_address0;
output   data_memory_ce0;
output   data_memory_we0;
output  [31:0] data_memory_d0;
input  [31:0] data_memory_q0;
output  [0:0] error;

reg instr_memory_ce0;
reg[15:0] data_memory_address0;
reg data_memory_ce0;
reg data_memory_we0;
reg[31:0] data_memory_d0;

reg   [31:0] p_pc;
reg   [0:0] p_error;
reg   [4:0] xreg_address0;
reg    xreg_ce0;
reg    xreg_we0;
reg   [31:0] xreg_d0;
wire   [31:0] xreg_q0;
reg   [4:0] xreg_address1;
reg    xreg_ce1;
reg    xreg_we1;
reg   [31:0] xreg_d1;
wire   [31:0] xreg_q1;
reg   [31:0] p_pc_load_reg_2451;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] o_pcode_fu_1223_p1;
reg   [6:0] o_pcode_reg_2464;
wire    ap_CS_fsm_state2;
wire   [2:0] funct3_fu_1227_p4;
reg   [2:0] funct3_reg_2468;
wire  signed [31:0] sext_ln38_fu_1257_p1;
reg  signed [31:0] sext_ln38_reg_2475;
wire  signed [17:0] sext_ln38_1_fu_1261_p1;
reg  signed [17:0] sext_ln38_1_reg_2485;
wire   [4:0] rs1_fu_1265_p4;
reg   [4:0] rs1_reg_2490;
wire   [4:0] rs2_fu_1275_p4;
reg   [4:0] rs2_reg_2495;
wire   [4:0] rd_fu_1285_p4;
reg   [4:0] rd_reg_2505;
wire  signed [31:0] sext_ln42_fu_1345_p1;
reg  signed [31:0] sext_ln42_reg_2533;
wire  signed [31:0] imm_S_fu_1395_p5;
reg  signed [31:0] imm_S_reg_2538;
reg   [1:0] imm_S_cast_reg_2545;
wire   [0:0] icmp_ln336_fu_1446_p2;
reg   [0:0] icmp_ln336_reg_2556;
wire   [0:0] icmp_ln210_fu_1440_p2;
wire   [6:0] funct7_fu_1237_p4;
reg   [1:0] trunc_ln114_1_reg_2717;
wire   [0:0] or_ln336_fu_1714_p2;
wire    ap_CS_fsm_state4;
wire   [2:0] select_ln154_fu_2077_p3;
reg   [2:0] select_ln154_reg_2787;
wire    ap_CS_fsm_state19;
reg   [15:0] data_memory_addr_1_reg_2792;
wire   [1:0] add_ln114_1_fu_2098_p2;
reg   [1:0] add_ln114_1_reg_2797;
wire  signed [31:0] sext_ln154_fu_2125_p1;
reg  signed [31:0] sext_ln154_reg_2810;
wire    ap_CS_fsm_state20;
wire   [0:0] xor_ln116_fu_2155_p2;
wire   [0:0] or_ln116_fu_2165_p2;
wire   [0:0] grp_fu_1168_p2;
reg   [0:0] icmp_ln102_reg_2854;
wire    ap_CS_fsm_state22;
reg   [0:0] icmp_ln96_reg_2858;
wire   [0:0] grp_fu_1174_p2;
reg   [0:0] icmp_ln90_reg_2862;
reg   [0:0] icmp_ln84_reg_2866;
wire   [0:0] grp_fu_1198_p2;
reg   [0:0] icmp_ln78_reg_2870;
reg   [0:0] icmp_ln72_reg_2874;
wire    ap_CS_fsm_state23;
reg   [0:0] p_error_flag_1_reg_829;
wire   [0:0] grp_fu_1186_p3;
reg   [0:0] p_error_loc_1_reg_841;
wire   [31:0] zext_ln158_fu_2133_p1;
reg   [31:0] p_0_03225_reg_852;
reg   [0:0] ap_phi_mux_p_error_flag_17_phi_fu_868_p100;
reg   [0:0] p_error_flag_17_reg_863;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [0:0] ap_phi_mux_p_error_loc_17_phi_fu_1018_p100;
reg   [0:0] p_error_loc_17_reg_1014;
reg   [0:0] ap_phi_mux_p_error_loc_18_phi_fu_1140_p18;
reg   [0:0] p_error_loc_18_reg_1137;
wire    ap_CS_fsm_state24;
wire   [63:0] zext_ln33_fu_1218_p1;
wire   [63:0] zext_ln311_fu_1452_p1;
wire   [63:0] zext_ln311_1_fu_1457_p1;
wire   [63:0] zext_ln301_fu_1462_p1;
wire   [63:0] zext_ln301_1_fu_1467_p1;
wire   [63:0] zext_ln298_1_fu_1477_p1;
wire   [63:0] zext_ln298_fu_1472_p1;
wire   [63:0] zext_ln289_fu_1482_p1;
wire   [63:0] zext_ln289_1_fu_1487_p1;
wire   [63:0] zext_ln277_fu_1492_p1;
wire   [63:0] zext_ln277_1_fu_1497_p1;
wire   [63:0] zext_ln265_fu_1502_p1;
wire   [63:0] zext_ln265_1_fu_1507_p1;
wire   [63:0] zext_ln257_1_fu_1517_p1;
wire   [63:0] zext_ln257_fu_1512_p1;
wire   [63:0] zext_ln247_fu_1522_p1;
wire   [63:0] zext_ln247_1_fu_1527_p1;
wire   [63:0] zext_ln243_fu_1532_p1;
wire   [63:0] zext_ln243_1_fu_1537_p1;
wire   [63:0] zext_ln319_fu_1542_p1;
wire   [63:0] zext_ln319_1_fu_1547_p1;
wire   [63:0] zext_ln211_fu_1552_p1;
wire   [63:0] zext_ln207_fu_1557_p1;
wire   [63:0] zext_ln204_fu_1562_p1;
wire   [63:0] zext_ln201_fu_1567_p1;
wire   [63:0] zext_ln194_fu_1572_p1;
wire   [63:0] zext_ln187_fu_1577_p1;
wire   [63:0] zext_ln184_fu_1582_p1;
wire   [63:0] zext_ln223_fu_1587_p1;
wire   [63:0] zext_ln220_fu_1592_p1;
wire   [63:0] zext_ln152_fu_1597_p1;
wire   [63:0] zext_ln114_fu_1602_p1;
wire   [63:0] zext_ln102_fu_1617_p1;
wire   [63:0] zext_ln102_1_fu_1622_p1;
wire   [63:0] zext_ln96_fu_1627_p1;
wire   [63:0] zext_ln96_1_fu_1632_p1;
wire   [63:0] zext_ln90_fu_1637_p1;
wire   [63:0] zext_ln90_1_fu_1642_p1;
wire   [63:0] zext_ln84_fu_1647_p1;
wire   [63:0] zext_ln84_1_fu_1652_p1;
wire   [63:0] zext_ln78_fu_1657_p1;
wire   [63:0] zext_ln78_1_fu_1662_p1;
wire   [63:0] zext_ln72_fu_1667_p1;
wire   [63:0] zext_ln72_1_fu_1672_p1;
wire   [63:0] zext_ln65_fu_1677_p1;
wire   [63:0] zext_ln60_fu_1682_p1;
wire   [63:0] zext_ln57_fu_1704_p1;
wire   [63:0] zext_ln54_fu_1709_p1;
wire   [63:0] zext_ln311_2_fu_1725_p1;
wire   [63:0] zext_ln301_2_fu_1744_p1;
wire   [63:0] zext_ln298_2_fu_1763_p1;
wire   [63:0] zext_ln289_2_fu_1774_p1;
wire   [63:0] zext_ln278_fu_1778_p1;
wire   [63:0] zext_ln266_fu_1787_p1;
wire   [63:0] zext_ln257_2_fu_1811_p1;
wire   [63:0] zext_ln247_2_fu_1822_p1;
wire   [63:0] zext_ln243_2_fu_1833_p1;
wire   [63:0] zext_ln319_2_fu_1844_p1;
wire   [63:0] zext_ln211_2_fu_1858_p1;
wire   [63:0] zext_ln207_1_fu_1868_p1;
wire   [63:0] zext_ln204_1_fu_1878_p1;
wire   [63:0] zext_ln201_1_fu_1888_p1;
wire   [63:0] zext_ln195_fu_1897_p1;
wire   [63:0] zext_ln188_fu_1911_p1;
wire   [63:0] zext_ln184_1_fu_1920_p1;
wire   [63:0] zext_ln223_2_fu_1934_p1;
wire   [63:0] zext_ln220_2_fu_1948_p1;
wire   [63:0] zext_ln153_fu_2044_p1;
wire   [63:0] zext_ln115_fu_2113_p1;
wire   [63:0] zext_ln172_fu_2139_p1;
wire   [63:0] zext_ln168_fu_2143_p1;
wire   [63:0] zext_ln163_fu_2147_p1;
wire   [63:0] zext_ln142_1_fu_2205_p1;
wire   [63:0] zext_ln137_1_fu_2235_p1;
wire   [63:0] zext_ln133_fu_2239_p1;
wire   [63:0] zext_ln129_fu_2269_p1;
wire   [63:0] zext_ln124_fu_2299_p1;
wire   [63:0] zext_ln66_fu_2441_p1;
wire   [31:0] grp_fu_1180_p2;
wire   [31:0] grp_fu_1194_p2;
wire   [31:0] grp_fu_1162_p2;
wire   [31:0] add_ln61_fu_1687_p2;
wire   [31:0] add_ln57_fu_1698_p2;
wire   [31:0] imm_U_fu_1427_p3;
wire   [31:0] or_ln311_fu_1718_p2;
wire   [31:0] ashr_ln301_fu_1737_p2;
wire   [31:0] lshr_ln298_fu_1756_p2;
wire   [31:0] xor_ln289_fu_1767_p2;
wire   [31:0] zext_ln277_2_fu_1782_p1;
wire   [31:0] zext_ln265_2_fu_1791_p1;
wire   [31:0] shl_ln257_fu_1804_p2;
wire   [31:0] sub_ln247_fu_1815_p2;
wire   [31:0] add_ln243_fu_1826_p2;
wire   [31:0] and_ln319_fu_1837_p2;
wire   [31:0] shl_ln211_fu_1851_p2;
wire   [31:0] and_ln207_fu_1862_p2;
wire   [31:0] or_ln204_fu_1872_p2;
wire   [31:0] xor_ln201_fu_1882_p2;
wire   [31:0] zext_ln194_1_fu_1901_p1;
wire   [31:0] zext_ln187_1_fu_1915_p1;
wire   [31:0] ashr_ln223_fu_1927_p2;
wire   [31:0] lshr_ln220_fu_1941_p2;
wire   [31:0] zext_ln142_fu_2200_p1;
wire   [31:0] zext_ln137_fu_2230_p1;
wire   [31:0] temp_2_fu_2170_p3;
wire  signed [31:0] sext_ln129_fu_2264_p1;
wire  signed [31:0] sext_ln124_fu_2294_p1;
wire   [31:0] or_ln168_fu_2341_p2;
wire   [31:0] or_ln163_fu_2386_p2;
wire   [15:0] lshr_ln_fu_1208_p4;
wire  signed [11:0] funct12_fu_1247_p4;
wire   [0:0] tmp_3_fu_1323_p3;
wire   [0:0] tmp_2_fu_1315_p3;
wire   [5:0] tmp_1_fu_1305_p4;
wire   [3:0] tmp_fu_1295_p4;
wire   [12:0] imm_B_fu_1331_p6;
wire   [7:0] tmp_6_fu_1367_p4;
wire   [0:0] tmp_5_fu_1359_p3;
wire   [9:0] tmp_4_fu_1349_p4;
wire   [20:0] imm_J_fu_1377_p6;
wire   [19:0] tmp_8_fu_1417_p4;
wire  signed [31:0] sext_ln45_fu_1391_p1;
wire   [4:0] trunc_ln301_fu_1729_p1;
wire   [31:0] zext_ln301_3_fu_1733_p1;
wire   [4:0] trunc_ln298_fu_1748_p1;
wire   [31:0] zext_ln298_3_fu_1752_p1;
wire   [4:0] trunc_ln257_fu_1796_p1;
wire   [31:0] zext_ln257_3_fu_1800_p1;
wire   [31:0] zext_ln211_1_fu_1848_p1;
wire   [0:0] icmp_ln194_fu_1892_p2;
wire   [0:0] icmp_ln187_fu_1906_p2;
wire   [31:0] zext_ln223_1_fu_1924_p1;
wire   [31:0] zext_ln220_1_fu_1938_p1;
wire   [1:0] trunc_ln152_fu_1952_p1;
wire   [33:0] zext_ln152_1_fu_1956_p1;
wire  signed [33:0] sext_ln152_fu_1960_p1;
wire   [31:0] add_ln152_3_fu_1975_p2;
wire   [17:0] trunc_ln152_4_fu_1966_p1;
wire   [17:0] trunc_ln152_3_fu_1963_p1;
wire   [33:0] add_ln152_fu_1980_p2;
wire   [17:0] add_ln152_1_fu_1990_p2;
wire   [17:0] sub_ln152_fu_2004_p2;
wire   [15:0] trunc_ln152_1_fu_2010_p4;
wire   [0:0] tmp_9_fu_1996_p3;
wire   [15:0] sub_ln152_1_fu_2020_p2;
wire   [15:0] trunc_ln152_2_fu_2026_p4;
wire   [15:0] pos_1_fu_2036_p3;
wire   [1:0] trunc_ln152_5_fu_1986_p1;
wire   [1:0] sub_ln154_fu_2049_p2;
wire   [2:0] p_and_t_fu_2055_p3;
wire   [1:0] add_ln152_2_fu_1970_p2;
wire   [2:0] sub_ln154_1_fu_2063_p2;
wire   [2:0] tmp_s_fu_2069_p3;
wire   [17:0] trunc_ln114_fu_2085_p1;
wire   [1:0] trunc_ln114_2_fu_2089_p1;
wire   [17:0] pos_fu_2093_p2;
wire   [15:0] lshr_ln1_fu_2103_p4;
wire   [5:0] offset_fu_2118_p3;
wire   [27:0] trunc_ln155_fu_2129_p1;
wire   [27:0] temp_1_fu_2151_p1;
wire   [31:0] zext_ln115_1_fu_2161_p1;
wire   [4:0] shl_ln3_fu_2179_p3;
wire   [31:0] zext_ln141_fu_2186_p1;
wire   [31:0] lshr_ln141_fu_2190_p2;
wire   [15:0] result_3_fu_2196_p1;
wire   [4:0] shl_ln2_fu_2209_p3;
wire   [31:0] zext_ln136_fu_2216_p1;
wire   [31:0] lshr_ln136_fu_2220_p2;
wire   [7:0] result_2_fu_2226_p1;
wire   [4:0] shl_ln1_fu_2243_p3;
wire   [31:0] zext_ln128_fu_2250_p1;
wire   [31:0] lshr_ln128_fu_2254_p2;
wire   [15:0] result_1_fu_2260_p1;
wire   [4:0] shl_ln_fu_2273_p3;
wire   [31:0] zext_ln123_fu_2280_p1;
wire   [31:0] lshr_ln123_fu_2284_p2;
wire   [7:0] result_fu_2290_p1;
wire   [31:0] mask_1_fu_2303_p2;
wire   [31:0] xor_ln168_fu_2308_p2;
wire   [15:0] trunc_ln168_fu_2320_p1;
wire   [32:0] zext_ln168_1_fu_2324_p1;
wire   [32:0] zext_ln168_2_fu_2328_p1;
wire   [32:0] shl_ln168_fu_2331_p2;
wire   [31:0] trunc_ln168_1_fu_2337_p1;
wire   [31:0] and_ln168_fu_2314_p2;
wire   [31:0] mask_fu_2348_p2;
wire   [31:0] xor_ln163_fu_2353_p2;
wire   [7:0] trunc_ln163_fu_2365_p1;
wire   [32:0] zext_ln163_1_fu_2369_p1;
wire   [32:0] zext_ln163_2_fu_2373_p1;
wire   [32:0] shl_ln163_fu_2376_p2;
wire   [31:0] trunc_ln163_1_fu_2382_p1;
wire   [31:0] and_ln163_fu_2359_p2;
reg   [23:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 p_pc = 32'd0;
#0 p_error = 1'd0;
#0 ap_CS_fsm = 24'd1;
end

processor_xreg_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xreg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(xreg_address0),
    .ce0(xreg_ce0),
    .we0(xreg_we0),
    .d0(xreg_d0),
    .q0(xreg_q0),
    .address1(xreg_address1),
    .ce1(xreg_ce1),
    .we1(xreg_we1),
    .d1(xreg_d1),
    .q1(xreg_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_pc <= 32'd0;
    end else begin
        if (((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2))) begin
            p_pc <= add_ln61_fu_1687_p2;
        end else if (((1'b1 == ap_CS_fsm_state21) & ((((((((((funct3_reg_2468 == 3'd6) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln96_reg_2858 == 1'd0)) | ((funct3_reg_2468 == 3'd7) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln102_reg_2854 == 1'd1))) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln90_reg_2862 == 1'd1))) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln84_reg_2866 == 1'd0))) | ((funct3_reg_2468 == 3'd3) & (o_pcode_reg_2464 == 7'd99))) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd99))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd6) & ~(funct3_reg_2468 == 3'd7) & ~(funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln72_reg_2874 == 1'd0))) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln78_reg_2870 == 1'd1))) | (~(o_pcode_reg_2464 == 7'd103) & ~(o_pcode_reg_2464 == 7'd111) & ~(o_pcode_reg_2464 == 7'd99))))) begin
            p_pc <= grp_fu_1162_p2;
        end else if ((((funct3_reg_2468 == 3'd4) & (grp_fu_1174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd5) & (grp_fu_1174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd6) & (grp_fu_1168_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd7) & (grp_fu_1168_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd0) & (grp_fu_1198_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd1) & (grp_fu_1198_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)))) begin
            p_pc <= grp_fu_1194_p2;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            p_pc <= grp_fu_1180_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        if ((grp_fu_1186_p3 == 1'd0)) begin
            p_0_03225_reg_852 <= data_memory_q0;
        end else if ((grp_fu_1186_p3 == 1'd1)) begin
            p_0_03225_reg_852 <= zext_ln158_fu_2133_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)))) begin
        p_error_flag_17_reg_863 <= xor_ln116_fu_2155_p2;
    end else if ((((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)))) begin
        p_error_flag_17_reg_863 <= p_error_flag_1_reg_829;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd99)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd99)))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd0) & ~(funct3_reg_2468 == 3'd1) & ~(funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | (~(funct3_reg_2468 == 3'd0) & ~(funct3_reg_2468 == 3'd1) & ~(funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 
    == 7'd111) & ~(o_pcode_fu_1223_p1 == 7'd55) & ~(o_pcode_fu_1223_p1 == 7'd23) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(o_pcode_fu_1223_p1 == 7'd51) & ~(o_pcode_fu_1223_p1 == 7'd115) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) 
    & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)))) begin
        p_error_flag_17_reg_863 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14) | ((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16)) | ((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (grp_fu_1174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd5) & (grp_fu_1174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd6) & (grp_fu_1168_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 
    == 3'd7) & (grp_fu_1168_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (grp_fu_1198_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd1) & (grp_fu_1198_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16)))) begin
        p_error_flag_17_reg_863 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_error_flag_17_reg_863 <= icmp_ln336_reg_2556;
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        if ((grp_fu_1186_p3 == 1'd0)) begin
            p_error_flag_1_reg_829 <= 1'd1;
        end else if ((grp_fu_1186_p3 == 1'd1)) begin
            p_error_flag_1_reg_829 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)))) begin
        p_error_loc_17_reg_1014 <= or_ln116_fu_2165_p2;
    end else if ((((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)))) begin
        p_error_loc_17_reg_1014 <= p_error_loc_1_reg_841;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd99)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd99)))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd0) & ~(funct3_reg_2468 == 3'd1) & ~(funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | (~(funct3_reg_2468 == 3'd0) & ~(funct3_reg_2468 == 3'd1) & ~(funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 
    == 7'd111) & ~(o_pcode_fu_1223_p1 == 7'd55) & ~(o_pcode_fu_1223_p1 == 7'd23) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(o_pcode_fu_1223_p1 == 7'd51) & ~(o_pcode_fu_1223_p1 == 7'd115) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) 
    & (icmp_ln210_fu_1440_p2 == 1'd0)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd0)))) begin
        p_error_loc_17_reg_1014 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14) | ((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16)) | ((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (grp_fu_1174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd5) & (grp_fu_1174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd6) & (grp_fu_1168_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 
    == 3'd7) & (grp_fu_1168_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (grp_fu_1198_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd1) & (grp_fu_1198_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16)))) begin
        p_error_loc_17_reg_1014 <= p_error;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_error_loc_17_reg_1014 <= or_ln336_fu_1714_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & ((((((((((funct3_reg_2468 == 3'd6) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln96_reg_2858 == 1'd0)) | ((funct3_reg_2468 == 3'd7) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln102_reg_2854 == 1'd1))) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln90_reg_2862 == 1'd1))) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln84_reg_2866 == 1'd0))) | ((funct3_reg_2468 == 3'd3) & (o_pcode_reg_2464 == 7'd99))) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd99))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd6) & ~(funct3_reg_2468 == 3'd7) & ~(funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln72_reg_2874 == 1'd0))) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln78_reg_2870 == 1'd1))) | (~(o_pcode_reg_2464 == 7'd103) & ~(o_pcode_reg_2464 == 7'd111) & ~(o_pcode_reg_2464 == 7'd99))))) begin
        p_error_loc_18_reg_1137 <= ap_phi_mux_p_error_loc_17_phi_fu_1018_p100;
    end else if (((1'b1 == ap_CS_fsm_state24) | ((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_reg_2468 == 3'd4) & (grp_fu_1174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd5) & (grp_fu_1174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd6) & (grp_fu_1168_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd7) & (grp_fu_1168_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd0) & (grp_fu_1198_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((funct3_reg_2468 == 3'd1) & (grp_fu_1198_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)))) begin
        p_error_loc_18_reg_1137 <= p_error;
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        if ((grp_fu_1186_p3 == 1'd0)) begin
            p_error_loc_1_reg_841 <= 1'd1;
        end else if ((grp_fu_1186_p3 == 1'd1)) begin
            p_error_loc_1_reg_841 <= p_error;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state19))) begin
        add_ln114_1_reg_2797 <= add_ln114_1_fu_2098_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state19))) begin
        data_memory_addr_1_reg_2792 <= zext_ln153_fu_2044_p1;
        select_ln154_reg_2787 <= select_ln154_fu_2077_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        funct3_reg_2468 <= {{instr_memory_q0[14:12]}};
        imm_S_cast_reg_2545 <= {{instr_memory_q0[8:7]}};
        imm_S_reg_2538 <= imm_S_fu_1395_p5;
        o_pcode_reg_2464 <= o_pcode_fu_1223_p1;
        rd_reg_2505 <= {{instr_memory_q0[11:7]}};
        rs1_reg_2490 <= {{instr_memory_q0[19:15]}};
        rs2_reg_2495 <= {{instr_memory_q0[24:20]}};
        sext_ln38_1_reg_2485 <= sext_ln38_1_fu_1261_p1;
        sext_ln38_reg_2475 <= sext_ln38_fu_1257_p1;
        sext_ln42_reg_2533[31 : 1] <= sext_ln42_fu_1345_p1[31 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln102_reg_2854 <= grp_fu_1168_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_fu_1223_p1 == 7'd115) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln336_reg_2556 <= icmp_ln336_fu_1446_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln72_reg_2874 <= grp_fu_1198_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln78_reg_2870 <= grp_fu_1198_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln84_reg_2866 <= grp_fu_1174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd5) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln90_reg_2862 <= grp_fu_1174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln96_reg_2858 <= grp_fu_1168_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & ((((((((((funct3_reg_2468 == 3'd6) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln96_reg_2858 == 1'd0)) | ((funct3_reg_2468 == 3'd7) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln102_reg_2854 == 1'd1))) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln90_reg_2862 == 1'd1))) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln84_reg_2866 == 1'd0))) | ((funct3_reg_2468 == 3'd3) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1))) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd6) & ~(funct3_reg_2468 == 3'd7) & ~(funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 
    7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln72_reg_2874 == 1'd0))) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1) & (icmp_ln78_reg_2870 == 1'd1))) | (~(o_pcode_reg_2464 == 7'd103) & ~(o_pcode_reg_2464 == 7'd111) & ~(o_pcode_reg_2464 == 7'd99) & (ap_phi_mux_p_error_flag_17_phi_fu_868_p100 == 1'd1))))) begin
        p_error <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_pc_load_reg_2451 <= p_pc;
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        sext_ln154_reg_2810[31 : 3] <= sext_ln154_fu_2125_p1[31 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((o_pcode_fu_1223_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln114_1_reg_2717 <= {{instr_memory_q0[21:20]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)))) begin
        ap_phi_mux_p_error_flag_17_phi_fu_868_p100 = p_error_flag_1_reg_829;
    end else begin
        ap_phi_mux_p_error_flag_17_phi_fu_868_p100 = p_error_flag_17_reg_863;
    end
end

always @ (*) begin
    if ((((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)))) begin
        ap_phi_mux_p_error_loc_17_phi_fu_1018_p100 = p_error_loc_1_reg_841;
    end else begin
        ap_phi_mux_p_error_loc_17_phi_fu_1018_p100 = p_error_loc_17_reg_1014;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & ((((((((((funct3_reg_2468 == 3'd6) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln96_reg_2858 == 1'd0)) | ((funct3_reg_2468 == 3'd7) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln102_reg_2854 == 1'd1))) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln90_reg_2862 == 1'd1))) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln84_reg_2866 == 1'd0))) | ((funct3_reg_2468 == 3'd3) & (o_pcode_reg_2464 == 7'd99))) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd99))) | (~(funct3_reg_2468 == 3'd4) & ~(funct3_reg_2468 == 3'd5) & ~(funct3_reg_2468 == 3'd6) & ~(funct3_reg_2468 == 3'd7) & ~(funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln72_reg_2874 == 1'd0))) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd99) & (icmp_ln78_reg_2870 == 1'd1))) | (~(o_pcode_reg_2464 == 7'd103) & ~(o_pcode_reg_2464 == 7'd111) & ~(o_pcode_reg_2464 == 7'd99))))) begin
        ap_phi_mux_p_error_loc_18_phi_fu_1140_p18 = ap_phi_mux_p_error_loc_17_phi_fu_1018_p100;
    end else begin
        ap_phi_mux_p_error_loc_18_phi_fu_1140_p18 = p_error_loc_18_reg_1137;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)))) begin
        data_memory_address0 = data_memory_addr_1_reg_2792;
    end else if (((o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state19))) begin
        data_memory_address0 = zext_ln115_fu_2113_p1;
    end else if (((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state19))) begin
        data_memory_address0 = zext_ln153_fu_2044_p1;
    end else begin
        data_memory_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state19)) | ((o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state19)))) begin
        data_memory_ce0 = 1'b1;
    end else begin
        data_memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21))) begin
        data_memory_d0 = or_ln163_fu_2386_p2;
    end else if (((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21))) begin
        data_memory_d0 = or_ln168_fu_2341_p2;
    end else if (((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21))) begin
        data_memory_d0 = xreg_q1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        data_memory_d0 = zext_ln158_fu_2133_p1;
    end else begin
        data_memory_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state21)) | ((o_pcode_reg_2464 == 7'd35) & (grp_fu_1186_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state20)))) begin
        data_memory_we0 = 1'b1;
    end else begin
        data_memory_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        instr_memory_ce0 = 1'b1;
    end else begin
        instr_memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        xreg_address0 = zext_ln66_fu_2441_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        xreg_address0 = zext_ln220_2_fu_1948_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        xreg_address0 = zext_ln223_2_fu_1934_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln54_fu_1709_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln57_fu_1704_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln60_fu_1682_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln65_fu_1677_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln72_1_fu_1672_p1;
    end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln78_1_fu_1662_p1;
    end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln84_1_fu_1652_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln90_1_fu_1642_p1;
    end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln96_1_fu_1632_p1;
    end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln102_1_fu_1622_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln114_fu_1602_p1;
    end else if (((o_pcode_fu_1223_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln152_fu_1597_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
        xreg_address0 = zext_ln220_fu_1592_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
        xreg_address0 = zext_ln223_fu_1587_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln184_fu_1582_p1;
    end else if (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln187_fu_1577_p1;
    end else if (((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln194_fu_1572_p1;
    end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln201_fu_1567_p1;
    end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln204_fu_1562_p1;
    end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln207_fu_1557_p1;
    end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln211_fu_1552_p1;
    end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln319_1_fu_1547_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
        xreg_address0 = zext_ln243_1_fu_1537_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
        xreg_address0 = zext_ln247_1_fu_1527_p1;
    end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln257_fu_1512_p1;
    end else if (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln265_1_fu_1507_p1;
    end else if (((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln277_1_fu_1497_p1;
    end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln289_1_fu_1487_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
        xreg_address0 = zext_ln298_fu_1472_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
        xreg_address0 = zext_ln301_1_fu_1467_p1;
    end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address0 = zext_ln311_1_fu_1457_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        xreg_address0 = 5'd0;
    end else begin
        xreg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln124_fu_2299_p1;
    end else if (((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln129_fu_2269_p1;
    end else if (((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln133_fu_2239_p1;
    end else if (((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln137_1_fu_2235_p1;
    end else if (((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln142_1_fu_2205_p1;
    end else if (((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln163_fu_2147_p1;
    end else if (((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln168_fu_2143_p1;
    end else if (((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_address1 = zext_ln172_fu_2139_p1;
    end else if (((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln184_1_fu_1920_p1;
    end else if (((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln188_fu_1911_p1;
    end else if (((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln195_fu_1897_p1;
    end else if (((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln201_1_fu_1888_p1;
    end else if (((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln204_1_fu_1878_p1;
    end else if (((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln207_1_fu_1868_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xreg_address1 = zext_ln211_2_fu_1858_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        xreg_address1 = zext_ln319_2_fu_1844_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        xreg_address1 = zext_ln243_2_fu_1833_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        xreg_address1 = zext_ln247_2_fu_1822_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        xreg_address1 = zext_ln257_2_fu_1811_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        xreg_address1 = zext_ln266_fu_1787_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        xreg_address1 = zext_ln278_fu_1778_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        xreg_address1 = zext_ln289_2_fu_1774_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xreg_address1 = zext_ln298_2_fu_1763_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        xreg_address1 = zext_ln301_2_fu_1744_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        xreg_address1 = zext_ln311_2_fu_1725_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln72_fu_1667_p1;
    end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln78_fu_1657_p1;
    end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln84_fu_1647_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln90_fu_1637_p1;
    end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln96_fu_1627_p1;
    end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln102_fu_1617_p1;
    end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln319_fu_1542_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
        xreg_address1 = zext_ln243_fu_1532_p1;
    end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
        xreg_address1 = zext_ln247_fu_1522_p1;
    end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln257_1_fu_1517_p1;
    end else if (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln265_fu_1502_p1;
    end else if (((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln277_fu_1492_p1;
    end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln289_fu_1482_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
        xreg_address1 = zext_ln298_1_fu_1477_p1;
    end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
        xreg_address1 = zext_ln301_fu_1462_p1;
    end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
        xreg_address1 = zext_ln311_fu_1452_p1;
    end else begin
        xreg_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state23) | ((o_pcode_fu_1223_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd0) 
    & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 
    == 3'd4) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 
    7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)))) begin
        xreg_ce0 = 1'b1;
    end else begin
        xreg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state14) | ((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 
    == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd35) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0)) | ((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32)) | ((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 
    == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0)) | ((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32)) | ((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1227_p4 
    == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1)))) begin
        xreg_ce1 = 1'b1;
    end else begin
        xreg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        xreg_d0 = lshr_ln220_fu_1941_p2;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        xreg_d0 = ashr_ln223_fu_1927_p2;
    end else if (((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_d0 = imm_U_fu_1427_p3;
    end else if (((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_d0 = add_ln57_fu_1698_p2;
    end else if ((((o_pcode_fu_1223_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)))) begin
        xreg_d0 = grp_fu_1162_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        xreg_d0 = 32'd0;
    end else begin
        xreg_d0 = 'bx;
    end
end

always @ (*) begin
    if (((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_d1 = sext_ln124_fu_2294_p1;
    end else if (((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_d1 = sext_ln129_fu_2264_p1;
    end else if (((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_d1 = temp_2_fu_2170_p3;
    end else if (((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_d1 = zext_ln137_fu_2230_p1;
    end else if (((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20))) begin
        xreg_d1 = zext_ln142_fu_2200_p1;
    end else if (((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = grp_fu_1180_p2;
    end else if (((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = zext_ln187_1_fu_1915_p1;
    end else if (((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = zext_ln194_1_fu_1901_p1;
    end else if (((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = xor_ln201_fu_1882_p2;
    end else if (((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = or_ln204_fu_1872_p2;
    end else if (((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_d1 = and_ln207_fu_1862_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        xreg_d1 = shl_ln211_fu_1851_p2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        xreg_d1 = and_ln319_fu_1837_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        xreg_d1 = add_ln243_fu_1826_p2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        xreg_d1 = sub_ln247_fu_1815_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        xreg_d1 = shl_ln257_fu_1804_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        xreg_d1 = zext_ln265_2_fu_1791_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        xreg_d1 = zext_ln277_2_fu_1782_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        xreg_d1 = xor_ln289_fu_1767_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xreg_d1 = lshr_ln298_fu_1756_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        xreg_d1 = ashr_ln301_fu_1737_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        xreg_d1 = or_ln311_fu_1718_p2;
    end else begin
        xreg_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | ((o_pcode_fu_1223_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1223_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)))) begin
        xreg_we0 = 1'b1;
    end else begin
        xreg_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state14) | ((funct3_reg_2468 == 3'd3) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd4) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd5) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd6) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd7) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2468 == 3'd0) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd1) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)) | ((funct3_reg_2468 == 3'd2) & (1'b1 == ap_CS_fsm_state16)) 
    | ((funct3_reg_2468 == 3'd2) & (o_pcode_reg_2464 == 7'd3) & (1'b1 == ap_CS_fsm_state20)))) begin
        xreg_we1 = 1'b1;
    end else begin
        xreg_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~(funct3_fu_1227_p4 == 3'd2) & ~(funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if ((~(funct3_fu_1227_p4 == 3'd1) & ~(funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((funct3_fu_1227_p4 == 3'd7) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((funct3_fu_1227_p4 == 3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1237_p4 == 7'd32))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((funct3_fu_1227_p4 == 3'd6) & (o_pcode_fu_1223_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1440_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((o_pcode_fu_1223_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if (((1'b1 == ap_CS_fsm_state2) & ((o_pcode_fu_1223_p1 == 7'd55) | ((o_pcode_fu_1223_p1 == 7'd23) | ((o_pcode_fu_1223_p1 == 7'd111) | ((((((((((((~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(funct3_fu_1227_p4 == 3'd0) & (funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd51) & (icmp_ln210_fu_1440_p2 == 1'd0)) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(funct3_fu_1227_p4 == 3'd0) & (funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd51) & (icmp_ln210_fu_1440_p2 == 1'd0))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(funct3_fu_1227_p4 == 3'd1) & ~(funct3_fu_1227_p4 == 3'd2) & ~(funct3_fu_1227_p4 == 3'd3) & ~(funct3_fu_1227_p4 == 3'd4) & ~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 
    == 7'd51))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(funct3_fu_1227_p4 == 3'd0) & (funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd51) & (icmp_ln210_fu_1440_p2 == 1'd0))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(o_pcode_fu_1223_p1 == 7'd51) & ~(o_pcode_fu_1223_p1 == 7'd115))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(funct3_fu_1227_p4 == 3'd0) & ~(funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd51) & (icmp_ln210_fu_1440_p2 == 1'd0))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(funct3_fu_1227_p4 == 3'd0) & (funct3_fu_1227_p4 == 
    3'd4) & (o_pcode_fu_1223_p1 == 7'd51) & (icmp_ln210_fu_1440_p2 == 1'd0))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(o_pcode_fu_1223_p1 == 7'd19) & ~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd0) & (o_pcode_fu_1223_p1 == 7'd51))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & ~(funct3_fu_1227_p4 == 3'd1) & ~(funct7_fu_1237_p4 == 7'd0) & ~(funct7_fu_1237_p4 == 7'd32) & (funct3_fu_1227_p4 == 3'd5) & (o_pcode_fu_1223_p1 == 7'd19))) | (~(o_pcode_fu_1223_p1 == 7'd103) & ~(o_pcode_fu_1223_p1 == 7'd99) & ~(o_pcode_fu_1223_p1 == 7'd3) & ~(o_pcode_fu_1223_p1 == 7'd35) & (funct3_fu_1227_p4 == 3'd1) & (o_pcode_fu_1223_p1 == 7'd19) & (icmp_ln210_fu_1440_p2 == 1'd0))) | (~(o_pcode_fu_1223_p1 == 7'd103) & (funct3_fu_1227_p4 == 3'd3) & (o_pcode_fu_1223_p1 == 7'd99))) | (~(o_pcode_fu_1223_p1 == 7'd103) & 
    (funct3_fu_1227_p4 == 3'd2) & (o_pcode_fu_1223_p1 == 7'd99)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else if (((1'b1 == ap_CS_fsm_state2) & ((o_pcode_fu_1223_p1 == 7'd3) | (o_pcode_fu_1223_p1 == 7'd35)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln114_1_fu_2098_p2 = (trunc_ln114_2_fu_2089_p1 + trunc_ln114_1_reg_2717);

assign add_ln152_1_fu_1990_p2 = (trunc_ln152_4_fu_1966_p1 + trunc_ln152_3_fu_1963_p1);

assign add_ln152_2_fu_1970_p2 = (trunc_ln152_fu_1952_p1 + imm_S_cast_reg_2545);

assign add_ln152_3_fu_1975_p2 = ($signed(xreg_q0) + $signed(imm_S_reg_2538));

assign add_ln152_fu_1980_p2 = ($signed(zext_ln152_1_fu_1956_p1) + $signed(sext_ln152_fu_1960_p1));

assign add_ln243_fu_1826_p2 = (xreg_q0 + xreg_q1);

assign add_ln57_fu_1698_p2 = (p_pc_load_reg_2451 + imm_U_fu_1427_p3);

assign add_ln61_fu_1687_p2 = ($signed(p_pc_load_reg_2451) + $signed(sext_ln45_fu_1391_p1));

assign and_ln163_fu_2359_p2 = (xor_ln163_fu_2353_p2 & p_0_03225_reg_852);

assign and_ln168_fu_2314_p2 = (xor_ln168_fu_2308_p2 & p_0_03225_reg_852);

assign and_ln207_fu_1862_p2 = (xreg_q0 & sext_ln38_reg_2475);

assign and_ln319_fu_1837_p2 = (xreg_q1 & xreg_q0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ashr_ln223_fu_1927_p2 = $signed(xreg_q0) >>> zext_ln223_1_fu_1924_p1;

assign ashr_ln301_fu_1737_p2 = $signed(xreg_q1) >>> zext_ln301_3_fu_1733_p1;

assign error = ap_phi_mux_p_error_loc_18_phi_fu_1140_p18;

assign funct12_fu_1247_p4 = {{instr_memory_q0[31:20]}};

assign funct3_fu_1227_p4 = {{instr_memory_q0[14:12]}};

assign funct7_fu_1237_p4 = {{instr_memory_q0[31:25]}};

assign grp_fu_1162_p2 = (p_pc_load_reg_2451 + 32'd4);

assign grp_fu_1168_p2 = ((xreg_q1 < xreg_q0) ? 1'b1 : 1'b0);

assign grp_fu_1174_p2 = (($signed(xreg_q1) < $signed(xreg_q0)) ? 1'b1 : 1'b0);

assign grp_fu_1180_p2 = ($signed(xreg_q0) + $signed(sext_ln38_reg_2475));

assign grp_fu_1186_p3 = data_memory_q0[32'd28];

assign grp_fu_1194_p2 = ($signed(p_pc_load_reg_2451) + $signed(sext_ln42_reg_2533));

assign grp_fu_1198_p2 = ((xreg_q1 == xreg_q0) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_1906_p2 = (($signed(xreg_q0) < $signed(sext_ln38_reg_2475)) ? 1'b1 : 1'b0);

assign icmp_ln194_fu_1892_p2 = ((xreg_q0 < sext_ln38_reg_2475) ? 1'b1 : 1'b0);

assign icmp_ln210_fu_1440_p2 = ((funct7_fu_1237_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln336_fu_1446_p2 = ((funct12_fu_1247_p4 != 12'd0) ? 1'b1 : 1'b0);

assign imm_B_fu_1331_p6 = {{{{{tmp_3_fu_1323_p3}, {tmp_2_fu_1315_p3}}, {tmp_1_fu_1305_p4}}, {tmp_fu_1295_p4}}, {1'd0}};

assign imm_J_fu_1377_p6 = {{{{{tmp_3_fu_1323_p3}, {tmp_6_fu_1367_p4}}, {tmp_5_fu_1359_p3}}, {tmp_4_fu_1349_p4}}, {1'd0}};

assign imm_S_fu_1395_p5 = {{sext_ln38_fu_1257_p1[31:5]}, {rd_fu_1285_p4}};

assign imm_U_fu_1427_p3 = {{tmp_8_fu_1417_p4}, {12'd0}};

assign instr_memory_address0 = zext_ln33_fu_1218_p1;

assign lshr_ln123_fu_2284_p2 = temp_2_fu_2170_p3 >> zext_ln123_fu_2280_p1;

assign lshr_ln128_fu_2254_p2 = temp_2_fu_2170_p3 >> zext_ln128_fu_2250_p1;

assign lshr_ln136_fu_2220_p2 = temp_2_fu_2170_p3 >> zext_ln136_fu_2216_p1;

assign lshr_ln141_fu_2190_p2 = temp_2_fu_2170_p3 >> zext_ln141_fu_2186_p1;

assign lshr_ln1_fu_2103_p4 = {{pos_fu_2093_p2[17:2]}};

assign lshr_ln220_fu_1941_p2 = xreg_q0 >> zext_ln220_1_fu_1938_p1;

assign lshr_ln298_fu_1756_p2 = xreg_q0 >> zext_ln298_3_fu_1752_p1;

assign lshr_ln_fu_1208_p4 = {{p_pc[17:2]}};

assign mask_1_fu_2303_p2 = 32'd65535 << sext_ln154_reg_2810;

assign mask_fu_2348_p2 = 32'd255 << sext_ln154_reg_2810;

assign o_pcode_fu_1223_p1 = instr_memory_q0[6:0];

assign offset_fu_2118_p3 = {{select_ln154_reg_2787}, {3'd0}};

assign or_ln116_fu_2165_p2 = (xor_ln116_fu_2155_p2 | p_error);

assign or_ln163_fu_2386_p2 = (trunc_ln163_1_fu_2382_p1 | and_ln163_fu_2359_p2);

assign or_ln168_fu_2341_p2 = (trunc_ln168_1_fu_2337_p1 | and_ln168_fu_2314_p2);

assign or_ln204_fu_1872_p2 = (xreg_q0 | sext_ln38_reg_2475);

assign or_ln311_fu_1718_p2 = (xreg_q1 | xreg_q0);

assign or_ln336_fu_1714_p2 = (p_error | icmp_ln336_reg_2556);

assign p_and_t_fu_2055_p3 = {{1'd0}, {sub_ln154_fu_2049_p2}};

assign pos_1_fu_2036_p3 = ((tmp_9_fu_1996_p3[0:0] == 1'b1) ? sub_ln152_1_fu_2020_p2 : trunc_ln152_2_fu_2026_p4);

assign pos_fu_2093_p2 = ($signed(trunc_ln114_fu_2085_p1) + $signed(sext_ln38_1_reg_2485));

assign rd_fu_1285_p4 = {{instr_memory_q0[11:7]}};

assign result_1_fu_2260_p1 = lshr_ln128_fu_2254_p2[15:0];

assign result_2_fu_2226_p1 = lshr_ln136_fu_2220_p2[7:0];

assign result_3_fu_2196_p1 = lshr_ln141_fu_2190_p2[15:0];

assign result_fu_2290_p1 = lshr_ln123_fu_2284_p2[7:0];

assign rs1_fu_1265_p4 = {{instr_memory_q0[19:15]}};

assign rs2_fu_1275_p4 = {{instr_memory_q0[24:20]}};

assign select_ln154_fu_2077_p3 = ((tmp_9_fu_1996_p3[0:0] == 1'b1) ? sub_ln154_1_fu_2063_p2 : tmp_s_fu_2069_p3);

assign sext_ln124_fu_2294_p1 = $signed(result_fu_2290_p1);

assign sext_ln129_fu_2264_p1 = $signed(result_1_fu_2260_p1);

assign sext_ln152_fu_1960_p1 = imm_S_reg_2538;

assign sext_ln154_fu_2125_p1 = $signed(offset_fu_2118_p3);

assign sext_ln38_1_fu_1261_p1 = funct12_fu_1247_p4;

assign sext_ln38_fu_1257_p1 = funct12_fu_1247_p4;

assign sext_ln42_fu_1345_p1 = $signed(imm_B_fu_1331_p6);

assign sext_ln45_fu_1391_p1 = $signed(imm_J_fu_1377_p6);

assign shl_ln163_fu_2376_p2 = zext_ln163_1_fu_2369_p1 << zext_ln163_2_fu_2373_p1;

assign shl_ln168_fu_2331_p2 = zext_ln168_1_fu_2324_p1 << zext_ln168_2_fu_2328_p1;

assign shl_ln1_fu_2243_p3 = {{add_ln114_1_reg_2797}, {3'd0}};

assign shl_ln211_fu_1851_p2 = xreg_q0 << zext_ln211_1_fu_1848_p1;

assign shl_ln257_fu_1804_p2 = xreg_q0 << zext_ln257_3_fu_1800_p1;

assign shl_ln2_fu_2209_p3 = {{add_ln114_1_reg_2797}, {3'd0}};

assign shl_ln3_fu_2179_p3 = {{add_ln114_1_reg_2797}, {3'd0}};

assign shl_ln_fu_2273_p3 = {{add_ln114_1_reg_2797}, {3'd0}};

assign sub_ln152_1_fu_2020_p2 = (16'd0 - trunc_ln152_1_fu_2010_p4);

assign sub_ln152_fu_2004_p2 = (18'd0 - add_ln152_1_fu_1990_p2);

assign sub_ln154_1_fu_2063_p2 = (3'd0 - p_and_t_fu_2055_p3);

assign sub_ln154_fu_2049_p2 = (2'd0 - trunc_ln152_5_fu_1986_p1);

assign sub_ln247_fu_1815_p2 = (xreg_q1 - xreg_q0);

assign temp_1_fu_2151_p1 = data_memory_q0[27:0];

assign temp_2_fu_2170_p3 = ((grp_fu_1186_p3[0:0] == 1'b1) ? zext_ln115_1_fu_2161_p1 : data_memory_q0);

assign tmp_1_fu_1305_p4 = {{instr_memory_q0[30:25]}};

assign tmp_2_fu_1315_p3 = instr_memory_q0[32'd7];

assign tmp_3_fu_1323_p3 = instr_memory_q0[32'd31];

assign tmp_4_fu_1349_p4 = {{instr_memory_q0[30:21]}};

assign tmp_5_fu_1359_p3 = instr_memory_q0[32'd20];

assign tmp_6_fu_1367_p4 = {{instr_memory_q0[19:12]}};

assign tmp_8_fu_1417_p4 = {{instr_memory_q0[31:12]}};

assign tmp_9_fu_1996_p3 = add_ln152_fu_1980_p2[32'd33];

assign tmp_fu_1295_p4 = {{instr_memory_q0[11:8]}};

assign tmp_s_fu_2069_p3 = {{1'd0}, {add_ln152_2_fu_1970_p2}};

assign trunc_ln114_2_fu_2089_p1 = xreg_q0[1:0];

assign trunc_ln114_fu_2085_p1 = xreg_q0[17:0];

assign trunc_ln152_1_fu_2010_p4 = {{sub_ln152_fu_2004_p2[17:2]}};

assign trunc_ln152_2_fu_2026_p4 = {{add_ln152_1_fu_1990_p2[17:2]}};

assign trunc_ln152_3_fu_1963_p1 = imm_S_reg_2538[17:0];

assign trunc_ln152_4_fu_1966_p1 = xreg_q0[17:0];

assign trunc_ln152_5_fu_1986_p1 = add_ln152_3_fu_1975_p2[1:0];

assign trunc_ln152_fu_1952_p1 = xreg_q0[1:0];

assign trunc_ln155_fu_2129_p1 = data_memory_q0[27:0];

assign trunc_ln163_1_fu_2382_p1 = shl_ln163_fu_2376_p2[31:0];

assign trunc_ln163_fu_2365_p1 = xreg_q1[7:0];

assign trunc_ln168_1_fu_2337_p1 = shl_ln168_fu_2331_p2[31:0];

assign trunc_ln168_fu_2320_p1 = xreg_q1[15:0];

assign trunc_ln257_fu_1796_p1 = xreg_q1[4:0];

assign trunc_ln298_fu_1748_p1 = xreg_q1[4:0];

assign trunc_ln301_fu_1729_p1 = xreg_q0[4:0];

assign xor_ln116_fu_2155_p2 = (grp_fu_1186_p3 ^ 1'd1);

assign xor_ln163_fu_2353_p2 = (mask_fu_2348_p2 ^ 32'd4294967295);

assign xor_ln168_fu_2308_p2 = (mask_1_fu_2303_p2 ^ 32'd4294967295);

assign xor_ln201_fu_1882_p2 = (xreg_q0 ^ sext_ln38_reg_2475);

assign xor_ln289_fu_1767_p2 = (xreg_q1 ^ xreg_q0);

assign zext_ln102_1_fu_1622_p1 = rs2_fu_1275_p4;

assign zext_ln102_fu_1617_p1 = rs1_fu_1265_p4;

assign zext_ln114_fu_1602_p1 = rs1_fu_1265_p4;

assign zext_ln115_1_fu_2161_p1 = temp_1_fu_2151_p1;

assign zext_ln115_fu_2113_p1 = lshr_ln1_fu_2103_p4;

assign zext_ln123_fu_2280_p1 = shl_ln_fu_2273_p3;

assign zext_ln124_fu_2299_p1 = rd_reg_2505;

assign zext_ln128_fu_2250_p1 = shl_ln1_fu_2243_p3;

assign zext_ln129_fu_2269_p1 = rd_reg_2505;

assign zext_ln133_fu_2239_p1 = rd_reg_2505;

assign zext_ln136_fu_2216_p1 = shl_ln2_fu_2209_p3;

assign zext_ln137_1_fu_2235_p1 = rd_reg_2505;

assign zext_ln137_fu_2230_p1 = result_2_fu_2226_p1;

assign zext_ln141_fu_2186_p1 = shl_ln3_fu_2179_p3;

assign zext_ln142_1_fu_2205_p1 = rd_reg_2505;

assign zext_ln142_fu_2200_p1 = result_3_fu_2196_p1;

assign zext_ln152_1_fu_1956_p1 = xreg_q0;

assign zext_ln152_fu_1597_p1 = rs1_fu_1265_p4;

assign zext_ln153_fu_2044_p1 = pos_1_fu_2036_p3;

assign zext_ln158_fu_2133_p1 = trunc_ln155_fu_2129_p1;

assign zext_ln163_1_fu_2369_p1 = trunc_ln163_fu_2365_p1;

assign zext_ln163_2_fu_2373_p1 = $unsigned(sext_ln154_reg_2810);

assign zext_ln163_fu_2147_p1 = rs2_reg_2495;

assign zext_ln168_1_fu_2324_p1 = trunc_ln168_fu_2320_p1;

assign zext_ln168_2_fu_2328_p1 = $unsigned(sext_ln154_reg_2810);

assign zext_ln168_fu_2143_p1 = rs2_reg_2495;

assign zext_ln172_fu_2139_p1 = rs2_reg_2495;

assign zext_ln184_1_fu_1920_p1 = rd_reg_2505;

assign zext_ln184_fu_1582_p1 = rs1_fu_1265_p4;

assign zext_ln187_1_fu_1915_p1 = icmp_ln187_fu_1906_p2;

assign zext_ln187_fu_1577_p1 = rs1_fu_1265_p4;

assign zext_ln188_fu_1911_p1 = rd_reg_2505;

assign zext_ln194_1_fu_1901_p1 = icmp_ln194_fu_1892_p2;

assign zext_ln194_fu_1572_p1 = rs1_fu_1265_p4;

assign zext_ln195_fu_1897_p1 = rd_reg_2505;

assign zext_ln201_1_fu_1888_p1 = rd_reg_2505;

assign zext_ln201_fu_1567_p1 = rs1_fu_1265_p4;

assign zext_ln204_1_fu_1878_p1 = rd_reg_2505;

assign zext_ln204_fu_1562_p1 = rs1_fu_1265_p4;

assign zext_ln207_1_fu_1868_p1 = rd_reg_2505;

assign zext_ln207_fu_1557_p1 = rs1_fu_1265_p4;

assign zext_ln211_1_fu_1848_p1 = rs2_reg_2495;

assign zext_ln211_2_fu_1858_p1 = rd_reg_2505;

assign zext_ln211_fu_1552_p1 = rs1_fu_1265_p4;

assign zext_ln220_1_fu_1938_p1 = rs2_reg_2495;

assign zext_ln220_2_fu_1948_p1 = rd_reg_2505;

assign zext_ln220_fu_1592_p1 = rs1_fu_1265_p4;

assign zext_ln223_1_fu_1924_p1 = rs2_reg_2495;

assign zext_ln223_2_fu_1934_p1 = rd_reg_2505;

assign zext_ln223_fu_1587_p1 = rs1_fu_1265_p4;

assign zext_ln243_1_fu_1537_p1 = rs2_fu_1275_p4;

assign zext_ln243_2_fu_1833_p1 = rd_reg_2505;

assign zext_ln243_fu_1532_p1 = rs1_fu_1265_p4;

assign zext_ln247_1_fu_1527_p1 = rs2_fu_1275_p4;

assign zext_ln247_2_fu_1822_p1 = rd_reg_2505;

assign zext_ln247_fu_1522_p1 = rs1_fu_1265_p4;

assign zext_ln257_1_fu_1517_p1 = rs2_fu_1275_p4;

assign zext_ln257_2_fu_1811_p1 = rd_reg_2505;

assign zext_ln257_3_fu_1800_p1 = trunc_ln257_fu_1796_p1;

assign zext_ln257_fu_1512_p1 = rs1_fu_1265_p4;

assign zext_ln265_1_fu_1507_p1 = rs2_fu_1275_p4;

assign zext_ln265_2_fu_1791_p1 = grp_fu_1174_p2;

assign zext_ln265_fu_1502_p1 = rs1_fu_1265_p4;

assign zext_ln266_fu_1787_p1 = rd_reg_2505;

assign zext_ln277_1_fu_1497_p1 = rs2_fu_1275_p4;

assign zext_ln277_2_fu_1782_p1 = grp_fu_1168_p2;

assign zext_ln277_fu_1492_p1 = rs1_fu_1265_p4;

assign zext_ln278_fu_1778_p1 = rd_reg_2505;

assign zext_ln289_1_fu_1487_p1 = rs2_fu_1275_p4;

assign zext_ln289_2_fu_1774_p1 = rd_reg_2505;

assign zext_ln289_fu_1482_p1 = rs1_fu_1265_p4;

assign zext_ln298_1_fu_1477_p1 = rs2_fu_1275_p4;

assign zext_ln298_2_fu_1763_p1 = rd_reg_2505;

assign zext_ln298_3_fu_1752_p1 = trunc_ln298_fu_1748_p1;

assign zext_ln298_fu_1472_p1 = rs1_fu_1265_p4;

assign zext_ln301_1_fu_1467_p1 = rs2_fu_1275_p4;

assign zext_ln301_2_fu_1744_p1 = rd_reg_2505;

assign zext_ln301_3_fu_1733_p1 = trunc_ln301_fu_1729_p1;

assign zext_ln301_fu_1462_p1 = rs1_fu_1265_p4;

assign zext_ln311_1_fu_1457_p1 = rs2_fu_1275_p4;

assign zext_ln311_2_fu_1725_p1 = rd_reg_2505;

assign zext_ln311_fu_1452_p1 = rs1_fu_1265_p4;

assign zext_ln319_1_fu_1547_p1 = rs2_fu_1275_p4;

assign zext_ln319_2_fu_1844_p1 = rd_reg_2505;

assign zext_ln319_fu_1542_p1 = rs1_fu_1265_p4;

assign zext_ln33_fu_1218_p1 = lshr_ln_fu_1208_p4;

assign zext_ln54_fu_1709_p1 = rd_fu_1285_p4;

assign zext_ln57_fu_1704_p1 = rd_fu_1285_p4;

assign zext_ln60_fu_1682_p1 = rd_fu_1285_p4;

assign zext_ln65_fu_1677_p1 = rd_fu_1285_p4;

assign zext_ln66_fu_2441_p1 = rs1_reg_2490;

assign zext_ln72_1_fu_1672_p1 = rs2_fu_1275_p4;

assign zext_ln72_fu_1667_p1 = rs1_fu_1265_p4;

assign zext_ln78_1_fu_1662_p1 = rs2_fu_1275_p4;

assign zext_ln78_fu_1657_p1 = rs1_fu_1265_p4;

assign zext_ln84_1_fu_1652_p1 = rs2_fu_1275_p4;

assign zext_ln84_fu_1647_p1 = rs1_fu_1265_p4;

assign zext_ln90_1_fu_1642_p1 = rs2_fu_1275_p4;

assign zext_ln90_fu_1637_p1 = rs1_fu_1265_p4;

assign zext_ln96_1_fu_1632_p1 = rs2_fu_1275_p4;

assign zext_ln96_fu_1627_p1 = rs1_fu_1265_p4;

always @ (posedge ap_clk) begin
    sext_ln42_reg_2533[0] <= 1'b0;
    sext_ln154_reg_2810[2:0] <= 3'b000;
end

endmodule //processor
