// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processor_processor,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.513750,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=333,HLS_SYN_LUT=3810,HLS_VERSION=2023_1_1}" *)

module processor (
        ap_clk,
        ap_rst,
        memory_address0,
        memory_ce0,
        memory_we0,
        memory_d0,
        memory_q0,
        error,
        pc
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst;
output  [16:0] memory_address0;
output   memory_ce0;
output   memory_we0;
output  [31:0] memory_d0;
input  [31:0] memory_q0;
output  [0:0] error;
output  [31:0] pc;

reg[16:0] memory_address0;
reg memory_ce0;
reg memory_we0;
reg[31:0] memory_d0;

reg   [31:0] p_pc;
reg   [4:0] xreg_address0;
reg    xreg_ce0;
reg    xreg_we0;
reg   [31:0] xreg_d0;
wire   [31:0] xreg_q0;
reg   [4:0] xreg_address1;
reg    xreg_ce1;
reg    xreg_we1;
reg   [31:0] xreg_d1;
wire   [31:0] xreg_q1;
reg   [0:0] p_error;
reg   [1:0] reg_1005;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire   [6:0] o_pcode_fu_1038_p1;
wire   [2:0] funct3_fu_1042_p4;
wire   [31:0] grp_fu_995_p2;
wire    ap_CS_fsm_state18;
reg   [2:0] funct3_reg_2748;
wire   [0:0] grp_fu_971_p2;
wire   [0:0] grp_fu_977_p2;
wire   [0:0] grp_fu_999_p2;
reg   [31:0] p_pc_load_reg_2731;
wire    ap_CS_fsm_state1;
reg   [6:0] o_pcode_reg_2744;
wire   [6:0] funct7_fu_1052_p4;
reg   [6:0] funct7_reg_2752;
wire  signed [11:0] funct12_fu_1062_p4;
reg  signed [11:0] funct12_reg_2756;
wire  signed [31:0] sext_ln38_fu_1072_p1;
reg  signed [31:0] sext_ln38_reg_2761;
wire  signed [18:0] sext_ln38_1_fu_1076_p1;
reg  signed [18:0] sext_ln38_1_reg_2771;
wire   [4:0] rs1_fu_1080_p4;
reg   [4:0] rs1_reg_2780;
wire   [4:0] rs2_fu_1090_p4;
reg   [4:0] rs2_reg_2785;
wire   [4:0] rd_fu_1100_p4;
reg   [4:0] rd_reg_2794;
wire  signed [31:0] sext_ln42_fu_1160_p1;
reg  signed [31:0] sext_ln42_reg_2822;
wire  signed [31:0] imm_S_fu_1210_p5;
reg  signed [31:0] imm_S_reg_2827;
reg   [1:0] imm_S_cast_reg_2838;
wire   [0:0] icmp_ln210_fu_1251_p2;
reg   [0:0] icmp_ln210_reg_2844;
wire   [31:0] add_ln63_fu_1613_p2;
wire   [2:0] select_ln166_fu_2331_p3;
reg   [2:0] select_ln166_reg_3106;
wire    ap_CS_fsm_state16;
reg   [16:0] memory_addr_7_reg_3111;
wire   [2:0] select_ln158_fu_2463_p3;
reg   [2:0] select_ln158_reg_3121;
reg   [16:0] memory_addr_6_reg_3126;
wire   [1:0] add_ln142_1_fu_2493_p2;
reg   [1:0] add_ln142_1_reg_3136;
wire    ap_CS_fsm_state17;
wire   [1:0] add_ln135_1_fu_2527_p2;
reg   [1:0] add_ln135_1_reg_3146;
wire   [1:0] add_ln125_1_fu_2636_p2;
reg   [1:0] add_ln125_1_reg_3161;
wire   [1:0] add_ln118_1_fu_2670_p2;
reg   [1:0] add_ln118_1_reg_3171;
reg   [0:0] icmp_ln104_reg_3181;
reg   [0:0] icmp_ln98_reg_3185;
reg   [0:0] icmp_ln92_reg_3189;
reg   [0:0] icmp_ln86_reg_3193;
reg   [0:0] icmp_ln80_reg_3197;
reg   [0:0] icmp_ln74_reg_3201;
wire    ap_CS_fsm_state19;
reg   [31:0] ap_phi_mux_p_0_0_03388_phi_fu_933_p18;
reg   [31:0] p_0_0_03388_reg_930;
wire   [31:0] grp_fu_983_p2;
wire    ap_CS_fsm_state11;
wire   [31:0] grp_fu_964_p2;
wire   [63:0] zext_ln33_fu_1033_p1;
wire   [63:0] zext_ln311_fu_1281_p1;
wire   [63:0] zext_ln311_1_fu_1286_p1;
wire   [63:0] zext_ln301_fu_1291_p1;
wire   [63:0] zext_ln301_1_fu_1296_p1;
wire   [63:0] zext_ln298_1_fu_1306_p1;
wire   [63:0] zext_ln298_fu_1301_p1;
wire   [63:0] zext_ln289_fu_1323_p1;
wire   [63:0] zext_ln289_1_fu_1328_p1;
wire   [63:0] zext_ln277_fu_1339_p1;
wire   [63:0] zext_ln277_1_fu_1344_p1;
wire   [63:0] zext_ln265_fu_1355_p1;
wire   [63:0] zext_ln265_1_fu_1360_p1;
wire   [63:0] zext_ln257_1_fu_1376_p1;
wire   [63:0] zext_ln257_fu_1371_p1;
wire   [63:0] zext_ln247_fu_1381_p1;
wire   [63:0] zext_ln247_1_fu_1386_p1;
wire   [63:0] zext_ln243_fu_1391_p1;
wire   [63:0] zext_ln243_1_fu_1396_p1;
wire   [63:0] zext_ln319_fu_1413_p1;
wire   [63:0] zext_ln319_1_fu_1418_p1;
wire   [63:0] zext_ln211_fu_1429_p1;
wire   [63:0] zext_ln207_fu_1434_p1;
wire   [63:0] zext_ln204_fu_1439_p1;
wire   [63:0] zext_ln201_fu_1444_p1;
wire   [63:0] zext_ln194_fu_1449_p1;
wire   [63:0] zext_ln187_fu_1454_p1;
wire   [63:0] zext_ln184_fu_1459_p1;
wire   [63:0] zext_ln223_fu_1464_p1;
wire   [63:0] zext_ln220_fu_1469_p1;
wire   [63:0] zext_ln173_fu_1480_p1;
wire   [63:0] zext_ln173_1_fu_1485_p1;
wire   [63:0] zext_ln165_fu_1490_p1;
wire   [63:0] zext_ln157_fu_1495_p1;
wire   [63:0] zext_ln142_fu_1506_p1;
wire   [63:0] zext_ln135_fu_1511_p1;
wire   [63:0] zext_ln132_fu_1516_p1;
wire   [63:0] zext_ln125_fu_1521_p1;
wire   [63:0] zext_ln118_fu_1526_p1;
wire   [63:0] zext_ln104_fu_1537_p1;
wire   [63:0] zext_ln104_1_fu_1542_p1;
wire   [63:0] zext_ln98_fu_1547_p1;
wire   [63:0] zext_ln98_1_fu_1552_p1;
wire   [63:0] zext_ln92_fu_1557_p1;
wire   [63:0] zext_ln92_1_fu_1562_p1;
wire   [63:0] zext_ln86_fu_1567_p1;
wire   [63:0] zext_ln86_1_fu_1572_p1;
wire   [63:0] zext_ln80_fu_1577_p1;
wire   [63:0] zext_ln80_1_fu_1582_p1;
wire   [63:0] zext_ln74_fu_1587_p1;
wire   [63:0] zext_ln74_1_fu_1592_p1;
wire   [63:0] zext_ln67_fu_1603_p1;
wire   [63:0] zext_ln62_fu_1608_p1;
wire   [63:0] zext_ln59_fu_1630_p1;
wire   [63:0] zext_ln56_fu_1635_p1;
wire   [63:0] zext_ln311_2_fu_1653_p1;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln301_2_fu_1672_p1;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln298_2_fu_1691_p1;
wire   [63:0] zext_ln289_2_fu_1702_p1;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln278_fu_1706_p1;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln266_fu_1715_p1;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln257_2_fu_1739_p1;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln247_2_fu_1750_p1;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln243_2_fu_1761_p1;
wire   [63:0] zext_ln319_2_fu_1772_p1;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln145_1_fu_1918_p1;
wire   [63:0] zext_ln138_1_fu_1948_p1;
wire   [63:0] zext_ln132_2_fu_1952_p1;
wire   [63:0] zext_ln128_fu_1982_p1;
wire   [63:0] zext_ln121_fu_2012_p1;
wire   [63:0] zext_ln211_2_fu_2043_p1;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln207_1_fu_2053_p1;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln204_1_fu_2063_p1;
wire   [63:0] zext_ln201_1_fu_2073_p1;
wire   [63:0] zext_ln195_fu_2082_p1;
wire   [63:0] zext_ln188_fu_2096_p1;
wire   [63:0] zext_ln184_1_fu_2105_p1;
wire   [63:0] zext_ln223_2_fu_2119_p1;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln220_2_fu_2133_p1;
wire   [63:0] zext_ln173_3_fu_2211_p1;
wire    ap_CS_fsm_state15;
wire   [63:0] zext_ln168_fu_2339_p1;
wire   [63:0] zext_ln169_fu_2344_p1;
wire   [63:0] zext_ln160_fu_2471_p1;
wire   [63:0] zext_ln161_fu_2476_p1;
wire   [63:0] zext_ln143_fu_2509_p1;
wire   [63:0] zext_ln136_fu_2543_p1;
wire   [63:0] zext_ln132_3_fu_2618_p1;
wire   [63:0] zext_ln126_fu_2652_p1;
wire   [63:0] zext_ln119_fu_2686_p1;
wire   [63:0] zext_ln68_fu_2727_p1;
wire   [0:0] icmp_ln336_fu_1257_p2;
wire   [31:0] or_ln168_fu_1827_p2;
wire   [31:0] or_ln160_fu_1885_p2;
wire   [31:0] add_ln59_fu_1624_p2;
wire   [31:0] imm_U_fu_1242_p3;
wire   [31:0] or_ln311_fu_1646_p2;
wire   [31:0] ashr_ln301_fu_1665_p2;
wire   [31:0] lshr_ln298_fu_1684_p2;
wire   [31:0] xor_ln289_fu_1695_p2;
wire   [31:0] zext_ln277_2_fu_1710_p1;
wire   [31:0] zext_ln265_2_fu_1719_p1;
wire   [31:0] shl_ln257_fu_1732_p2;
wire   [31:0] sub_ln247_fu_1743_p2;
wire   [31:0] add_ln243_fu_1754_p2;
wire   [31:0] and_ln319_fu_1765_p2;
wire   [31:0] zext_ln145_fu_1913_p1;
wire   [31:0] zext_ln138_fu_1943_p1;
wire  signed [31:0] sext_ln128_fu_1977_p1;
wire  signed [31:0] sext_ln121_fu_2007_p1;
wire   [31:0] shl_ln211_fu_2036_p2;
wire   [31:0] and_ln207_fu_2047_p2;
wire   [31:0] or_ln204_fu_2057_p2;
wire   [31:0] xor_ln201_fu_2067_p2;
wire   [31:0] zext_ln194_1_fu_2086_p1;
wire   [31:0] zext_ln187_1_fu_2100_p1;
wire   [31:0] ashr_ln223_fu_2112_p2;
wire   [31:0] lshr_ln220_fu_2126_p2;
wire   [16:0] lshr_ln_fu_1023_p4;
wire   [0:0] tmp_3_fu_1138_p3;
wire   [0:0] tmp_2_fu_1130_p3;
wire   [5:0] tmp_1_fu_1120_p4;
wire   [3:0] tmp_fu_1110_p4;
wire   [12:0] imm_B_fu_1146_p6;
wire   [7:0] tmp_6_fu_1182_p4;
wire   [0:0] tmp_5_fu_1174_p3;
wire   [9:0] tmp_4_fu_1164_p4;
wire   [20:0] imm_J_fu_1192_p6;
wire   [19:0] tmp_8_fu_1232_p4;
wire  signed [31:0] sext_ln46_fu_1206_p1;
wire   [4:0] trunc_ln301_fu_1657_p1;
wire   [31:0] zext_ln301_3_fu_1661_p1;
wire   [4:0] trunc_ln298_fu_1676_p1;
wire   [31:0] zext_ln298_3_fu_1680_p1;
wire   [4:0] trunc_ln257_fu_1724_p1;
wire   [31:0] zext_ln257_3_fu_1728_p1;
wire   [5:0] offset_1_fu_1776_p3;
wire  signed [31:0] sext_ln166_fu_1783_p1;
wire   [31:0] mask_1_fu_1787_p2;
wire   [31:0] xor_ln168_fu_1793_p2;
wire   [15:0] trunc_ln169_fu_1805_p1;
wire   [32:0] zext_ln169_1_fu_1809_p1;
wire   [32:0] zext_ln169_2_fu_1813_p1;
wire   [32:0] shl_ln169_fu_1817_p2;
wire   [31:0] trunc_ln169_1_fu_1823_p1;
wire   [31:0] and_ln168_fu_1799_p2;
wire   [5:0] offset_fu_1834_p3;
wire  signed [31:0] sext_ln158_fu_1841_p1;
wire   [31:0] mask_fu_1845_p2;
wire   [31:0] xor_ln160_fu_1851_p2;
wire   [7:0] trunc_ln161_fu_1863_p1;
wire   [32:0] zext_ln161_1_fu_1867_p1;
wire   [32:0] zext_ln161_2_fu_1871_p1;
wire   [32:0] shl_ln161_fu_1875_p2;
wire   [31:0] trunc_ln161_1_fu_1881_p1;
wire   [31:0] and_ln160_fu_1857_p2;
wire   [4:0] shl_ln3_fu_1892_p3;
wire   [31:0] zext_ln144_fu_1899_p1;
wire   [31:0] lshr_ln144_fu_1903_p2;
wire   [15:0] result_3_fu_1909_p1;
wire   [4:0] shl_ln2_fu_1922_p3;
wire   [31:0] zext_ln137_fu_1929_p1;
wire   [31:0] lshr_ln137_fu_1933_p2;
wire   [7:0] result_2_fu_1939_p1;
wire   [4:0] shl_ln1_fu_1956_p3;
wire   [31:0] zext_ln127_fu_1963_p1;
wire   [31:0] lshr_ln127_fu_1967_p2;
wire   [15:0] result_1_fu_1973_p1;
wire   [4:0] shl_ln_fu_1986_p3;
wire   [31:0] zext_ln120_fu_1993_p1;
wire   [31:0] lshr_ln120_fu_1997_p2;
wire   [7:0] result_fu_2003_p1;
wire   [31:0] zext_ln211_1_fu_2033_p1;
wire   [0:0] icmp_ln194_fu_2077_p2;
wire   [0:0] icmp_ln187_fu_2091_p2;
wire   [31:0] zext_ln223_1_fu_2109_p1;
wire   [31:0] zext_ln220_1_fu_2123_p1;
wire   [33:0] zext_ln173_2_fu_2137_p1;
wire  signed [33:0] sext_ln173_fu_2141_p1;
wire   [18:0] trunc_ln173_1_fu_2147_p1;
wire   [18:0] trunc_ln173_fu_2144_p1;
wire   [33:0] add_ln173_fu_2151_p2;
wire   [18:0] add_ln173_1_fu_2157_p2;
wire   [18:0] sub_ln173_fu_2171_p2;
wire   [16:0] trunc_ln173_3_fu_2177_p4;
wire   [0:0] tmp_12_fu_2163_p3;
wire   [16:0] sub_ln173_1_fu_2187_p2;
wire   [16:0] trunc_ln173_4_fu_2193_p4;
wire   [16:0] select_ln173_fu_2203_p3;
wire   [1:0] trunc_ln165_fu_2216_p1;
wire   [33:0] zext_ln165_1_fu_2220_p1;
wire  signed [33:0] sext_ln165_fu_2224_p1;
wire   [31:0] grp_fu_990_p2;
wire   [18:0] trunc_ln165_4_fu_2230_p1;
wire   [18:0] trunc_ln165_3_fu_2227_p1;
wire   [33:0] add_ln165_fu_2239_p2;
wire   [18:0] add_ln165_1_fu_2249_p2;
wire   [18:0] sub_ln165_fu_2263_p2;
wire   [16:0] trunc_ln165_1_fu_2269_p4;
wire   [0:0] tmp_10_fu_2255_p3;
wire   [16:0] sub_ln165_1_fu_2279_p2;
wire   [16:0] trunc_ln165_2_fu_2285_p4;
wire   [1:0] trunc_ln165_5_fu_2245_p1;
wire   [1:0] sub_ln166_fu_2303_p2;
wire   [2:0] p_and_t3_fu_2309_p3;
wire   [1:0] add_ln165_2_fu_2234_p2;
wire   [2:0] sub_ln166_1_fu_2317_p2;
wire   [2:0] tmp_11_fu_2323_p3;
wire   [16:0] pos_5_fu_2295_p3;
wire   [1:0] trunc_ln157_fu_2348_p1;
wire   [33:0] zext_ln157_1_fu_2352_p1;
wire  signed [33:0] sext_ln157_fu_2356_p1;
wire   [18:0] trunc_ln157_4_fu_2362_p1;
wire   [18:0] trunc_ln157_3_fu_2359_p1;
wire   [33:0] add_ln157_fu_2371_p2;
wire   [18:0] add_ln157_1_fu_2381_p2;
wire   [18:0] sub_ln157_fu_2395_p2;
wire   [16:0] trunc_ln157_1_fu_2401_p4;
wire   [0:0] tmp_9_fu_2387_p3;
wire   [16:0] sub_ln157_1_fu_2411_p2;
wire   [16:0] trunc_ln157_2_fu_2417_p4;
wire   [1:0] trunc_ln157_5_fu_2377_p1;
wire   [1:0] sub_ln158_fu_2435_p2;
wire   [2:0] p_and_t_fu_2441_p3;
wire   [1:0] add_ln157_2_fu_2366_p2;
wire   [2:0] sub_ln158_1_fu_2449_p2;
wire   [2:0] tmp_s_fu_2455_p3;
wire   [16:0] pos_4_fu_2427_p3;
wire   [18:0] trunc_ln142_fu_2480_p1;
wire   [1:0] trunc_ln142_2_fu_2484_p1;
wire   [18:0] pos_3_fu_2488_p2;
wire   [16:0] lshr_ln4_fu_2499_p4;
wire   [18:0] trunc_ln135_fu_2514_p1;
wire   [1:0] trunc_ln135_2_fu_2518_p1;
wire   [18:0] pos_2_fu_2522_p2;
wire   [16:0] lshr_ln3_fu_2533_p4;
wire   [33:0] zext_ln132_1_fu_2548_p1;
wire  signed [33:0] sext_ln132_fu_2552_p1;
wire   [18:0] trunc_ln132_fu_2555_p1;
wire   [33:0] add_ln132_fu_2559_p2;
wire   [18:0] add_ln132_1_fu_2565_p2;
wire   [18:0] sub_ln132_fu_2578_p2;
wire   [16:0] trunc_ln132_2_fu_2584_p4;
wire   [0:0] tmp_7_fu_2570_p3;
wire   [16:0] sub_ln132_1_fu_2594_p2;
wire   [16:0] trunc_ln132_3_fu_2600_p4;
wire   [16:0] select_ln132_fu_2610_p3;
wire   [18:0] trunc_ln125_fu_2623_p1;
wire   [1:0] trunc_ln125_2_fu_2627_p1;
wire   [18:0] pos_1_fu_2631_p2;
wire   [16:0] lshr_ln2_fu_2642_p4;
wire   [18:0] trunc_ln118_fu_2657_p1;
wire   [1:0] trunc_ln118_2_fu_2661_p1;
wire   [18:0] pos_fu_2665_p2;
wire   [16:0] lshr_ln1_fu_2676_p4;
reg   [18:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_condition_480;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 p_pc = 32'd0;
#0 p_error = 1'd0;
#0 ap_CS_fsm = 19'd1;
end

processor_xreg_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
xreg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(xreg_address0),
    .ce0(xreg_ce0),
    .we0(xreg_we0),
    .d0(xreg_d0),
    .q0(xreg_q0),
    .address1(xreg_address1),
    .ce1(xreg_ce1),
    .we1(xreg_we1),
    .d1(xreg_d1),
    .q1(xreg_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        p_pc <= 32'd0;
    end else begin
        if (((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2))) begin
            p_pc <= add_ln63_fu_1613_p2;
        end else if (((1'b1 == ap_CS_fsm_state11) & ((((((((((funct3_reg_2748 == 3'd7) & (icmp_ln104_reg_3181 == 1'd1) & (o_pcode_reg_2744 == 7'd99)) | ((funct3_reg_2748 == 3'd6) & (icmp_ln98_reg_3185 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd5) & (icmp_ln92_reg_3189 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd4) & (icmp_ln86_reg_3193 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd3) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd2) & (o_pcode_reg_2744 == 7'd99))) | (~(funct3_reg_2748 == 3'd7) & ~(funct3_reg_2748 == 3'd1) & ~(funct3_reg_2748 == 3'd4) & ~(funct3_reg_2748 == 3'd5) & ~(funct3_reg_2748 == 3'd6) & (icmp_ln74_reg_3201 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd1) & (icmp_ln80_reg_3197 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | (~(o_pcode_reg_2744 == 7'd111) & ~(o_pcode_reg_2744 == 7'd99) & ~(o_pcode_reg_2744 == 7'd103))))) begin
            p_pc <= grp_fu_964_p2;
        end else if (((1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd103))) begin
            p_pc <= grp_fu_983_p2;
        end else if ((((grp_fu_971_p2 == 1'd0) & (funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state18)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_999_p2 == 1'd1)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_999_p2 == 1'd0)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_977_p2 == 1'd1)) | ((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_977_p2 == 1'd0)) | ((grp_fu_971_p2 == 1'd1) & (funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state18)))) begin
            p_pc <= grp_fu_995_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ((((((((((funct3_reg_2748 == 3'd7) & (icmp_ln104_reg_3181 == 1'd1) & (o_pcode_reg_2744 == 7'd99)) | ((funct3_reg_2748 == 3'd6) & (icmp_ln98_reg_3185 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd5) & (icmp_ln92_reg_3189 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd4) & (icmp_ln86_reg_3193 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd3) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd2) & (o_pcode_reg_2744 == 7'd99))) | (~(funct3_reg_2748 == 3'd7) & ~(funct3_reg_2748 == 3'd1) & ~(funct3_reg_2748 == 3'd4) & ~(funct3_reg_2748 == 3'd5) & ~(funct3_reg_2748 == 3'd6) & (icmp_ln74_reg_3201 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd1) & (icmp_ln80_reg_3197 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | (~(o_pcode_reg_2744 == 7'd111) & ~(o_pcode_reg_2744 == 7'd99) & ~(o_pcode_reg_2744 == 7'd103))))) begin
        p_0_0_03388_reg_930 <= grp_fu_964_p2;
    end else if ((((grp_fu_971_p2 == 1'd0) & (funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state18)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_999_p2 == 1'd1)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_999_p2 == 1'd0)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_977_p2 == 1'd1)) | ((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state18) & (grp_fu_977_p2 == 1'd0)) | ((grp_fu_971_p2 == 1'd1) & (funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state18)))) begin
        p_0_0_03388_reg_930 <= grp_fu_995_p2;
    end else if (((1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd103))) begin
        p_0_0_03388_reg_930 <= grp_fu_983_p2;
    end else if (((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2))) begin
        p_0_0_03388_reg_930 <= add_ln63_fu_1613_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        add_ln118_1_reg_3171 <= add_ln118_1_fu_2670_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        add_ln125_1_reg_3161 <= add_ln125_1_fu_2636_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state17))) begin
        add_ln135_1_reg_3146 <= add_ln135_1_fu_2527_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state17))) begin
        add_ln142_1_reg_3136 <= add_ln142_1_fu_2493_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        funct12_reg_2756 <= {{memory_q0[31:20]}};
        funct3_reg_2748 <= {{memory_q0[14:12]}};
        funct7_reg_2752 <= {{memory_q0[31:25]}};
        icmp_ln210_reg_2844 <= icmp_ln210_fu_1251_p2;
        imm_S_cast_reg_2838 <= {{memory_q0[8:7]}};
        imm_S_reg_2827 <= imm_S_fu_1210_p5;
        o_pcode_reg_2744 <= o_pcode_fu_1038_p1;
        rd_reg_2794 <= {{memory_q0[11:7]}};
        rs1_reg_2780 <= {{memory_q0[19:15]}};
        rs2_reg_2785 <= {{memory_q0[24:20]}};
        sext_ln38_1_reg_2771 <= sext_ln38_1_fu_1076_p1;
        sext_ln38_reg_2761 <= sext_ln38_fu_1072_p1;
        sext_ln42_reg_2822[31 : 1] <= sext_ln42_fu_1160_p1[31 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln104_reg_3181 <= grp_fu_971_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln74_reg_3201 <= grp_fu_999_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln80_reg_3197 <= grp_fu_999_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln86_reg_3193 <= grp_fu_977_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln92_reg_3189 <= grp_fu_977_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state18))) begin
        icmp_ln98_reg_3185 <= grp_fu_971_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        memory_addr_6_reg_3126 <= zext_ln160_fu_2471_p1;
        select_ln158_reg_3121 <= select_ln158_fu_2463_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        memory_addr_7_reg_3111 <= zext_ln168_fu_2339_p1;
        select_ln166_reg_3106 <= select_ln166_fu_2331_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | (~(o_pcode_fu_1038_p1 == 7'd15) & ~(o_pcode_fu_1038_p1 == 7'd115) & ~(o_pcode_fu_1038_p1 == 7'd3) & ~(o_pcode_fu_1038_p1 == 7'd55) & ~(o_pcode_fu_1038_p1 == 7'd23) & ~(o_pcode_fu_1038_p1 == 7'd103) & ~(o_pcode_fu_1038_p1 == 7'd111) & ~(o_pcode_fu_1038_p1 == 7'd99) & ~(o_pcode_fu_1038_p1 == 7'd35) & ~(o_pcode_fu_1038_p1 == 7'd19) & ~(o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(funct3_fu_1042_p4 == 3'd0) & ~(funct3_fu_1042_p4 == 3'd1) & ~(funct3_fu_1042_p4 == 3'd4) & ~(funct3_fu_1042_p4 == 3'd5) & ~(funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | (~(funct3_fu_1042_p4 == 3'd0) & ~(funct3_fu_1042_p4 == 3'd1) & ~(funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 
    == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | (~(funct7_fu_1052_p4 == 7'd0) & ~(funct7_fu_1052_p4 == 7'd32) & (funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1052_p4 == 7'd0) & ~(funct7_fu_1052_p4 == 7'd32) & (funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | (~(funct7_fu_1052_p4 == 7'd0) & ~(funct7_fu_1052_p4 == 7'd32) & (funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd15) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln336_fu_1257_p2 == 1'd0) & (o_pcode_fu_1038_p1 == 7'd115) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd99)) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd99)))) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | ((funct3_fu_1042_p4 
    == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd0)))) begin
        p_error <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_pc_load_reg_2731 <= p_pc;
    end
end

always @ (posedge ap_clk) begin
    if ((((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_1005 <= {{memory_q0[21:20]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((1'b1 == ap_condition_480)) begin
            ap_phi_mux_p_0_0_03388_phi_fu_933_p18 = grp_fu_964_p2;
        end else if ((o_pcode_reg_2744 == 7'd103)) begin
            ap_phi_mux_p_0_0_03388_phi_fu_933_p18 = grp_fu_983_p2;
        end else begin
            ap_phi_mux_p_0_0_03388_phi_fu_933_p18 = p_0_0_03388_reg_930;
        end
    end else begin
        ap_phi_mux_p_0_0_03388_phi_fu_933_p18 = p_0_0_03388_reg_930;
    end
end

always @ (*) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        memory_address0 = zext_ln119_fu_2686_p1;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        memory_address0 = zext_ln126_fu_2652_p1;
    end else if (((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state17))) begin
        memory_address0 = zext_ln132_3_fu_2618_p1;
    end else if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state17))) begin
        memory_address0 = zext_ln136_fu_2543_p1;
    end else if (((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state17))) begin
        memory_address0 = zext_ln143_fu_2509_p1;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        memory_address0 = zext_ln160_fu_2471_p1;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        memory_address0 = zext_ln168_fu_2339_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        memory_address0 = zext_ln173_3_fu_2211_p1;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35))) begin
        memory_address0 = memory_addr_6_reg_3126;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35))) begin
        memory_address0 = memory_addr_7_reg_3111;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        memory_address0 = zext_ln33_fu_1033_p1;
    end else begin
        memory_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state1) | ((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state17)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state17)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state17)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state17)) | ((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state17)))) begin
        memory_ce0 = 1'b1;
    end else begin
        memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        memory_d0 = xreg_q0;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35))) begin
        memory_d0 = or_ln160_fu_1885_p2;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35))) begin
        memory_d0 = or_ln168_fu_1827_p2;
    end else begin
        memory_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd35)))) begin
        memory_we0 = 1'b1;
    end else begin
        memory_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        xreg_address0 = zext_ln68_fu_2727_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd0))) begin
        xreg_address0 = zext_ln220_2_fu_2133_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd32))) begin
        xreg_address0 = zext_ln223_2_fu_2119_p1;
    end else if (((o_pcode_fu_1038_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln56_fu_1635_p1;
    end else if (((o_pcode_fu_1038_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln59_fu_1630_p1;
    end else if (((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln62_fu_1608_p1;
    end else if (((o_pcode_fu_1038_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln67_fu_1603_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln74_1_fu_1592_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln80_1_fu_1582_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln86_1_fu_1572_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln92_1_fu_1562_p1;
    end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln98_1_fu_1552_p1;
    end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln104_1_fu_1542_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln118_fu_1526_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln125_fu_1521_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln132_fu_1516_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln135_fu_1511_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln142_fu_1506_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln157_fu_1495_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln165_fu_1490_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln173_fu_1480_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0))) begin
        xreg_address0 = zext_ln220_fu_1469_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32))) begin
        xreg_address0 = zext_ln223_fu_1464_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln184_fu_1459_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln187_fu_1454_p1;
    end else if (((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln194_fu_1449_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln201_fu_1444_p1;
    end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln204_fu_1439_p1;
    end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address0 = zext_ln207_fu_1434_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln211_fu_1429_p1;
    end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln319_1_fu_1418_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0))) begin
        xreg_address0 = zext_ln243_1_fu_1396_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32))) begin
        xreg_address0 = zext_ln247_1_fu_1386_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln257_fu_1371_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln265_1_fu_1360_p1;
    end else if (((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln277_1_fu_1344_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln289_1_fu_1328_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0))) begin
        xreg_address0 = zext_ln298_fu_1301_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32))) begin
        xreg_address0 = zext_ln301_1_fu_1296_p1;
    end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address0 = zext_ln311_1_fu_1286_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        xreg_address0 = 5'd0;
    end else begin
        xreg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln161_fu_2476_p1;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        xreg_address1 = zext_ln169_fu_2344_p1;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln184_1_fu_2105_p1;
    end else if (((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln188_fu_2096_p1;
    end else if (((funct3_reg_2748 == 3'd3) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln195_fu_2082_p1;
    end else if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln201_1_fu_2073_p1;
    end else if (((funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln204_1_fu_2063_p1;
    end else if (((funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_address1 = zext_ln207_1_fu_2053_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        xreg_address1 = zext_ln211_2_fu_2043_p1;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_address1 = zext_ln121_fu_2012_p1;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_address1 = zext_ln128_fu_1982_p1;
    end else if (((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_address1 = zext_ln132_2_fu_1952_p1;
    end else if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_address1 = zext_ln138_1_fu_1948_p1;
    end else if (((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_address1 = zext_ln145_1_fu_1918_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        xreg_address1 = zext_ln319_2_fu_1772_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd0))) begin
        xreg_address1 = zext_ln243_2_fu_1761_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd32))) begin
        xreg_address1 = zext_ln247_2_fu_1750_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        xreg_address1 = zext_ln257_2_fu_1739_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xreg_address1 = zext_ln266_fu_1715_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        xreg_address1 = zext_ln278_fu_1706_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        xreg_address1 = zext_ln289_2_fu_1702_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd0))) begin
        xreg_address1 = zext_ln298_2_fu_1691_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd32))) begin
        xreg_address1 = zext_ln301_2_fu_1672_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        xreg_address1 = zext_ln311_2_fu_1653_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln74_fu_1587_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln80_fu_1577_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln86_fu_1567_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln92_fu_1557_p1;
    end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln98_fu_1547_p1;
    end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln104_fu_1537_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_address1 = zext_ln173_1_fu_1485_p1;
    end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln319_fu_1413_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0))) begin
        xreg_address1 = zext_ln243_fu_1391_p1;
    end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32))) begin
        xreg_address1 = zext_ln247_fu_1381_p1;
    end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln257_1_fu_1376_p1;
    end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln265_fu_1355_p1;
    end else if (((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln277_fu_1339_p1;
    end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln289_fu_1323_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0))) begin
        xreg_address1 = zext_ln298_1_fu_1306_p1;
    end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32))) begin
        xreg_address1 = zext_ln301_fu_1291_p1;
    end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1))) begin
        xreg_address1 = zext_ln311_fu_1281_p1;
    end else begin
        xreg_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state1) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 
    == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32)) | ((funct3_fu_1042_p4 
    == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32)) | ((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd32)) | ((o_pcode_fu_1038_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 
    == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)))) begin
        xreg_ce0 = 1'b1;
    end else begin
        xreg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0)) | ((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 
    == 1'd1)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd0)) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (funct7_fu_1052_p4 == 7'd32)) | ((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd32)) | ((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd32)) | ((funct3_reg_2748 == 3'd3) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 
    == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln210_fu_1251_p2 == 1'd1)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state16)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 
    == 7'd3)) | ((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state13)))) begin
        xreg_ce1 = 1'b1;
    end else begin
        xreg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd0))) begin
        xreg_d0 = lshr_ln220_fu_2126_p2;
    end else if (((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd32))) begin
        xreg_d0 = ashr_ln223_fu_2112_p2;
    end else if (((o_pcode_fu_1038_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_d0 = imm_U_fu_1242_p3;
    end else if (((o_pcode_fu_1038_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2))) begin
        xreg_d0 = add_ln59_fu_1624_p2;
    end else if ((((o_pcode_fu_1038_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)))) begin
        xreg_d0 = grp_fu_964_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        xreg_d0 = 32'd0;
    end else begin
        xreg_d0 = 'bx;
    end
end

always @ (*) begin
    if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = grp_fu_983_p2;
    end else if (((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = zext_ln187_1_fu_2100_p1;
    end else if (((funct3_reg_2748 == 3'd3) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = zext_ln194_1_fu_2086_p1;
    end else if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = xor_ln201_fu_2067_p2;
    end else if (((funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = or_ln204_fu_2057_p2;
    end else if (((funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state13))) begin
        xreg_d1 = and_ln207_fu_2047_p2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        xreg_d1 = shl_ln211_fu_2036_p2;
    end else if (((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_d1 = sext_ln121_fu_2007_p1;
    end else if (((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_d1 = sext_ln128_fu_1977_p1;
    end else if (((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_d1 = memory_q0;
    end else if (((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_d1 = zext_ln138_fu_1943_p1;
    end else if (((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3))) begin
        xreg_d1 = zext_ln145_fu_1913_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        xreg_d1 = and_ln319_fu_1765_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd0))) begin
        xreg_d1 = add_ln243_fu_1754_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd32))) begin
        xreg_d1 = sub_ln247_fu_1743_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        xreg_d1 = shl_ln257_fu_1732_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xreg_d1 = zext_ln265_2_fu_1719_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        xreg_d1 = zext_ln277_2_fu_1710_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        xreg_d1 = xor_ln289_fu_1695_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd0))) begin
        xreg_d1 = lshr_ln298_fu_1684_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd32))) begin
        xreg_d1 = ashr_ln301_fu_1665_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        xreg_d1 = or_ln311_fu_1646_p2;
    end else begin
        xreg_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | ((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state14) & (funct7_reg_2752 == 7'd32)) | ((o_pcode_fu_1038_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state2)) | ((o_pcode_fu_1038_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state2)))) begin
        xreg_we0 = 1'b1;
    end else begin
        xreg_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((funct3_reg_2748 == 3'd7) & (1'b1 == ap_CS_fsm_state13)) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state9) & (funct7_reg_2752 == 7'd32)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln210_reg_2844 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd0)) | ((1'b1 == ap_CS_fsm_state4) & (funct7_reg_2752 == 7'd32)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln210_reg_2844 == 1'd1)) | ((funct3_reg_2748 == 3'd3) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd2) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd0) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 
    == 3'd0) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd1) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state13)) | ((funct3_reg_2748 == 3'd4) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd5) & (1'b1 == ap_CS_fsm_state11) & (o_pcode_reg_2744 == 7'd3)) | ((funct3_reg_2748 == 3'd6) & (1'b1 == ap_CS_fsm_state13)))) begin
        xreg_we1 = 1'b1;
    end else begin
        xreg_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if ((~(funct3_fu_1042_p4 == 3'd2) & ~(funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd99) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if ((~(funct3_fu_1042_p4 == 3'd7) & ~(funct3_fu_1042_p4 == 3'd3) & ~(funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd3) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((1'b1 == ap_CS_fsm_state2) & (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd35)) | ((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd35))))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd35) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if ((~(funct3_fu_1042_p4 == 3'd1) & ~(funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd19) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((funct3_fu_1042_p4 == 3'd0) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((funct3_fu_1042_p4 == 3'd1) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state2) & ((((((((((((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd35)) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd35))) | ((funct3_fu_1042_p4 == 3'd5) & (o_pcode_fu_1038_p1 == 7'd35))) | ((funct3_fu_1042_p4 == 3'd4) & (o_pcode_fu_1038_p1 == 7'd35))) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd35))) | ((funct3_fu_1042_p4 == 3'd7) & (o_pcode_fu_1038_p1 == 7'd3))) | ((funct3_fu_1042_p4 == 3'd6) & (o_pcode_fu_1038_p1 == 7'd3))) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd3))) | ((funct3_fu_1042_p4 == 3'd3) & (o_pcode_fu_1038_p1 == 7'd99))) | ((funct3_fu_1042_p4 == 3'd2) & (o_pcode_fu_1038_p1 == 7'd99))) | (~(o_pcode_fu_1038_p1 == 7'd3) & ~(o_pcode_fu_1038_p1 == 7'd103) & ~(o_pcode_fu_1038_p1 == 7'd99) & ~(o_pcode_fu_1038_p1 == 7'd35) & ~(o_pcode_fu_1038_p1 == 7'd19) & ~(o_pcode_fu_1038_p1 == 7'd51))))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_1_fu_2670_p2 = (trunc_ln118_2_fu_2661_p1 + reg_1005);

assign add_ln125_1_fu_2636_p2 = (trunc_ln125_2_fu_2627_p1 + reg_1005);

assign add_ln132_1_fu_2565_p2 = ($signed(trunc_ln132_fu_2555_p1) + $signed(sext_ln38_1_reg_2771));

assign add_ln132_fu_2559_p2 = ($signed(zext_ln132_1_fu_2548_p1) + $signed(sext_ln132_fu_2552_p1));

assign add_ln135_1_fu_2527_p2 = (trunc_ln135_2_fu_2518_p1 + reg_1005);

assign add_ln142_1_fu_2493_p2 = (trunc_ln142_2_fu_2484_p1 + reg_1005);

assign add_ln157_1_fu_2381_p2 = (trunc_ln157_4_fu_2362_p1 + trunc_ln157_3_fu_2359_p1);

assign add_ln157_2_fu_2366_p2 = (trunc_ln157_fu_2348_p1 + imm_S_cast_reg_2838);

assign add_ln157_fu_2371_p2 = ($signed(zext_ln157_1_fu_2352_p1) + $signed(sext_ln157_fu_2356_p1));

assign add_ln165_1_fu_2249_p2 = (trunc_ln165_4_fu_2230_p1 + trunc_ln165_3_fu_2227_p1);

assign add_ln165_2_fu_2234_p2 = (trunc_ln165_fu_2216_p1 + imm_S_cast_reg_2838);

assign add_ln165_fu_2239_p2 = ($signed(zext_ln165_1_fu_2220_p1) + $signed(sext_ln165_fu_2224_p1));

assign add_ln173_1_fu_2157_p2 = (trunc_ln173_1_fu_2147_p1 + trunc_ln173_fu_2144_p1);

assign add_ln173_fu_2151_p2 = ($signed(zext_ln173_2_fu_2137_p1) + $signed(sext_ln173_fu_2141_p1));

assign add_ln243_fu_1754_p2 = (xreg_q0 + xreg_q1);

assign add_ln59_fu_1624_p2 = (p_pc_load_reg_2731 + imm_U_fu_1242_p3);

assign add_ln63_fu_1613_p2 = ($signed(p_pc_load_reg_2731) + $signed(sext_ln46_fu_1206_p1));

assign and_ln160_fu_1857_p2 = (xor_ln160_fu_1851_p2 & memory_q0);

assign and_ln168_fu_1799_p2 = (xor_ln168_fu_1793_p2 & memory_q0);

assign and_ln207_fu_2047_p2 = (xreg_q0 & sext_ln38_reg_2761);

assign and_ln319_fu_1765_p2 = (xreg_q1 & xreg_q0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_480 = ((((((((((funct3_reg_2748 == 3'd7) & (icmp_ln104_reg_3181 == 1'd1) & (o_pcode_reg_2744 == 7'd99)) | ((funct3_reg_2748 == 3'd6) & (icmp_ln98_reg_3185 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd5) & (icmp_ln92_reg_3189 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd4) & (icmp_ln86_reg_3193 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd3) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd2) & (o_pcode_reg_2744 == 7'd99))) | (~(funct3_reg_2748 == 3'd7) & ~(funct3_reg_2748 == 3'd1) & ~(funct3_reg_2748 == 3'd4) & ~(funct3_reg_2748 == 3'd5) & ~(funct3_reg_2748 == 3'd6) & (icmp_ln74_reg_3201 == 1'd0) & (o_pcode_reg_2744 == 7'd99))) | ((funct3_reg_2748 == 3'd1) & (icmp_ln80_reg_3197 == 1'd1) & (o_pcode_reg_2744 == 7'd99))) | (~(o_pcode_reg_2744 == 7'd111) & ~(o_pcode_reg_2744 == 7'd99) & ~(o_pcode_reg_2744 == 7'd103)));
end

assign ashr_ln223_fu_2112_p2 = $signed(xreg_q0) >>> zext_ln223_1_fu_2109_p1;

assign ashr_ln301_fu_1665_p2 = $signed(xreg_q1) >>> zext_ln301_3_fu_1661_p1;

assign error = p_error;

assign funct12_fu_1062_p4 = {{memory_q0[31:20]}};

assign funct3_fu_1042_p4 = {{memory_q0[14:12]}};

assign funct7_fu_1052_p4 = {{memory_q0[31:25]}};

assign grp_fu_964_p2 = (p_pc_load_reg_2731 + 32'd4);

assign grp_fu_971_p2 = ((xreg_q1 < xreg_q0) ? 1'b1 : 1'b0);

assign grp_fu_977_p2 = (($signed(xreg_q1) < $signed(xreg_q0)) ? 1'b1 : 1'b0);

assign grp_fu_983_p2 = ($signed(xreg_q0) + $signed(sext_ln38_reg_2761));

assign grp_fu_990_p2 = ($signed(xreg_q0) + $signed(imm_S_reg_2827));

assign grp_fu_995_p2 = ($signed(p_pc_load_reg_2731) + $signed(sext_ln42_reg_2822));

assign grp_fu_999_p2 = ((xreg_q1 == xreg_q0) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_2091_p2 = (($signed(xreg_q0) < $signed(sext_ln38_reg_2761)) ? 1'b1 : 1'b0);

assign icmp_ln194_fu_2077_p2 = ((xreg_q0 < sext_ln38_reg_2761) ? 1'b1 : 1'b0);

assign icmp_ln210_fu_1251_p2 = ((funct7_fu_1052_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln336_fu_1257_p2 = ((funct12_fu_1062_p4 == 12'd0) ? 1'b1 : 1'b0);

assign imm_B_fu_1146_p6 = {{{{{tmp_3_fu_1138_p3}, {tmp_2_fu_1130_p3}}, {tmp_1_fu_1120_p4}}, {tmp_fu_1110_p4}}, {1'd0}};

assign imm_J_fu_1192_p6 = {{{{{tmp_3_fu_1138_p3}, {tmp_6_fu_1182_p4}}, {tmp_5_fu_1174_p3}}, {tmp_4_fu_1164_p4}}, {1'd0}};

assign imm_S_fu_1210_p5 = {{sext_ln38_fu_1072_p1[31:5]}, {rd_fu_1100_p4}};

assign imm_U_fu_1242_p3 = {{tmp_8_fu_1232_p4}, {12'd0}};

assign lshr_ln120_fu_1997_p2 = memory_q0 >> zext_ln120_fu_1993_p1;

assign lshr_ln127_fu_1967_p2 = memory_q0 >> zext_ln127_fu_1963_p1;

assign lshr_ln137_fu_1933_p2 = memory_q0 >> zext_ln137_fu_1929_p1;

assign lshr_ln144_fu_1903_p2 = memory_q0 >> zext_ln144_fu_1899_p1;

assign lshr_ln1_fu_2676_p4 = {{pos_fu_2665_p2[18:2]}};

assign lshr_ln220_fu_2126_p2 = xreg_q0 >> zext_ln220_1_fu_2123_p1;

assign lshr_ln298_fu_1684_p2 = xreg_q0 >> zext_ln298_3_fu_1680_p1;

assign lshr_ln2_fu_2642_p4 = {{pos_1_fu_2631_p2[18:2]}};

assign lshr_ln3_fu_2533_p4 = {{pos_2_fu_2522_p2[18:2]}};

assign lshr_ln4_fu_2499_p4 = {{pos_3_fu_2488_p2[18:2]}};

assign lshr_ln_fu_1023_p4 = {{p_pc[18:2]}};

assign mask_1_fu_1787_p2 = 32'd65535 << sext_ln166_fu_1783_p1;

assign mask_fu_1845_p2 = 32'd255 << sext_ln158_fu_1841_p1;

assign o_pcode_fu_1038_p1 = memory_q0[6:0];

assign offset_1_fu_1776_p3 = {{select_ln166_reg_3106}, {3'd0}};

assign offset_fu_1834_p3 = {{select_ln158_reg_3121}, {3'd0}};

assign or_ln160_fu_1885_p2 = (trunc_ln161_1_fu_1881_p1 | and_ln160_fu_1857_p2);

assign or_ln168_fu_1827_p2 = (trunc_ln169_1_fu_1823_p1 | and_ln168_fu_1799_p2);

assign or_ln204_fu_2057_p2 = (xreg_q0 | sext_ln38_reg_2761);

assign or_ln311_fu_1646_p2 = (xreg_q1 | xreg_q0);

assign p_and_t3_fu_2309_p3 = {{1'd0}, {sub_ln166_fu_2303_p2}};

assign p_and_t_fu_2441_p3 = {{1'd0}, {sub_ln158_fu_2435_p2}};

assign pc = ap_phi_mux_p_0_0_03388_phi_fu_933_p18;

assign pos_1_fu_2631_p2 = ($signed(trunc_ln125_fu_2623_p1) + $signed(sext_ln38_1_reg_2771));

assign pos_2_fu_2522_p2 = ($signed(trunc_ln135_fu_2514_p1) + $signed(sext_ln38_1_reg_2771));

assign pos_3_fu_2488_p2 = ($signed(trunc_ln142_fu_2480_p1) + $signed(sext_ln38_1_reg_2771));

assign pos_4_fu_2427_p3 = ((tmp_9_fu_2387_p3[0:0] == 1'b1) ? sub_ln157_1_fu_2411_p2 : trunc_ln157_2_fu_2417_p4);

assign pos_5_fu_2295_p3 = ((tmp_10_fu_2255_p3[0:0] == 1'b1) ? sub_ln165_1_fu_2279_p2 : trunc_ln165_2_fu_2285_p4);

assign pos_fu_2665_p2 = ($signed(trunc_ln118_fu_2657_p1) + $signed(sext_ln38_1_reg_2771));

assign rd_fu_1100_p4 = {{memory_q0[11:7]}};

assign result_1_fu_1973_p1 = lshr_ln127_fu_1967_p2[15:0];

assign result_2_fu_1939_p1 = lshr_ln137_fu_1933_p2[7:0];

assign result_3_fu_1909_p1 = lshr_ln144_fu_1903_p2[15:0];

assign result_fu_2003_p1 = lshr_ln120_fu_1997_p2[7:0];

assign rs1_fu_1080_p4 = {{memory_q0[19:15]}};

assign rs2_fu_1090_p4 = {{memory_q0[24:20]}};

assign select_ln132_fu_2610_p3 = ((tmp_7_fu_2570_p3[0:0] == 1'b1) ? sub_ln132_1_fu_2594_p2 : trunc_ln132_3_fu_2600_p4);

assign select_ln158_fu_2463_p3 = ((tmp_9_fu_2387_p3[0:0] == 1'b1) ? sub_ln158_1_fu_2449_p2 : tmp_s_fu_2455_p3);

assign select_ln166_fu_2331_p3 = ((tmp_10_fu_2255_p3[0:0] == 1'b1) ? sub_ln166_1_fu_2317_p2 : tmp_11_fu_2323_p3);

assign select_ln173_fu_2203_p3 = ((tmp_12_fu_2163_p3[0:0] == 1'b1) ? sub_ln173_1_fu_2187_p2 : trunc_ln173_4_fu_2193_p4);

assign sext_ln121_fu_2007_p1 = $signed(result_fu_2003_p1);

assign sext_ln128_fu_1977_p1 = $signed(result_1_fu_1973_p1);

assign sext_ln132_fu_2552_p1 = funct12_reg_2756;

assign sext_ln157_fu_2356_p1 = imm_S_reg_2827;

assign sext_ln158_fu_1841_p1 = $signed(offset_fu_1834_p3);

assign sext_ln165_fu_2224_p1 = imm_S_reg_2827;

assign sext_ln166_fu_1783_p1 = $signed(offset_1_fu_1776_p3);

assign sext_ln173_fu_2141_p1 = imm_S_reg_2827;

assign sext_ln38_1_fu_1076_p1 = funct12_fu_1062_p4;

assign sext_ln38_fu_1072_p1 = funct12_fu_1062_p4;

assign sext_ln42_fu_1160_p1 = $signed(imm_B_fu_1146_p6);

assign sext_ln46_fu_1206_p1 = $signed(imm_J_fu_1192_p6);

assign shl_ln161_fu_1875_p2 = zext_ln161_1_fu_1867_p1 << zext_ln161_2_fu_1871_p1;

assign shl_ln169_fu_1817_p2 = zext_ln169_1_fu_1809_p1 << zext_ln169_2_fu_1813_p1;

assign shl_ln1_fu_1956_p3 = {{add_ln125_1_reg_3161}, {3'd0}};

assign shl_ln211_fu_2036_p2 = xreg_q0 << zext_ln211_1_fu_2033_p1;

assign shl_ln257_fu_1732_p2 = xreg_q0 << zext_ln257_3_fu_1728_p1;

assign shl_ln2_fu_1922_p3 = {{add_ln135_1_reg_3146}, {3'd0}};

assign shl_ln3_fu_1892_p3 = {{add_ln142_1_reg_3136}, {3'd0}};

assign shl_ln_fu_1986_p3 = {{add_ln118_1_reg_3171}, {3'd0}};

assign sub_ln132_1_fu_2594_p2 = (17'd0 - trunc_ln132_2_fu_2584_p4);

assign sub_ln132_fu_2578_p2 = (19'd0 - add_ln132_1_fu_2565_p2);

assign sub_ln157_1_fu_2411_p2 = (17'd0 - trunc_ln157_1_fu_2401_p4);

assign sub_ln157_fu_2395_p2 = (19'd0 - add_ln157_1_fu_2381_p2);

assign sub_ln158_1_fu_2449_p2 = (3'd0 - p_and_t_fu_2441_p3);

assign sub_ln158_fu_2435_p2 = (2'd0 - trunc_ln157_5_fu_2377_p1);

assign sub_ln165_1_fu_2279_p2 = (17'd0 - trunc_ln165_1_fu_2269_p4);

assign sub_ln165_fu_2263_p2 = (19'd0 - add_ln165_1_fu_2249_p2);

assign sub_ln166_1_fu_2317_p2 = (3'd0 - p_and_t3_fu_2309_p3);

assign sub_ln166_fu_2303_p2 = (2'd0 - trunc_ln165_5_fu_2245_p1);

assign sub_ln173_1_fu_2187_p2 = (17'd0 - trunc_ln173_3_fu_2177_p4);

assign sub_ln173_fu_2171_p2 = (19'd0 - add_ln173_1_fu_2157_p2);

assign sub_ln247_fu_1743_p2 = (xreg_q1 - xreg_q0);

assign tmp_10_fu_2255_p3 = add_ln165_fu_2239_p2[32'd33];

assign tmp_11_fu_2323_p3 = {{1'd0}, {add_ln165_2_fu_2234_p2}};

assign tmp_12_fu_2163_p3 = add_ln173_fu_2151_p2[32'd33];

assign tmp_1_fu_1120_p4 = {{memory_q0[30:25]}};

assign tmp_2_fu_1130_p3 = memory_q0[32'd7];

assign tmp_3_fu_1138_p3 = memory_q0[32'd31];

assign tmp_4_fu_1164_p4 = {{memory_q0[30:21]}};

assign tmp_5_fu_1174_p3 = memory_q0[32'd20];

assign tmp_6_fu_1182_p4 = {{memory_q0[19:12]}};

assign tmp_7_fu_2570_p3 = add_ln132_fu_2559_p2[32'd33];

assign tmp_8_fu_1232_p4 = {{memory_q0[31:12]}};

assign tmp_9_fu_2387_p3 = add_ln157_fu_2371_p2[32'd33];

assign tmp_fu_1110_p4 = {{memory_q0[11:8]}};

assign tmp_s_fu_2455_p3 = {{1'd0}, {add_ln157_2_fu_2366_p2}};

assign trunc_ln118_2_fu_2661_p1 = xreg_q0[1:0];

assign trunc_ln118_fu_2657_p1 = xreg_q0[18:0];

assign trunc_ln125_2_fu_2627_p1 = xreg_q0[1:0];

assign trunc_ln125_fu_2623_p1 = xreg_q0[18:0];

assign trunc_ln132_2_fu_2584_p4 = {{sub_ln132_fu_2578_p2[18:2]}};

assign trunc_ln132_3_fu_2600_p4 = {{add_ln132_1_fu_2565_p2[18:2]}};

assign trunc_ln132_fu_2555_p1 = xreg_q0[18:0];

assign trunc_ln135_2_fu_2518_p1 = xreg_q0[1:0];

assign trunc_ln135_fu_2514_p1 = xreg_q0[18:0];

assign trunc_ln142_2_fu_2484_p1 = xreg_q0[1:0];

assign trunc_ln142_fu_2480_p1 = xreg_q0[18:0];

assign trunc_ln157_1_fu_2401_p4 = {{sub_ln157_fu_2395_p2[18:2]}};

assign trunc_ln157_2_fu_2417_p4 = {{add_ln157_1_fu_2381_p2[18:2]}};

assign trunc_ln157_3_fu_2359_p1 = imm_S_reg_2827[18:0];

assign trunc_ln157_4_fu_2362_p1 = xreg_q0[18:0];

assign trunc_ln157_5_fu_2377_p1 = grp_fu_990_p2[1:0];

assign trunc_ln157_fu_2348_p1 = xreg_q0[1:0];

assign trunc_ln161_1_fu_1881_p1 = shl_ln161_fu_1875_p2[31:0];

assign trunc_ln161_fu_1863_p1 = xreg_q1[7:0];

assign trunc_ln165_1_fu_2269_p4 = {{sub_ln165_fu_2263_p2[18:2]}};

assign trunc_ln165_2_fu_2285_p4 = {{add_ln165_1_fu_2249_p2[18:2]}};

assign trunc_ln165_3_fu_2227_p1 = imm_S_reg_2827[18:0];

assign trunc_ln165_4_fu_2230_p1 = xreg_q0[18:0];

assign trunc_ln165_5_fu_2245_p1 = grp_fu_990_p2[1:0];

assign trunc_ln165_fu_2216_p1 = xreg_q0[1:0];

assign trunc_ln169_1_fu_1823_p1 = shl_ln169_fu_1817_p2[31:0];

assign trunc_ln169_fu_1805_p1 = xreg_q1[15:0];

assign trunc_ln173_1_fu_2147_p1 = xreg_q1[18:0];

assign trunc_ln173_3_fu_2177_p4 = {{sub_ln173_fu_2171_p2[18:2]}};

assign trunc_ln173_4_fu_2193_p4 = {{add_ln173_1_fu_2157_p2[18:2]}};

assign trunc_ln173_fu_2144_p1 = imm_S_reg_2827[18:0];

assign trunc_ln257_fu_1724_p1 = xreg_q1[4:0];

assign trunc_ln298_fu_1676_p1 = xreg_q1[4:0];

assign trunc_ln301_fu_1657_p1 = xreg_q0[4:0];

assign xor_ln160_fu_1851_p2 = (mask_fu_1845_p2 ^ 32'd4294967295);

assign xor_ln168_fu_1793_p2 = (mask_1_fu_1787_p2 ^ 32'd4294967295);

assign xor_ln201_fu_2067_p2 = (xreg_q0 ^ sext_ln38_reg_2761);

assign xor_ln289_fu_1695_p2 = (xreg_q1 ^ xreg_q0);

assign zext_ln104_1_fu_1542_p1 = rs2_fu_1090_p4;

assign zext_ln104_fu_1537_p1 = rs1_fu_1080_p4;

assign zext_ln118_fu_1526_p1 = rs1_fu_1080_p4;

assign zext_ln119_fu_2686_p1 = lshr_ln1_fu_2676_p4;

assign zext_ln120_fu_1993_p1 = shl_ln_fu_1986_p3;

assign zext_ln121_fu_2012_p1 = rd_reg_2794;

assign zext_ln125_fu_1521_p1 = rs1_fu_1080_p4;

assign zext_ln126_fu_2652_p1 = lshr_ln2_fu_2642_p4;

assign zext_ln127_fu_1963_p1 = shl_ln1_fu_1956_p3;

assign zext_ln128_fu_1982_p1 = rd_reg_2794;

assign zext_ln132_1_fu_2548_p1 = xreg_q0;

assign zext_ln132_2_fu_1952_p1 = rd_reg_2794;

assign zext_ln132_3_fu_2618_p1 = select_ln132_fu_2610_p3;

assign zext_ln132_fu_1516_p1 = rs1_fu_1080_p4;

assign zext_ln135_fu_1511_p1 = rs1_fu_1080_p4;

assign zext_ln136_fu_2543_p1 = lshr_ln3_fu_2533_p4;

assign zext_ln137_fu_1929_p1 = shl_ln2_fu_1922_p3;

assign zext_ln138_1_fu_1948_p1 = rd_reg_2794;

assign zext_ln138_fu_1943_p1 = result_2_fu_1939_p1;

assign zext_ln142_fu_1506_p1 = rs1_fu_1080_p4;

assign zext_ln143_fu_2509_p1 = lshr_ln4_fu_2499_p4;

assign zext_ln144_fu_1899_p1 = shl_ln3_fu_1892_p3;

assign zext_ln145_1_fu_1918_p1 = rd_reg_2794;

assign zext_ln145_fu_1913_p1 = result_3_fu_1909_p1;

assign zext_ln157_1_fu_2352_p1 = xreg_q0;

assign zext_ln157_fu_1495_p1 = rs1_fu_1080_p4;

assign zext_ln160_fu_2471_p1 = pos_4_fu_2427_p3;

assign zext_ln161_1_fu_1867_p1 = trunc_ln161_fu_1863_p1;

assign zext_ln161_2_fu_1871_p1 = $unsigned(sext_ln158_fu_1841_p1);

assign zext_ln161_fu_2476_p1 = rs2_reg_2785;

assign zext_ln165_1_fu_2220_p1 = xreg_q0;

assign zext_ln165_fu_1490_p1 = rs1_fu_1080_p4;

assign zext_ln168_fu_2339_p1 = pos_5_fu_2295_p3;

assign zext_ln169_1_fu_1809_p1 = trunc_ln169_fu_1805_p1;

assign zext_ln169_2_fu_1813_p1 = $unsigned(sext_ln166_fu_1783_p1);

assign zext_ln169_fu_2344_p1 = rs2_reg_2785;

assign zext_ln173_1_fu_1485_p1 = rs1_fu_1080_p4;

assign zext_ln173_2_fu_2137_p1 = xreg_q1;

assign zext_ln173_3_fu_2211_p1 = select_ln173_fu_2203_p3;

assign zext_ln173_fu_1480_p1 = rs2_fu_1090_p4;

assign zext_ln184_1_fu_2105_p1 = rd_reg_2794;

assign zext_ln184_fu_1459_p1 = rs1_fu_1080_p4;

assign zext_ln187_1_fu_2100_p1 = icmp_ln187_fu_2091_p2;

assign zext_ln187_fu_1454_p1 = rs1_fu_1080_p4;

assign zext_ln188_fu_2096_p1 = rd_reg_2794;

assign zext_ln194_1_fu_2086_p1 = icmp_ln194_fu_2077_p2;

assign zext_ln194_fu_1449_p1 = rs1_fu_1080_p4;

assign zext_ln195_fu_2082_p1 = rd_reg_2794;

assign zext_ln201_1_fu_2073_p1 = rd_reg_2794;

assign zext_ln201_fu_1444_p1 = rs1_fu_1080_p4;

assign zext_ln204_1_fu_2063_p1 = rd_reg_2794;

assign zext_ln204_fu_1439_p1 = rs1_fu_1080_p4;

assign zext_ln207_1_fu_2053_p1 = rd_reg_2794;

assign zext_ln207_fu_1434_p1 = rs1_fu_1080_p4;

assign zext_ln211_1_fu_2033_p1 = rs2_reg_2785;

assign zext_ln211_2_fu_2043_p1 = rd_reg_2794;

assign zext_ln211_fu_1429_p1 = rs1_fu_1080_p4;

assign zext_ln220_1_fu_2123_p1 = rs2_reg_2785;

assign zext_ln220_2_fu_2133_p1 = rd_reg_2794;

assign zext_ln220_fu_1469_p1 = rs1_fu_1080_p4;

assign zext_ln223_1_fu_2109_p1 = rs2_reg_2785;

assign zext_ln223_2_fu_2119_p1 = rd_reg_2794;

assign zext_ln223_fu_1464_p1 = rs1_fu_1080_p4;

assign zext_ln243_1_fu_1396_p1 = rs2_fu_1090_p4;

assign zext_ln243_2_fu_1761_p1 = rd_reg_2794;

assign zext_ln243_fu_1391_p1 = rs1_fu_1080_p4;

assign zext_ln247_1_fu_1386_p1 = rs2_fu_1090_p4;

assign zext_ln247_2_fu_1750_p1 = rd_reg_2794;

assign zext_ln247_fu_1381_p1 = rs1_fu_1080_p4;

assign zext_ln257_1_fu_1376_p1 = rs2_fu_1090_p4;

assign zext_ln257_2_fu_1739_p1 = rd_reg_2794;

assign zext_ln257_3_fu_1728_p1 = trunc_ln257_fu_1724_p1;

assign zext_ln257_fu_1371_p1 = rs1_fu_1080_p4;

assign zext_ln265_1_fu_1360_p1 = rs2_fu_1090_p4;

assign zext_ln265_2_fu_1719_p1 = grp_fu_977_p2;

assign zext_ln265_fu_1355_p1 = rs1_fu_1080_p4;

assign zext_ln266_fu_1715_p1 = rd_reg_2794;

assign zext_ln277_1_fu_1344_p1 = rs2_fu_1090_p4;

assign zext_ln277_2_fu_1710_p1 = grp_fu_971_p2;

assign zext_ln277_fu_1339_p1 = rs1_fu_1080_p4;

assign zext_ln278_fu_1706_p1 = rd_reg_2794;

assign zext_ln289_1_fu_1328_p1 = rs2_fu_1090_p4;

assign zext_ln289_2_fu_1702_p1 = rd_reg_2794;

assign zext_ln289_fu_1323_p1 = rs1_fu_1080_p4;

assign zext_ln298_1_fu_1306_p1 = rs2_fu_1090_p4;

assign zext_ln298_2_fu_1691_p1 = rd_reg_2794;

assign zext_ln298_3_fu_1680_p1 = trunc_ln298_fu_1676_p1;

assign zext_ln298_fu_1301_p1 = rs1_fu_1080_p4;

assign zext_ln301_1_fu_1296_p1 = rs2_fu_1090_p4;

assign zext_ln301_2_fu_1672_p1 = rd_reg_2794;

assign zext_ln301_3_fu_1661_p1 = trunc_ln301_fu_1657_p1;

assign zext_ln301_fu_1291_p1 = rs1_fu_1080_p4;

assign zext_ln311_1_fu_1286_p1 = rs2_fu_1090_p4;

assign zext_ln311_2_fu_1653_p1 = rd_reg_2794;

assign zext_ln311_fu_1281_p1 = rs1_fu_1080_p4;

assign zext_ln319_1_fu_1418_p1 = rs2_fu_1090_p4;

assign zext_ln319_2_fu_1772_p1 = rd_reg_2794;

assign zext_ln319_fu_1413_p1 = rs1_fu_1080_p4;

assign zext_ln33_fu_1033_p1 = lshr_ln_fu_1023_p4;

assign zext_ln56_fu_1635_p1 = rd_fu_1100_p4;

assign zext_ln59_fu_1630_p1 = rd_fu_1100_p4;

assign zext_ln62_fu_1608_p1 = rd_fu_1100_p4;

assign zext_ln67_fu_1603_p1 = rd_fu_1100_p4;

assign zext_ln68_fu_2727_p1 = rs1_reg_2780;

assign zext_ln74_1_fu_1592_p1 = rs2_fu_1090_p4;

assign zext_ln74_fu_1587_p1 = rs1_fu_1080_p4;

assign zext_ln80_1_fu_1582_p1 = rs2_fu_1090_p4;

assign zext_ln80_fu_1577_p1 = rs1_fu_1080_p4;

assign zext_ln86_1_fu_1572_p1 = rs2_fu_1090_p4;

assign zext_ln86_fu_1567_p1 = rs1_fu_1080_p4;

assign zext_ln92_1_fu_1562_p1 = rs2_fu_1090_p4;

assign zext_ln92_fu_1557_p1 = rs1_fu_1080_p4;

assign zext_ln98_1_fu_1552_p1 = rs2_fu_1090_p4;

assign zext_ln98_fu_1547_p1 = rs1_fu_1080_p4;

always @ (posedge ap_clk) begin
    sext_ln42_reg_2822[0] <= 1'b0;
end

endmodule //processor
