// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processor_processor,hls_ip_2023_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.203667,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1392,HLS_SYN_LUT=3177,HLS_VERSION=2023_1_1}" *)

module processor (
        ap_clk,
        ap_rst,
        memory_address0,
        memory_ce0,
        memory_we0,
        memory_d0,
        memory_q0,
        o_error
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
output  [16:0] memory_address0;
output   memory_ce0;
output   memory_we0;
output  [31:0] memory_d0;
input  [31:0] memory_q0;
output  [0:0] o_error;

reg[16:0] memory_address0;
reg memory_ce0;
reg memory_we0;

reg   [31:0] g_pc;
reg   [0:0] g_error;
reg   [31:0] p_ZL6g_xreg_1;
reg   [31:0] p_ZL6g_xreg_2;
reg   [31:0] p_ZL6g_xreg_3;
reg   [31:0] p_ZL6g_xreg_4;
reg   [31:0] p_ZL6g_xreg_5;
reg   [31:0] p_ZL6g_xreg_6;
reg   [31:0] p_ZL6g_xreg_7;
reg   [31:0] p_ZL6g_xreg_8;
reg   [31:0] p_ZL6g_xreg_9;
reg   [31:0] p_ZL6g_xreg_10;
reg   [31:0] p_ZL6g_xreg_11;
reg   [31:0] p_ZL6g_xreg_12;
reg   [31:0] p_ZL6g_xreg_13;
reg   [31:0] p_ZL6g_xreg_14;
reg   [31:0] p_ZL6g_xreg_15;
reg   [31:0] p_ZL6g_xreg_16;
reg   [31:0] p_ZL6g_xreg_17;
reg   [31:0] p_ZL6g_xreg_18;
reg   [31:0] p_ZL6g_xreg_19;
reg   [31:0] p_ZL6g_xreg_20;
reg   [31:0] p_ZL6g_xreg_21;
reg   [31:0] p_ZL6g_xreg_22;
reg   [31:0] p_ZL6g_xreg_23;
reg   [31:0] p_ZL6g_xreg_24;
reg   [31:0] p_ZL6g_xreg_25;
reg   [31:0] p_ZL6g_xreg_26;
reg   [31:0] p_ZL6g_xreg_27;
reg   [31:0] p_ZL6g_xreg_28;
reg   [31:0] p_ZL6g_xreg_29;
reg   [31:0] p_ZL6g_xreg_30;
reg   [31:0] p_ZL6g_xreg_31;
reg   [31:0] old_pc_reg_2303;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] op_code_fu_891_p1;
reg   [6:0] op_code_reg_2319;
wire    ap_CS_fsm_state2;
reg   [2:0] funct3_reg_2324;
reg   [6:0] funct7_reg_2329;
reg   [4:0] rd_reg_2334;
reg   [3:0] tmp7_reg_2338;
reg   [5:0] tmp_s_reg_2343;
reg   [0:0] tmp_reg_2348;
reg   [0:0] tmp_1_reg_2353;
reg   [11:0] imm_I_reg_2359;
reg   [9:0] tmp_2_reg_2366;
reg   [0:0] tmp_3_reg_2371;
reg   [7:0] tmp_6_reg_2376;
reg   [4:0] tmp_7_reg_2381;
reg   [6:0] tmp_8_reg_2386;
reg   [19:0] tmp_5_reg_2391;
wire   [31:0] source1_fu_1173_p34;
reg   [31:0] source1_reg_2396;
wire   [31:0] result_24_fu_1243_p34;
reg   [31:0] result_24_reg_2407;
wire   [31:0] result_2_fu_1313_p2;
reg   [31:0] result_2_reg_2422;
wire    ap_CS_fsm_state3;
wire   [31:0] select_ln96_fu_1364_p3;
wire   [31:0] select_ln91_fu_1372_p3;
wire   [31:0] select_ln86_fu_1380_p3;
wire   [31:0] select_ln81_fu_1388_p3;
wire   [31:0] select_ln76_fu_1396_p3;
wire   [31:0] select_ln71_fu_1404_p3;
wire   [31:0] add_ln64_fu_1418_p2;
wire   [31:0] add_ln59_fu_1423_p2;
wire   [2:0] select_ln114_fu_1518_p3;
reg   [2:0] select_ln114_reg_2488;
wire   [16:0] trunc_ln408_fu_1670_p1;
reg   [16:0] trunc_ln408_reg_2560;
wire   [2:0] select_ln168_fu_1704_p3;
reg   [2:0] select_ln168_reg_2574;
wire    call_ret_execute_arithm_fu_774_ap_ready;
wire   [31:0] call_ret_execute_arithm_fu_774_imm_U_val;
wire   [0:0] call_ret_execute_arithm_fu_774_g_error;
wire    call_ret_execute_arithm_fu_774_g_error_ap_vld;
wire   [31:0] call_ret_execute_arithm_fu_774_ap_return_0;
wire   [0:0] call_ret_execute_arithm_fu_774_ap_return_1;
reg   [31:0] ap_phi_mux_result_22_phi_fu_432_p36;
reg   [31:0] result_22_reg_428;
wire    ap_CS_fsm_state4;
wire   [31:0] zext_ln153_1_fu_1746_p1;
wire   [31:0] zext_ln155_1_fu_1737_p1;
wire   [31:0] zext_ln142_1_fu_1770_p1;
wire   [31:0] zext_ln144_1_fu_1761_p1;
wire   [31:0] zext_ln146_1_fu_1756_p1;
wire   [31:0] zext_ln148_1_fu_1751_p1;
wire  signed [31:0] sext_ln132_fu_1784_p1;
wire  signed [31:0] sext_ln134_fu_1775_p1;
wire  signed [31:0] sext_ln121_fu_1808_p1;
wire  signed [31:0] sext_ln123_fu_1799_p1;
wire  signed [31:0] sext_ln125_fu_1794_p1;
wire  signed [31:0] sext_ln127_fu_1789_p1;
reg   [31:0] ap_phi_mux_g_pc_new_7_phi_fu_479_p40;
reg   [31:0] g_pc_new_7_reg_476;
reg   [0:0] ap_phi_mux_write_reg_1_phi_fu_526_p40;
reg   [0:0] write_reg_1_reg_521;
reg   [31:0] ap_phi_mux_result_816_phi_fu_590_p40;
reg   [31:0] result_816_reg_587;
wire   [31:0] result_10_fu_2002_p5;
wire   [31:0] result_9_fu_2018_p5;
wire   [31:0] result_8_fu_2034_p5;
wire   [31:0] result_7_fu_2050_p5;
wire   [31:0] result_6_fu_2066_p5;
wire   [31:0] result_5_fu_2082_p5;
reg   [0:0] ap_phi_mux_write_mem_0_ph_phi_fu_640_p40;
reg   [0:0] write_mem_0_ph_reg_636;
reg   [16:0] ap_phi_mux_write_addr_0_ph_phi_fu_706_p40;
reg   [16:0] write_addr_0_ph_reg_702;
reg   [31:0] ap_phi_mux_g_pc_new_8_phi_fu_761_p8;
wire   [63:0] zext_ln28_fu_886_p1;
wire   [63:0] zext_ln155_fu_1538_p1;
wire   [63:0] zext_ln153_fu_1543_p1;
wire   [63:0] zext_ln148_fu_1548_p1;
wire   [63:0] zext_ln146_fu_1553_p1;
wire   [63:0] zext_ln144_fu_1558_p1;
wire   [63:0] zext_ln142_fu_1563_p1;
wire   [63:0] zext_ln138_fu_1568_p1;
wire   [63:0] zext_ln134_fu_1573_p1;
wire   [63:0] zext_ln132_fu_1578_p1;
wire   [63:0] zext_ln127_fu_1583_p1;
wire   [63:0] zext_ln125_fu_1588_p1;
wire   [63:0] zext_ln123_fu_1593_p1;
wire   [63:0] zext_ln121_fu_1598_p1;
wire   [63:0] zext_ln172_fu_1724_p1;
wire   [63:0] zext_ln379_fu_2287_p1;
reg   [0:0] ap_sig_allocacmp_g_error_load;
wire   [0:0] icmp_ln115_fu_1526_p2;
wire   [0:0] icmp_ln169_fu_1712_p2;
wire   [0:0] or_ln26_fu_874_p2;
wire  signed [31:0] sext_ln40_fu_1328_p1;
wire   [1:0] trunc_ln26_fu_848_p1;
wire   [0:0] icmp_ln26_fu_852_p2;
wire   [0:0] icmp_ln26_1_fu_868_p2;
wire   [16:0] lshr_ln_fu_858_p4;
wire   [4:0] source1_fu_1173_p33;
wire   [4:0] result_24_fu_1243_p33;
wire   [12:0] imm_B_fu_1318_p6;
wire   [20:0] imm_J_fu_1336_p6;
wire   [0:0] grp_fu_788_p2;
wire   [31:0] grp_fu_792_p2;
wire   [0:0] grp_fu_796_p2;
wire   [0:0] grp_fu_800_p2;
wire  signed [31:0] sext_ln41_fu_1333_p1;
wire  signed [31:0] sext_ln42_fu_1346_p1;
wire   [33:0] zext_ln113_fu_1428_p1;
wire  signed [33:0] sext_ln113_fu_1431_p1;
wire   [33:0] add_ln113_fu_1434_p2;
wire   [33:0] sub_ln113_fu_1448_p2;
wire   [31:0] trunc_ln113_1_fu_1454_p4;
wire   [0:0] tmp_11_fu_1440_p3;
wire   [31:0] sub_ln113_1_fu_1464_p2;
wire   [31:0] trunc_ln113_2_fu_1470_p4;
wire   [1:0] trunc_ln114_1_fu_1492_p1;
wire   [2:0] p_and_t_fu_1496_p3;
wire   [1:0] trunc_ln114_fu_1488_p1;
wire   [2:0] sub_ln114_fu_1504_p2;
wire   [2:0] tmp_12_fu_1510_p3;
wire   [31:0] pos_fu_1480_p3;
wire   [11:0] tmp_4_fu_1350_p3;
wire   [33:0] zext_ln167_fu_1609_p1;
wire  signed [33:0] sext_ln167_fu_1612_p1;
wire   [33:0] add_ln167_fu_1616_p2;
wire   [33:0] sub_ln167_fu_1630_p2;
wire   [31:0] trunc_ln167_1_fu_1636_p4;
wire   [0:0] tmp_9_fu_1622_p3;
wire   [31:0] sub_ln167_1_fu_1646_p2;
wire   [31:0] trunc_ln167_2_fu_1652_p4;
wire   [31:0] write_addr_fu_1662_p3;
wire   [1:0] trunc_ln168_1_fu_1678_p1;
wire   [2:0] p_and_t3_fu_1682_p3;
wire   [1:0] trunc_ln168_fu_1674_p1;
wire   [2:0] sub_ln168_fu_1690_p2;
wire   [2:0] tmp_10_fu_1696_p3;
wire   [15:0] grp_fu_804_p4;
wire   [15:0] result_21_fu_1742_p1;
wire   [7:0] grp_fu_814_p4;
wire   [7:0] grp_fu_824_p4;
wire   [7:0] grp_fu_834_p4;
wire   [7:0] result_17_fu_1766_p1;
wire   [15:0] result_15_fu_1780_p1;
wire   [7:0] result_11_fu_1804_p1;
wire   [15:0] trunc_ln189_fu_1999_p1;
wire   [15:0] trunc_ln187_fu_2015_p1;
wire   [7:0] trunc_ln182_fu_2031_p1;
wire   [7:0] trunc_ln180_fu_2047_p1;
wire   [7:0] trunc_ln178_fu_2063_p1;
wire   [7:0] trunc_ln176_fu_2079_p1;
reg   [3:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 g_pc = 32'd0;
#0 g_error = 1'd0;
#0 p_ZL6g_xreg_1 = 32'd0;
#0 p_ZL6g_xreg_2 = 32'd0;
#0 p_ZL6g_xreg_3 = 32'd0;
#0 p_ZL6g_xreg_4 = 32'd0;
#0 p_ZL6g_xreg_5 = 32'd0;
#0 p_ZL6g_xreg_6 = 32'd0;
#0 p_ZL6g_xreg_7 = 32'd0;
#0 p_ZL6g_xreg_8 = 32'd0;
#0 p_ZL6g_xreg_9 = 32'd0;
#0 p_ZL6g_xreg_10 = 32'd0;
#0 p_ZL6g_xreg_11 = 32'd0;
#0 p_ZL6g_xreg_12 = 32'd0;
#0 p_ZL6g_xreg_13 = 32'd0;
#0 p_ZL6g_xreg_14 = 32'd0;
#0 p_ZL6g_xreg_15 = 32'd0;
#0 p_ZL6g_xreg_16 = 32'd0;
#0 p_ZL6g_xreg_17 = 32'd0;
#0 p_ZL6g_xreg_18 = 32'd0;
#0 p_ZL6g_xreg_19 = 32'd0;
#0 p_ZL6g_xreg_20 = 32'd0;
#0 p_ZL6g_xreg_21 = 32'd0;
#0 p_ZL6g_xreg_22 = 32'd0;
#0 p_ZL6g_xreg_23 = 32'd0;
#0 p_ZL6g_xreg_24 = 32'd0;
#0 p_ZL6g_xreg_25 = 32'd0;
#0 p_ZL6g_xreg_26 = 32'd0;
#0 p_ZL6g_xreg_27 = 32'd0;
#0 p_ZL6g_xreg_28 = 32'd0;
#0 p_ZL6g_xreg_29 = 32'd0;
#0 p_ZL6g_xreg_30 = 32'd0;
#0 p_ZL6g_xreg_31 = 32'd0;
#0 ap_CS_fsm = 4'd1;
end

processor_execute_arithm call_ret_execute_arithm_fu_774(
    .ap_ready(call_ret_execute_arithm_fu_774_ap_ready),
    .op_code_val(op_code_reg_2319),
    .funct3_val(funct3_reg_2324),
    .funct7_val(funct7_reg_2329),
    .source1_val(source1_reg_2396),
    .source2_val(result_24_reg_2407),
    .imm_I_val(imm_I_reg_2359),
    .imm_U_val(call_ret_execute_arithm_fu_774_imm_U_val),
    .old_pc_val(old_pc_reg_2303),
    .g_error(call_ret_execute_arithm_fu_774_g_error),
    .g_error_ap_vld(call_ret_execute_arithm_fu_774_g_error_ap_vld),
    .ap_return_0(call_ret_execute_arithm_fu_774_ap_return_0),
    .ap_return_1(call_ret_execute_arithm_fu_774_ap_return_1)
);

processor_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U10(
    .din0(32'd0),
    .din1(p_ZL6g_xreg_1),
    .din2(p_ZL6g_xreg_2),
    .din3(p_ZL6g_xreg_3),
    .din4(p_ZL6g_xreg_4),
    .din5(p_ZL6g_xreg_5),
    .din6(p_ZL6g_xreg_6),
    .din7(p_ZL6g_xreg_7),
    .din8(p_ZL6g_xreg_8),
    .din9(p_ZL6g_xreg_9),
    .din10(p_ZL6g_xreg_10),
    .din11(p_ZL6g_xreg_11),
    .din12(p_ZL6g_xreg_12),
    .din13(p_ZL6g_xreg_13),
    .din14(p_ZL6g_xreg_14),
    .din15(p_ZL6g_xreg_15),
    .din16(p_ZL6g_xreg_16),
    .din17(p_ZL6g_xreg_17),
    .din18(p_ZL6g_xreg_18),
    .din19(p_ZL6g_xreg_19),
    .din20(p_ZL6g_xreg_20),
    .din21(p_ZL6g_xreg_21),
    .din22(p_ZL6g_xreg_22),
    .din23(p_ZL6g_xreg_23),
    .din24(p_ZL6g_xreg_24),
    .din25(p_ZL6g_xreg_25),
    .din26(p_ZL6g_xreg_26),
    .din27(p_ZL6g_xreg_27),
    .din28(p_ZL6g_xreg_28),
    .din29(p_ZL6g_xreg_29),
    .din30(p_ZL6g_xreg_30),
    .din31(p_ZL6g_xreg_31),
    .din32(source1_fu_1173_p33),
    .dout(source1_fu_1173_p34)
);

processor_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U11(
    .din0(32'd0),
    .din1(p_ZL6g_xreg_1),
    .din2(p_ZL6g_xreg_2),
    .din3(p_ZL6g_xreg_3),
    .din4(p_ZL6g_xreg_4),
    .din5(p_ZL6g_xreg_5),
    .din6(p_ZL6g_xreg_6),
    .din7(p_ZL6g_xreg_7),
    .din8(p_ZL6g_xreg_8),
    .din9(p_ZL6g_xreg_9),
    .din10(p_ZL6g_xreg_10),
    .din11(p_ZL6g_xreg_11),
    .din12(p_ZL6g_xreg_12),
    .din13(p_ZL6g_xreg_13),
    .din14(p_ZL6g_xreg_14),
    .din15(p_ZL6g_xreg_15),
    .din16(p_ZL6g_xreg_16),
    .din17(p_ZL6g_xreg_17),
    .din18(p_ZL6g_xreg_18),
    .din19(p_ZL6g_xreg_19),
    .din20(p_ZL6g_xreg_20),
    .din21(p_ZL6g_xreg_21),
    .din22(p_ZL6g_xreg_22),
    .din23(p_ZL6g_xreg_23),
    .din24(p_ZL6g_xreg_24),
    .din25(p_ZL6g_xreg_25),
    .din26(p_ZL6g_xreg_26),
    .din27(p_ZL6g_xreg_27),
    .din28(p_ZL6g_xreg_28),
    .din29(p_ZL6g_xreg_29),
    .din30(p_ZL6g_xreg_30),
    .din31(p_ZL6g_xreg_31),
    .din32(result_24_fu_1243_p33),
    .dout(result_24_fu_1243_p34)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        g_pc <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            g_pc <= ap_phi_mux_g_pc_new_8_phi_fu_761_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((or_ln26_fu_874_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & ~(funct3_reg_2324 == 3'd4) & ~(funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((op_code_reg_2319 == 7'd35) & (icmp_ln169_fu_1712_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((op_code_reg_2319 == 7'd3) & (icmp_ln115_fu_1526_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & (((funct3_reg_2324 == 3'd3) & (op_code_reg_2319 == 7'd99)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd99)))))) begin
        g_error <= 1'd1;
    end else if ((~(op_code_reg_2319 == 7'd35) & ~(op_code_reg_2319 == 7'd3) & ~(op_code_reg_2319 == 7'd111) & ~(op_code_reg_2319 == 7'd103) & ~(op_code_reg_2319 == 7'd99) & (call_ret_execute_arithm_fu_774_g_error_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        g_error <= call_ret_execute_arithm_fu_774_g_error;
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln71_fu_1404_p3;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln76_fu_1396_p3;
    end else if (((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln81_fu_1388_p3;
    end else if (((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln86_fu_1380_p3;
    end else if (((funct3_reg_2324 == 3'd6) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln91_fu_1372_p3;
    end else if (((funct3_reg_2324 == 3'd7) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= select_ln96_fu_1364_p3;
    end else if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        g_pc_new_7_reg_476 <= result_2_reg_2422;
    end else if (((op_code_reg_2319 == 7'd111) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= add_ln59_fu_1423_p2;
    end else if (((op_code_reg_2319 == 7'd103) & (1'b1 == ap_CS_fsm_state3))) begin
        g_pc_new_7_reg_476 <= add_ln64_fu_1418_p2;
    end else if (((~(op_code_reg_2319 == 7'd35) & ~(op_code_reg_2319 == 7'd3) & ~(op_code_reg_2319 == 7'd111) & ~(op_code_reg_2319 == 7'd103) & ~(op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & (((funct3_reg_2324 == 3'd3) & (op_code_reg_2319 == 7'd99)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd99)))))) begin
        g_pc_new_7_reg_476 <= result_2_fu_1313_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_1 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_1 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd10) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_10 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_10 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd11) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_11 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_11 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd12) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_12 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_12 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd13) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_13 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_13 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd14) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_14 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_14 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd15) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_15 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_15 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd16) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_16 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_16 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd17) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_17 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_17 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd18) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_18 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_18 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd19) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_19 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_19 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_2 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_2 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd20) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_20 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_20 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd21) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_21 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_21 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd22) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_22 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_22 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd23) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_23 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_23 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd24) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_24 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_24 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd25) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_25 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_25 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd26) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_26 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_26 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd27) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_27 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_27 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd28) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_28 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_28 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd29) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_29 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_29 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_3 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_3 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd30) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_30 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_30 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd31) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_31 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_31 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_4 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_4 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_5 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_5 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_6 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_6 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd7) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_7 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_7 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd8) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_8 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_8 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rd_reg_2334 == 5'd9) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1))) begin
            p_ZL6g_xreg_9 <= ap_phi_mux_result_816_phi_fu_590_p40;
        end else if ((op_code_reg_2319 == 7'd3)) begin
            p_ZL6g_xreg_9 <= ap_phi_mux_result_22_phi_fu_432_p36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd3))) begin
            result_22_reg_428 <= sext_ln127_fu_1789_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd2))) begin
            result_22_reg_428 <= sext_ln125_fu_1794_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd1))) begin
            result_22_reg_428 <= sext_ln123_fu_1799_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd0))) begin
            result_22_reg_428 <= sext_ln121_fu_1808_p1;
        end else if (((funct3_reg_2324 == 3'd1) & (select_ln114_reg_2488 == 3'd2))) begin
            result_22_reg_428 <= sext_ln134_fu_1775_p1;
        end else if (((funct3_reg_2324 == 3'd1) & (select_ln114_reg_2488 == 3'd0))) begin
            result_22_reg_428 <= sext_ln132_fu_1784_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd3))) begin
            result_22_reg_428 <= zext_ln148_1_fu_1751_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd2))) begin
            result_22_reg_428 <= zext_ln146_1_fu_1756_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd1))) begin
            result_22_reg_428 <= zext_ln144_1_fu_1761_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd0))) begin
            result_22_reg_428 <= zext_ln142_1_fu_1770_p1;
        end else if (((funct3_reg_2324 == 3'd5) & (select_ln114_reg_2488 == 3'd2))) begin
            result_22_reg_428 <= zext_ln155_1_fu_1737_p1;
        end else if (((funct3_reg_2324 == 3'd5) & (select_ln114_reg_2488 == 3'd0))) begin
            result_22_reg_428 <= zext_ln153_1_fu_1746_p1;
        end else if ((funct3_reg_2324 == 3'd2)) begin
            result_22_reg_428 <= memory_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_5_fu_2082_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_6_fu_2066_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_7_fu_2050_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_8_fu_2034_p5;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_9_fu_2018_p5;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_10_fu_2002_p5;
    end else if (((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4))) begin
        result_816_reg_587 <= result_24_reg_2407;
    end else if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)))) begin
        result_816_reg_587 <= memory_q0;
    end else if ((((op_code_reg_2319 == 7'd111) & (1'b1 == ap_CS_fsm_state3)) | ((op_code_reg_2319 == 7'd103) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd6) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd7) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & (((funct3_reg_2324 == 3'd3) & (op_code_reg_2319 == 7'd99)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd99)))))) begin
        result_816_reg_587 <= result_2_fu_1313_p2;
    end else if ((~(op_code_reg_2319 == 7'd35) & ~(op_code_reg_2319 == 7'd3) & ~(op_code_reg_2319 == 7'd111) & ~(op_code_reg_2319 == 7'd103) & ~(op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        result_816_reg_587 <= call_ret_execute_arithm_fu_774_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        write_mem_0_ph_reg_636 <= 1'd1;
    end else if (((~(op_code_reg_2319 == 7'd35) & ~(op_code_reg_2319 == 7'd3) & ~(op_code_reg_2319 == 7'd111) & ~(op_code_reg_2319 == 7'd103) & ~(op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((op_code_reg_2319 == 7'd111) & (1'b1 == ap_CS_fsm_state3)) | ((op_code_reg_2319 == 7'd103) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd6) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd7) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & (((funct3_reg_2324 == 3'd3) & (op_code_reg_2319 == 7'd99)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd99)))))) begin
        write_mem_0_ph_reg_636 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd6) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd7) & (op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state3) & (((funct3_reg_2324 == 3'd3) & (op_code_reg_2319 == 7'd99)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd99)))))) begin
        write_reg_1_reg_521 <= 1'd0;
    end else if ((((op_code_reg_2319 == 7'd111) & (1'b1 == ap_CS_fsm_state3)) | ((op_code_reg_2319 == 7'd103) & (1'b1 == ap_CS_fsm_state3)))) begin
        write_reg_1_reg_521 <= 1'd1;
    end else if ((~(op_code_reg_2319 == 7'd35) & ~(op_code_reg_2319 == 7'd3) & ~(op_code_reg_2319 == 7'd111) & ~(op_code_reg_2319 == 7'd103) & ~(op_code_reg_2319 == 7'd99) & (1'b1 == ap_CS_fsm_state3))) begin
        write_reg_1_reg_521 <= call_ret_execute_arithm_fu_774_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        funct3_reg_2324 <= {{memory_q0[14:12]}};
        funct7_reg_2329 <= {{memory_q0[31:25]}};
        imm_I_reg_2359 <= {{memory_q0[31:20]}};
        op_code_reg_2319 <= op_code_fu_891_p1;
        rd_reg_2334 <= {{memory_q0[11:7]}};
        result_24_reg_2407 <= result_24_fu_1243_p34;
        source1_reg_2396 <= source1_fu_1173_p34;
        tmp7_reg_2338 <= {{memory_q0[11:8]}};
        tmp_1_reg_2353 <= memory_q0[32'd31];
        tmp_2_reg_2366 <= {{memory_q0[30:21]}};
        tmp_3_reg_2371 <= memory_q0[32'd20];
        tmp_5_reg_2391 <= {{memory_q0[31:12]}};
        tmp_6_reg_2376 <= {{memory_q0[19:12]}};
        tmp_7_reg_2381 <= {{memory_q0[11:7]}};
        tmp_8_reg_2386 <= {{memory_q0[31:25]}};
        tmp_reg_2348 <= memory_q0[32'd7];
        tmp_s_reg_2343 <= {{memory_q0[30:25]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        old_pc_reg_2303 <= g_pc;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        result_2_reg_2422 <= result_2_fu_1313_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3))) begin
        select_ln114_reg_2488 <= select_ln114_fu_1518_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state3))) begin
        select_ln168_reg_2574 <= select_ln168_fu_1704_p3;
        trunc_ln408_reg_2560 <= trunc_ln408_fu_1670_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        write_addr_0_ph_reg_702 <= trunc_ln408_reg_2560;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_g_pc_new_7_phi_fu_479_p40 = result_2_reg_2422;
    end else begin
        ap_phi_mux_g_pc_new_7_phi_fu_479_p40 = g_pc_new_7_reg_476;
    end
end

always @ (*) begin
    if (((op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_g_pc_new_8_phi_fu_761_p8 = result_2_reg_2422;
    end else if (((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 == 1'd0) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 == 1'd0) & (ap_phi_mux_write_reg_1_phi_fu_526_p40 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | (~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_g_pc_new_8_phi_fu_761_p8 = ap_phi_mux_g_pc_new_7_phi_fu_479_p40;
    end else begin
        ap_phi_mux_g_pc_new_8_phi_fu_761_p8 = 'bx;
    end
end

always @ (*) begin
    if (((op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd3))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln127_fu_1789_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd2))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln125_fu_1794_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd1))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln123_fu_1799_p1;
        end else if (((funct3_reg_2324 == 3'd0) & (select_ln114_reg_2488 == 3'd0))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln121_fu_1808_p1;
        end else if (((funct3_reg_2324 == 3'd1) & (select_ln114_reg_2488 == 3'd2))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln134_fu_1775_p1;
        end else if (((funct3_reg_2324 == 3'd1) & (select_ln114_reg_2488 == 3'd0))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = sext_ln132_fu_1784_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd3))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln148_1_fu_1751_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd2))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln146_1_fu_1756_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd1))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln144_1_fu_1761_p1;
        end else if (((funct3_reg_2324 == 3'd4) & (select_ln114_reg_2488 == 3'd0))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln142_1_fu_1770_p1;
        end else if (((funct3_reg_2324 == 3'd5) & (select_ln114_reg_2488 == 3'd2))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln155_1_fu_1737_p1;
        end else if (((funct3_reg_2324 == 3'd5) & (select_ln114_reg_2488 == 3'd0))) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = zext_ln153_1_fu_1746_p1;
        end else if ((funct3_reg_2324 == 3'd2)) begin
            ap_phi_mux_result_22_phi_fu_432_p36 = memory_q0;
        end else begin
            ap_phi_mux_result_22_phi_fu_432_p36 = result_22_reg_428;
        end
    end else begin
        ap_phi_mux_result_22_phi_fu_432_p36 = result_22_reg_428;
    end
end

always @ (*) begin
    if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_5_fu_2082_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_6_fu_2066_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_7_fu_2050_p5;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_8_fu_2034_p5;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_9_fu_2018_p5;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_10_fu_2002_p5;
    end else if (((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_24_reg_2407;
    end else if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_result_816_phi_fu_590_p40 = memory_q0;
    end else begin
        ap_phi_mux_result_816_phi_fu_590_p40 = result_816_reg_587;
    end
end

always @ (*) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_write_addr_0_ph_phi_fu_706_p40 = trunc_ln408_reg_2560;
    end else begin
        ap_phi_mux_write_addr_0_ph_phi_fu_706_p40 = write_addr_0_ph_reg_702;
    end
end

always @ (*) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 = 1'd1;
    end else begin
        ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 = write_mem_0_ph_reg_636;
    end
end

always @ (*) begin
    if (((~(select_ln168_reg_2574 == 3'd3) & ~(select_ln168_reg_2574 == 3'd1) & ~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(select_ln168_reg_2574 == 3'd2) & ~(select_ln168_reg_2574 == 3'd0) & (funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | (~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd3) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd1) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 
    == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (select_ln168_reg_2574 == 3'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        ap_phi_mux_write_reg_1_phi_fu_526_p40 = 1'd0;
    end else begin
        ap_phi_mux_write_reg_1_phi_fu_526_p40 = write_reg_1_reg_521;
    end
end

always @ (*) begin
    if ((~(funct3_reg_2324 == 3'd2) & ~(funct3_reg_2324 == 3'd0) & ~(funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_sig_allocacmp_g_error_load = 1'd1;
    end else begin
        ap_sig_allocacmp_g_error_load = g_error;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        memory_address0 = zext_ln379_fu_2287_p1;
    end else if (((op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state3))) begin
        memory_address0 = zext_ln172_fu_1724_p1;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0))) begin
        memory_address0 = zext_ln121_fu_1598_p1;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd1))) begin
        memory_address0 = zext_ln123_fu_1593_p1;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2))) begin
        memory_address0 = zext_ln125_fu_1588_p1;
    end else if (((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd3))) begin
        memory_address0 = zext_ln127_fu_1583_p1;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0))) begin
        memory_address0 = zext_ln132_fu_1578_p1;
    end else if (((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2))) begin
        memory_address0 = zext_ln134_fu_1573_p1;
    end else if (((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3))) begin
        memory_address0 = zext_ln138_fu_1568_p1;
    end else if (((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0))) begin
        memory_address0 = zext_ln142_fu_1563_p1;
    end else if (((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd1))) begin
        memory_address0 = zext_ln144_fu_1558_p1;
    end else if (((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2))) begin
        memory_address0 = zext_ln146_fu_1553_p1;
    end else if (((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd3))) begin
        memory_address0 = zext_ln148_fu_1548_p1;
    end else if (((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0))) begin
        memory_address0 = zext_ln153_fu_1543_p1;
    end else if (((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2))) begin
        memory_address0 = zext_ln155_fu_1538_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        memory_address0 = zext_ln28_fu_886_p1;
    end else begin
        memory_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state4) | ((op_code_reg_2319 == 7'd35) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd2) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd1)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd3)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0)) | ((funct3_reg_2324 == 3'd0) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0)) | ((funct3_reg_2324 == 3'd1) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) 
    & (select_ln114_fu_1518_p3 == 3'd1)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd3)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0)) | ((funct3_reg_2324 == 3'd4) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2)) | ((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd0)) | ((funct3_reg_2324 == 3'd5) & (op_code_reg_2319 == 7'd3) & (1'b1 == ap_CS_fsm_state3) & (select_ln114_fu_1518_p3 == 3'd2)))) begin
        memory_ce0 = 1'b1;
    end else begin
        memory_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(op_code_reg_2319 == 7'd3) & (ap_phi_mux_write_mem_0_ph_phi_fu_640_p40 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        memory_we0 = 1'b1;
    end else begin
        memory_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln113_fu_1434_p2 = ($signed(zext_ln113_fu_1428_p1) + $signed(sext_ln113_fu_1431_p1));

assign add_ln167_fu_1616_p2 = ($signed(zext_ln167_fu_1609_p1) + $signed(sext_ln167_fu_1612_p1));

assign add_ln59_fu_1423_p2 = ($signed(old_pc_reg_2303) + $signed(sext_ln42_fu_1346_p1));

assign add_ln64_fu_1418_p2 = ($signed(source1_reg_2396) + $signed(sext_ln41_fu_1333_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign call_ret_execute_arithm_fu_774_imm_U_val = {{tmp_5_reg_2391}, {12'd0}};

assign grp_fu_788_p2 = ((source1_reg_2396 < result_24_reg_2407) ? 1'b1 : 1'b0);

assign grp_fu_792_p2 = ($signed(old_pc_reg_2303) + $signed(sext_ln40_fu_1328_p1));

assign grp_fu_796_p2 = (($signed(source1_reg_2396) < $signed(result_24_reg_2407)) ? 1'b1 : 1'b0);

assign grp_fu_800_p2 = ((source1_reg_2396 == result_24_reg_2407) ? 1'b1 : 1'b0);

assign grp_fu_804_p4 = {{memory_q0[31:16]}};

assign grp_fu_814_p4 = {{memory_q0[31:24]}};

assign grp_fu_824_p4 = {{memory_q0[23:16]}};

assign grp_fu_834_p4 = {{memory_q0[15:8]}};

assign icmp_ln115_fu_1526_p2 = ((pos_fu_1480_p3 > 32'd102399) ? 1'b1 : 1'b0);

assign icmp_ln169_fu_1712_p2 = ((write_addr_fu_1662_p3 > 32'd102399) ? 1'b1 : 1'b0);

assign icmp_ln26_1_fu_868_p2 = ((g_pc > 32'd409599) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_852_p2 = ((trunc_ln26_fu_848_p1 != 2'd0) ? 1'b1 : 1'b0);

assign imm_B_fu_1318_p6 = {{{{{tmp_1_reg_2353}, {tmp_reg_2348}}, {tmp_s_reg_2343}}, {tmp7_reg_2338}}, {1'd0}};

assign imm_J_fu_1336_p6 = {{{{{tmp_1_reg_2353}, {tmp_6_reg_2376}}, {tmp_3_reg_2371}}, {tmp_2_reg_2366}}, {1'd0}};

assign lshr_ln_fu_858_p4 = {{g_pc[18:2]}};

assign memory_d0 = ap_phi_mux_result_816_phi_fu_590_p40;

assign o_error = ap_sig_allocacmp_g_error_load;

assign op_code_fu_891_p1 = memory_q0[6:0];

assign or_ln26_fu_874_p2 = (icmp_ln26_fu_852_p2 | icmp_ln26_1_fu_868_p2);

assign p_and_t3_fu_1682_p3 = {{1'd0}, {trunc_ln168_1_fu_1678_p1}};

assign p_and_t_fu_1496_p3 = {{1'd0}, {trunc_ln114_1_fu_1492_p1}};

assign pos_fu_1480_p3 = ((tmp_11_fu_1440_p3[0:0] == 1'b1) ? sub_ln113_1_fu_1464_p2 : trunc_ln113_2_fu_1470_p4);

assign result_10_fu_2002_p5 = {{trunc_ln189_fu_1999_p1}, {memory_q0[15:0]}};

assign result_11_fu_1804_p1 = memory_q0[7:0];

assign result_15_fu_1780_p1 = memory_q0[15:0];

assign result_17_fu_1766_p1 = memory_q0[7:0];

assign result_21_fu_1742_p1 = memory_q0[15:0];

assign result_24_fu_1243_p33 = {{memory_q0[24:20]}};

assign result_2_fu_1313_p2 = (old_pc_reg_2303 + 32'd4);

assign result_5_fu_2082_p5 = {{memory_q0[31:8]}, {trunc_ln176_fu_2079_p1}};

assign result_6_fu_2066_p5 = {{memory_q0[31:16]}, {trunc_ln178_fu_2063_p1}, {memory_q0[7:0]}};

assign result_7_fu_2050_p5 = {{memory_q0[31:24]}, {trunc_ln180_fu_2047_p1}, {memory_q0[15:0]}};

assign result_8_fu_2034_p5 = {{trunc_ln182_fu_2031_p1}, {memory_q0[23:0]}};

assign result_9_fu_2018_p5 = {{memory_q0[31:16]}, {trunc_ln187_fu_2015_p1}};

assign select_ln114_fu_1518_p3 = ((tmp_11_fu_1440_p3[0:0] == 1'b1) ? sub_ln114_fu_1504_p2 : tmp_12_fu_1510_p3);

assign select_ln168_fu_1704_p3 = ((tmp_9_fu_1622_p3[0:0] == 1'b1) ? sub_ln168_fu_1690_p2 : tmp_10_fu_1696_p3);

assign select_ln71_fu_1404_p3 = ((grp_fu_800_p2[0:0] == 1'b1) ? grp_fu_792_p2 : result_2_fu_1313_p2);

assign select_ln76_fu_1396_p3 = ((grp_fu_800_p2[0:0] == 1'b1) ? result_2_fu_1313_p2 : grp_fu_792_p2);

assign select_ln81_fu_1388_p3 = ((grp_fu_796_p2[0:0] == 1'b1) ? grp_fu_792_p2 : result_2_fu_1313_p2);

assign select_ln86_fu_1380_p3 = ((grp_fu_796_p2[0:0] == 1'b1) ? result_2_fu_1313_p2 : grp_fu_792_p2);

assign select_ln91_fu_1372_p3 = ((grp_fu_788_p2[0:0] == 1'b1) ? grp_fu_792_p2 : result_2_fu_1313_p2);

assign select_ln96_fu_1364_p3 = ((grp_fu_788_p2[0:0] == 1'b1) ? result_2_fu_1313_p2 : grp_fu_792_p2);

assign sext_ln113_fu_1431_p1 = $signed(imm_I_reg_2359);

assign sext_ln121_fu_1808_p1 = $signed(result_11_fu_1804_p1);

assign sext_ln123_fu_1799_p1 = $signed(grp_fu_834_p4);

assign sext_ln125_fu_1794_p1 = $signed(grp_fu_824_p4);

assign sext_ln127_fu_1789_p1 = $signed(grp_fu_814_p4);

assign sext_ln132_fu_1784_p1 = $signed(result_15_fu_1780_p1);

assign sext_ln134_fu_1775_p1 = $signed(grp_fu_804_p4);

assign sext_ln167_fu_1612_p1 = $signed(tmp_4_fu_1350_p3);

assign sext_ln40_fu_1328_p1 = $signed(imm_B_fu_1318_p6);

assign sext_ln41_fu_1333_p1 = $signed(imm_I_reg_2359);

assign sext_ln42_fu_1346_p1 = $signed(imm_J_fu_1336_p6);

assign source1_fu_1173_p33 = {{memory_q0[19:15]}};

assign sub_ln113_1_fu_1464_p2 = (32'd0 - trunc_ln113_1_fu_1454_p4);

assign sub_ln113_fu_1448_p2 = (34'd0 - add_ln113_fu_1434_p2);

assign sub_ln114_fu_1504_p2 = (3'd0 - p_and_t_fu_1496_p3);

assign sub_ln167_1_fu_1646_p2 = (32'd0 - trunc_ln167_1_fu_1636_p4);

assign sub_ln167_fu_1630_p2 = (34'd0 - add_ln167_fu_1616_p2);

assign sub_ln168_fu_1690_p2 = (3'd0 - p_and_t3_fu_1682_p3);

assign tmp_10_fu_1696_p3 = {{1'd0}, {trunc_ln168_fu_1674_p1}};

assign tmp_11_fu_1440_p3 = add_ln113_fu_1434_p2[32'd33];

assign tmp_12_fu_1510_p3 = {{1'd0}, {trunc_ln114_fu_1488_p1}};

assign tmp_4_fu_1350_p3 = {{tmp_8_reg_2386}, {tmp_7_reg_2381}};

assign tmp_9_fu_1622_p3 = add_ln167_fu_1616_p2[32'd33];

assign trunc_ln113_1_fu_1454_p4 = {{sub_ln113_fu_1448_p2[33:2]}};

assign trunc_ln113_2_fu_1470_p4 = {{add_ln113_fu_1434_p2[33:2]}};

assign trunc_ln114_1_fu_1492_p1 = sub_ln113_fu_1448_p2[1:0];

assign trunc_ln114_fu_1488_p1 = add_ln113_fu_1434_p2[1:0];

assign trunc_ln167_1_fu_1636_p4 = {{sub_ln167_fu_1630_p2[33:2]}};

assign trunc_ln167_2_fu_1652_p4 = {{add_ln167_fu_1616_p2[33:2]}};

assign trunc_ln168_1_fu_1678_p1 = sub_ln167_fu_1630_p2[1:0];

assign trunc_ln168_fu_1674_p1 = add_ln167_fu_1616_p2[1:0];

assign trunc_ln176_fu_2079_p1 = result_24_reg_2407[7:0];

assign trunc_ln178_fu_2063_p1 = result_24_reg_2407[7:0];

assign trunc_ln180_fu_2047_p1 = result_24_reg_2407[7:0];

assign trunc_ln182_fu_2031_p1 = result_24_reg_2407[7:0];

assign trunc_ln187_fu_2015_p1 = result_24_reg_2407[15:0];

assign trunc_ln189_fu_1999_p1 = result_24_reg_2407[15:0];

assign trunc_ln26_fu_848_p1 = g_pc[1:0];

assign trunc_ln408_fu_1670_p1 = write_addr_fu_1662_p3[16:0];

assign write_addr_fu_1662_p3 = ((tmp_9_fu_1622_p3[0:0] == 1'b1) ? sub_ln167_1_fu_1646_p2 : trunc_ln167_2_fu_1652_p4);

assign zext_ln113_fu_1428_p1 = source1_reg_2396;

assign zext_ln121_fu_1598_p1 = pos_fu_1480_p3;

assign zext_ln123_fu_1593_p1 = pos_fu_1480_p3;

assign zext_ln125_fu_1588_p1 = pos_fu_1480_p3;

assign zext_ln127_fu_1583_p1 = pos_fu_1480_p3;

assign zext_ln132_fu_1578_p1 = pos_fu_1480_p3;

assign zext_ln134_fu_1573_p1 = pos_fu_1480_p3;

assign zext_ln138_fu_1568_p1 = pos_fu_1480_p3;

assign zext_ln142_1_fu_1770_p1 = result_17_fu_1766_p1;

assign zext_ln142_fu_1563_p1 = pos_fu_1480_p3;

assign zext_ln144_1_fu_1761_p1 = grp_fu_834_p4;

assign zext_ln144_fu_1558_p1 = pos_fu_1480_p3;

assign zext_ln146_1_fu_1756_p1 = grp_fu_824_p4;

assign zext_ln146_fu_1553_p1 = pos_fu_1480_p3;

assign zext_ln148_1_fu_1751_p1 = grp_fu_814_p4;

assign zext_ln148_fu_1548_p1 = pos_fu_1480_p3;

assign zext_ln153_1_fu_1746_p1 = result_21_fu_1742_p1;

assign zext_ln153_fu_1543_p1 = pos_fu_1480_p3;

assign zext_ln155_1_fu_1737_p1 = grp_fu_804_p4;

assign zext_ln155_fu_1538_p1 = pos_fu_1480_p3;

assign zext_ln167_fu_1609_p1 = source1_reg_2396;

assign zext_ln172_fu_1724_p1 = write_addr_fu_1662_p3;

assign zext_ln28_fu_886_p1 = lshr_ln_fu_858_p4;

assign zext_ln379_fu_2287_p1 = ap_phi_mux_write_addr_0_ph_phi_fu_706_p40;

endmodule //processor
